### ISSUE TITLE
Yêu cầu - Bổ sung xml5 bệnh án nội trú đối với các thủ thuật được lập phiếu từ ngoại trú xong rồi chuyển vào nội trú

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#1]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/06/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) ``
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_test_xml` 
-  ![maba](https://img.shields.io/badge/Mã%20bệnh%20án-:-blue?style=plastic&logo=github) `2022003252` 
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) 'Dữ liệu máy chủ'

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bệnh án nội trú:
Trường hợp bệnh nhân có chỉ định thủ thuật và lập phiếu ở ngoại trú rồi chuyển vào nội trú.
XML5 không load được dữ liệu thủ thuật các trường hợp này.
hiện tại chỉ load được các thủ thuật được chỉ định và lập phiếu trong nội trú thôi.
Đề xuất bổ sung thêm để trường hợp này!
```
xml3 có 2 thủ thuật được lập phiếu!
![image](https://user-images.githubusercontent.com/96155021/175857536-e6dc331e-bfae-4fa5-97d6-b35769c5f096.png)

xml5 chỉ load được thủ thuật trong nội trú
![image](https://user-images.githubusercontent.com/96155021/175857604-876ffd01-f4dd-4047-906f-34c1d150dd42.png)

**Comment by nghivanbi** [comment]
- Hỗ trợ cập nhật khi chuyển vào nội trú để có thông tin như lập phiếu trong nội trú.

**Comment by le-an-87** [comment]
01/04/2023!
