### ISSUE TITLE
Yêu cầu - Bổ sung giấy ra viện theo TT18

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#105]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dalieu_ct_full_2023_02_07`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bổ sung giấy ra viện theo thông tư 18.
* BV đề nghị trường chẩn đoán có ghép mã icd.

```
TT 18
https://github.com/dh-hos/CONGVAN-QUYDINH-DENGHI/issues/4
![image](https://user-images.githubusercontent.com/96155021/226295116-d2ea8186-b21e-42c9-8511-ece5b90c37af.png)
![image](https://user-images.githubusercontent.com/96155021/226295231-492037ec-157d-43fb-810e-b26b4f758a0a.png)

hướng dẫn tt56 có yêu cầu ghép mã icd
![image](https://user-images.githubusercontent.com/96155021/226295370-f01be82c-1ff2-4916-849b-76b22b9c700c.png)

Giấy ra viện tt18 nội trú
![image](https://user-images.githubusercontent.com/96155021/226295607-5b54c86c-4908-412d-a809-410d39780955.png)

**Comment by le-an-87** [comment]
01/04/2023!

**Comment by nghivanbi** [comment]
Cập nhật: Prescription: v3.23.0525.2

**Comment by le-an-87** [comment]
đã bổ sung!
