### ISSUE TITLE
Yêu cầu - Bổ sung tham số chặn thời gian ra toa quá gần thời gian khám.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#106]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ALL**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbphuoclong_bli`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện tại chức năng chặn thời gian ra toa quá gần thời gian khám đã có, nhưng do 1 số BV thì BHXH chưa bắt đến lỗi đó, nên nhiều BV phàn nàn vì phải đợi lâu quá.
=> Đề nghị bổ sung tham số chặn thời gian ra toa quá gần thời gian khám, để BV tự quyết có sử dụng hay không.
![image](https://user-images.githubusercontent.com/99630883/227865993-217f76a9-269d-4f03-870a-9ddbf3377cbc.png)

**Comment by nghivanbi** [comment]
Cập nhật
Prescription: [v3.23.0327.1](http://www.fsend.vn/download/celb64UIuuJn-X-LdHeNXvyqbisKihqC)
