### ISSUE TITLE
Lỗi - Bệnh ngoại trú sai trạng thái đã khám

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#110]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_quan12_dakham`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023032686` - _**MaKB**_: `2304003642` - _**NgayKCB**_: `05/04/2023` - _**MaPhong**_: `A1.14` - _**MaDV**_: `10` - _**ThangKT**_: `04` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân khám 3 phòng, phòng 1, 2 có toa thuốc nhưng đã xóa
-> printer không thấy bệnh nhân để in bảng kê thanh toán CLS

```
bệnh nhân có cls
![image](https://user-images.githubusercontent.com/96155021/229982438-e7e59cc4-f3de-4f5d-b059-379c51226c25.png)

printer không load được bệnh nhân để in bảng kê
![image](https://user-images.githubusercontent.com/96155021/229982497-9a8f8ff4-e42d-4459-a452-16c2146eae4a.png)

Trạng thái dakham bảng khambenh có các toa đã xóa
![image](https://user-images.githubusercontent.com/96155021/229982642-c8f5555f-ee69-4370-b6e1-902e83225461.png)

**Comment by nghivanbi** [comment]
Này xóa toa mà nó không clear được sohd và dakham.
Kiểm xem xóa toa tại phòng khám hay có cấu hình cc gì không, test qua lại dùm anh.
