### ISSUE TITLE
Lỗi - SMS sai ngày tái khám so với toa thuốc

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#116]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `96133`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PKĐK HỒNG ĐỨC**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_pkhd_loi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018067864` - _**MaKB**_: `2304010128` - _**NgayKCB**_: `18/04/2023` - _**MaPhong**_: `PKS` - _**MaDV**_: `16` - _**ThangKT**_: `04` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân khám ngày 18/04/2023 có toa thuốc có số ngày uống lớn nhất = 15
-> chức năng tạo SMS lấy ngày tái khám sai so với ngày dự kiến hết hạn toa thuốc
```
![image](https://user-images.githubusercontent.com/96155021/233244685-c21503e5-394d-4ae1-8e64-b90955b59e03.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.23.0427.1](http://www.fsend.vn/download/S-nNSqflHdg0poZ36SWWzZr9kEZnttV8)

**Comment by le-an-87** [comment]
vào chức năng Theo dõi SMS là hiển thị bảng này lên hà anh @nghivanbi !
này có vấn đề gì không anh
![image](https://user-images.githubusercontent.com/96155021/235339982-09a0bc28-6f09-4d83-943f-a1358fcc30f8.png)

**Comment by le-an-87** [comment]
Chổ này test xong chưa anh @hvtuan1987 !
để em đóng issues lại anh

**Comment by hvtuan1987** [comment]
Hổm anh báo chổ gởi SMS của Register á !

Vào Th 2, 15 thg 5, 2023 vào lúc 07:58 lê ân ***@***.***>
đã viết:
