### ISSUE TITLE
Yêu cầu - BANT trang in Phần Bệnh Án gắn tên Bác sĩ kết thúc hồ sơ bệnh án.

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#122]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77120`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA MEDIC SÀI GÒN**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_medicsaigon1_042023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

BANT đã điều trị nhiều ngày cùng 1 Bác sĩ, ngày cuối cùng khi kết thúc bệnh án là Bác sĩ khác. 
Khi bác sĩ khám cuối và kết thúc hồ sơ bệnh án thì cả 3 phần trên trang in đều thể hiện tên Bác sĩ khám cuối.

Yêu cầu :
Trên nội dung Hồ sơ in ra gồm 3 phần : 
I. Phần Chung - thể hiện tên bác sĩ đăng nhập khám.
II. Phần Bệnh án - thể hiện  tên Bs lập HSBA.
III.Phần tổng kết - thể hiện  tên bác sĩ đăng nhập khám.

https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/3f105bf0-1541-4214-aad2-3718975e14fc

**Comment by lqbinh1987** [comment]
Cho em cái deadline để e phản hồi với khách hàng nhe anh @nghivanbi .

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.0704.4](http://www.fsend.vn/download/HZPAhHIaEnzdKS2kE2UEqR5xb7OaHPi8)
