### ISSUE TITLE
Yêu cầu - Hỗ trợ cấu hình số tiền BHYT cảnh báo đặc thù không theo mức lương cơ sở BV Quận 12

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprescription#124]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận 12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquan12`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bệnh viện yêu cầu đặc thù cho phép cấu hình tổng chi phí thuộc BHYT của bệnh nhân ngoại trú 
dưới mức lương cơ sở. Số tiền này do đơn vị tự cấu hình, để hướng dẫn bệnh nhân tạm ứng trước 
tránh trường hợp bệnh nhân bổ về !

```

**Comment by nghivanbi** [comment]
Sử dụng tham số: ngoaitru.vuottran (số tiềm trần BV muốn).
Cập nhật Prescription: [v3.23.0515.2](http://www.fsend.vn/download/xVkY2r77L07k753KXHOMeqpGIBnCeknL)
