### ISSUE TITLE
Yêu cầu - BUILD THÊM MÃ BV TTYT BÌNH LONG SỬ DỤNG GÓI CẢNH BÁO CHỐNG CHỈ ĐỊNH

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#125]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `70071`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT THỊ XÃ BÌNH LONG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_bvbinhlong_chongchidinh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Gói chống chỉ định đã báo giá và đồng ý triển khai > Thêm mã BV 70071 để áp dụng tham số cảnh báo trên Prescription

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.9515.1](http://www.fsend.vn/download/-nq_oVRl8eIQwZ9a2CBsW5dTSd1zXplM)
