### ISSUE TITLE
Lỗi - Trích BBHC không hiển thị đủ thành viên - BV Phụ Sản

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#127]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusanct_2023039856_2305014369_trichbbhc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/mF8J5xSD8)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023039856` - _**MaKB**_: `2305014369` - _**NgayKCB**_: `24/05/2023` - _**MaPhong**_: `26` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Trích biên bản hội chẩn hiển thị không đủ thành viên trong danh sách thành viên

```
DS Thành viên 10
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/42e22e74-a0ec-4e7c-b1d4-b0989522c819)

Trích biên bản hội chẩn chỉ hiển thị được 6 thành viên
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/0660eeb3-48ec-4e39-8e19-d9c164cf9684)

**Comment by nghivanbi** [comment]
Chỗ này hỗ trợ chuyển qua mẫu tự thiết kế rồi á @le-an-87. Tham số: hoichan.customize
