### ISSUE TITLE
Lỗi - Chức năng đổi mã bệnh án không cập nhật mã bệnh án mới cho phiếu PT-TT, ekip, hội chẩn, chăm sóc

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#13]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **1/8/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77127`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Medic Sài Gòn 2**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_medicsg_matphieuthuthuat`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022006991` - _**MaKB**_: `2208000067` - _**MaBA**_: `N2022000766ABC` _**NgayKCB**_: `1/8/2022` - _**MaPhong**_: `ĐY` - _**MaDV**_: `20` - _**ThangKT**_: `08` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Khi sử dụng chức năng đổi mã bệnh án thì một số mẫu không cập nhật lại mã bệnh án mới như:
-- Phiếu Phẫu thuật, thủ thuật
-- Ê kíp phẫu thuật thủ thuật
-- Hội Chẩn
-- Chăm sóc

![ảnh](https://user-images.githubusercontent.com/97272332/182071478-ddd63425-6efc-4d73-b845-6dba10390f05.png)
![ảnh](https://user-images.githubusercontent.com/97272332/182071542-43f63ea0-4f4d-4132-bc4e-8403bf8eccb0.png)

**Comment by chauthanhtra** [comment]
có thời gian anh fix lỗi này nha anh

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0909.1](http://www.fsend.vn/download/eFWD1L8f6xm74ZY6j44SRKcPf1kvYoMq)

**Comment by chauthanhtra** [comment]
ok rồi anh
