### ISSUE TITLE
Lỗi - Sai ti lệ, thành tiền công khám thu phí khi bệnh nhân BHYT được chỉ định thêm công khám thứ 2 trở đi

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#132]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/6/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77156`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Phúc Gia Khang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phucgiakhang1206_dsnhanbenh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/v5WuJEf1f)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000880` - _**MaKB**_: `2306000227` - _**MaBA**_: `MaBA` _**NgayKCB**_: `16/6/2023` - _**MaPhong**_: `KB9` - _**MaDV**_: `02.03` - _**ThangKT**_: `06` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Bệnh nhân BHYT khi chỉ định thêm công khám thứ 2 trở đi là công khám thu phí thì phần mềm tính lại tỉ lệ thanh toán và thành tiền của công khám theo tỉ lệ -> Sai số tiền công khám thu phí

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/c946f159-03f3-45cf-a210-b74b17fcda4e)

- Trường hợp công khám đầu là công khám thu phí . công khám chỉ định sau là công khám BHYT thì công khám BHYT cũng bị tính tỉ lệ thanh toán và thành tiền lại
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/ca41805b-d6c5-4738-893f-7346fd2d8465)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.0628.1](http://www.fsend.vn/download/XUX2eWnAccmjhenT72jmsfaxNN39Vcyc)
