### ISSUE TITLE
Yêu cầu - Giấy ra viện BANT: Mã y tế trên giấy ra viện ghép mã bệnh án (mã y tế/mã bệnh án) như ở nội trú

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#134]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_cairang_giayrv_bant`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Rq7fXQ1Fa)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Bệnh viện yêu cầu mã y tế trên giấy ra viện BANT có thể ghép mã bệnh án phía sau mã y tế (mã y tế/mã bệnh án) như ở nội trú

- Hiện tại para mayte trên giấy ra viện không lấy được thông tin tham số mayte -> lấy mã y tế theo tham số mayte
- Không có para maba (nên không ghép mã y tế vào mã bệnh án được)
=> C1: làm theo nội trú mã y tế ghép mã bệnh án theo tham số: mayte và nt.maytesoba
=> C2: thêm para maba để bệnh viên tự ghép mã y tế vào para maba 

Dữ liệu bệnh nhân BANT theo đợt ra viện tháng 04/2023

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/2e66386f-4687-4ee4-b2c1-bccd56849be8)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/2af71049-6013-4351-b5f2-ff7865a69bce)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/9b9906a6-1a7a-4387-a10e-96bec1b45945)

**Comment by nghivanbi** [comment]
Cập nhật: cấu trúc mayte = tham số "mayte"+"/"+"06 số cuối bệnh án" (này đăng bắt theo bệnh viện)
Prescription: [v3.23.0628.2](http://www.fsend.vn/download/I1N9Nsq0jJCnrFOMmwWsTJrDHdaCiLaw)

**Comment by chauthanhtra** [comment]
(này đăng bắt theo bệnh viện) là làm riêng cho mã BV 92006 hả anh

**Comment by nghivanbi** [comment]
Uh test coi ok chưa, nếu các bv yêu cầu nhiều cái này mới chuyển sang tạo tham số.
