### ISSUE TITLE
Yêu cầu - BN BHYT Cho phép chỉ định thêm CLS khi đã cấp toa 

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprescription#135]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74206`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Medic Miền Đông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_medicmd_cdcls`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/hkTlV1WnD

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
BN BHYT Cho phép chỉ định thêm CLS khi đã cấp toa.
Khi sử dụng tham số pre.canhbaoclsthuchien =2: KHÔNG CHO lưu toa khi Có cận lâm sàng chưa thực hiện
nhưng tham số bắt thêm trường hợp không Cho phép chỉ định thêm CLS khi đã cấp toa

```
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/c9d18071-4bd4-4acb-a986-c38f7de93176)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/a1231ea9-03b3-4bab-85d2-3decf8eafc20)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription:[ v2.23.06.30.2](http://www.fsend.vn/download/W4I9ec0Tph2DPX2E1KazL0ReWhSOEkT-)

**Comment by minhduc2it** [comment]
đã test chức năng Cho phép chỉ định thêm CLS khi đã cấp toa ok
