### ISSUE TITLE
Lỗi - Chức năng cập nhật lương CB

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#136]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dongtay_chuyenluong`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/lQU2fOehr)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023027565` - _**MaKB**_: `2306030934` - _**MaBA**_: `N2023002823` _**NgayKCB**_: `30/06/2023` - _**MaPhong**_: `H27` - _**MaDV**_: `K17` - _**ThangKT**_: `06` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng cập nhật lương cơ CB:
- bệnh nhân đã nhận bệnh và lập bệnh án ngoại trú ở mức lương 1,490,000 muốn chuyển sang lương mới 1,800,000
-> phần mềm Không cập nhật được mức lương cơ bản đối với bệnh án ngoại trú thanh toán đợt.

* chức năng chuyển lương cơ bản ngoại trú không chọn được từng bệnh
-> nếu không cho chọn từng bệnh thì bỏ chức năng chọn tránh trường hợp người dùng hiểu nhằm đã chọn chuyển lương rồi mà phần mềm không chạy được.
```
Không lick chọn được từng bệnh nhưng chọn chuyển lương CB vẫn báo thành công gây hiểu nhằm cho người dùng
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/59ad2efc-c6a5-40c6-911c-01e35bb9978f)

Chuyển lương BANT thanh toán đợt báo thành công
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/50a0b4f1-d4d8-4203-bf83-1ca81fccca0c)
bảng kê bant vẫn tính ở mức lương củ 1,490
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/e5f3d147-755e-42ff-bc80-ba37fbe72018)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.0630.3](http://www.fsend.vn/download/W_Ajc20e-84quEmNZg_Zxq-DCPVD_rwY)

**Comment by le-an-87** [comment]
Đã fix!
