### ISSUE TITLE
Lỗi - Hiệu chỉnh thông tin không cho gõ tìm kiếm

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprescription#137]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `bi_omon_bangke
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Hiệu chỉnh thông tin trên Prescription không cho gõ tìm kiếm

```
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/8f573b3f-0ffc-43d8-a7ef-e2ffade45507)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.0704.1](http://www.fsend.vn/download/ul_tiuk80vPDb8G6Tc11odPMioeu3GvN)

**Comment by minhduc2it** [comment]
2 ô này vẫn không cho tìm kiếm

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/d19f3ddb-0dab-416f-9b9e-39409fb6d26a)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v2.23.0704.2](http://www.fsend.vn/download/X2iVFJ4_cM4wKJGvNPm-HUX_s6Ry3QSU)

**Comment by minhduc2it** [comment]
đã test ok
