### ISSUE TITLE
Lỗi - Khi hiệu chỉnh thông tin sẽ thêm công khám mới cho bệnh nhân và không xóa công khám củ

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#14]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_omon_lechmau21_thang7_2207016157`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [``](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2017036292` - _**MaKB**_: `2207016157` - _**NgayKCB**_: `21/07/2022` - _**MaPhong**_: `03` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2022`

-  ![Benh_nhan_test](https://img.shields.io/badge/Chi%20bệnh%20nhân%20test-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022000001` - _**MaKB**_: `2208000001` - _**NgayKCB**_: `02/08/2022` - _**MaPhong**_: `03` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Prescription khi Hiệu chỉnh thông tin chỉnh từ đối tượng này sang đối tượng khác. khi tiếp tục hiệu chỉnh nữa sẽ insert thêm công khám mới nhưng không xóa công khám củ.
 -> bệnh nhân sẽ có nhiều công khám trong 1 lần khám!
```
Bệnh nhân lỗi
![image](https://user-images.githubusercontent.com/96155021/182274031-33645028-aaff-411d-9995-22f023f5a58a.png)
Nhật ký chỉnh thông tin
![image](https://user-images.githubusercontent.com/96155021/182274418-2b83638a-431a-428c-b7fc-9bb6c391b464.png)

**Comment by le-an-87** [comment]
Lỗi này chưa fix phải không anh!

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.09.09.2](http://www.fsend.vn/download/Swb7zjJI_5RROqwe3BbBI05mRm1-E9EW)

**Comment by le-an-87** [comment]
đã fix!
