### ISSUE TITLE
Lỗi - Cập nhật sai tuyenxml khi khám bệnh

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#141]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/7/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_trungan_072023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/r5zeiBhFU)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000552` - _**MaKB**_: `2307000150` - _**MaBA**_: `MaBA` _**NgayKCB**_: `12/7/2023` - _**MaPhong**_: `01` - _**MaDV**_: `01` - _**ThangKT**_: `07` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi khám bệnh phần mềm Prescription cập nhật lại sai tuyến XML psdangky.tuyenxml của bệnh nhân 
Khi đăng ký bệnh nhân ở trạng thái cùng tuyến tuyenxml =0 , khi khám bệnh cho chẩn đoán lưu lại thì tuyenxml = 1

- Khi mới đăng ký
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/cc71464e-eaf1-48ca-8169-90fc0f95d941)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/c5b256bf-4c19-4c2c-9825-14f3ee00ac65)

- Khi khám xong
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/df9e12e3-4e48-4ec8-befd-fee22e4386dd)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/3a220794-0fd6-4809-9b13-e640ba647876)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/43f17dee-fd8b-4d0c-a7de-4373143237e7)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.07.13.2](http://www.fsend.vn/download/v5l84XLArCQcZnwNwaXdAx3S9jfrX-SH)
