### ISSUE TITLE
Lỗi - Form kết thúc bệnh án không load được thông tin bệnh đã kết thúc

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#142]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_ravien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/91dSbA58E)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023024473` - _**MaKB**_: `2307007923` - _**MaBA**_: `N2023007256` _**NgayKCB**_: `18/07/2023` - _**MaPhong**_: `11` - _**MaDV**_: `16` - _**ThangKT**_: `07` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
From kết thúc điều trị không lấy được thông tin đã nhập kết thúc
-> in giấy ra viện không có thông tin

```
Phiên bản 13/07/2023
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/a9eb00e1-9e29-405e-98a6-db73aabe5411)
Phiên bản 30/06/2023 không bị lỗi
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/f5c8b065-7838-41c0-8063-b91cc27ee652)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.0825.2](http://www.fsend.vn/download/PvR6ji7B1aaTYQ6wDUVfNhIWynCqsACA)

**Comment by le-an-87** [comment]
Đã fix!
