### ISSUE TITLE
Lỗi - Bệnh nhân BHYT không in được phiếu chỉ định CLS thu phí

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#144]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà i**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **1/8/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nhi Đồng CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `bi_nhidong_phieuchidinhcls`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/DzJyHry3A)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019094050` - _**MaKB**_: `2308000807` - _**MaBA**_: `MaBA` _**NgayKCB**_: `1/8/2023` - _**MaPhong**_: `17` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BV sử dụng mẫu phiếu chỉ định CLS chuẩn. Bệnh nhân BH chỉ định CLS thu phí ở 1 số mẫu không in được phiếu chỉ định CLS
- CLS X-quang không in được tên CLS
- CLS Vi sinh,  Rối loạn đông cầm máu không có cấu hình lên mẫu chuẩn chỉ in được phiếu kết quả mặc định mà không in được phiếu chỉ định có tên CLS
- CLS Huyết học không có cấu hình lên mẫu chuẩn không thể hiện trang in

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/ca8f1c59-df63-4776-82c3-1c1ca12144fd)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/aaa67c81-543a-42ad-8cab-d29972e2e737)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/e53b23c8-f179-43f0-aee9-3c94069ed668)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.0802.1](http://www.fsend.vn/download/hzHwSSoyBpXUJARwLjJUPVdegBARRxP0)

**Comment by chauthanhtra** [comment]
- CLS Xquang in được rồi

- Còn mấy mẫu Huyết học,, Vi sinh, Rối loạn đông cần máu chưa được nha anh @nghivanbi

**Comment by nghivanbi** [comment]
cụ thể dùm anh mã cls để test á

**Comment by chauthanhtra** [comment]
Các mã CLS theo kho:
- Huyết học: DI06  (Không thấy phiếu in)
- Rối loạn đông cầm máu: TH104  (chỉ in được mẫu mặc định mà không có CLS) không có cấu hình CLS lên mẫu mặc định
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/6ec9c3b5-30f0-4fa7-af26-1b80716b0740)

- Vi Sinh: RO01   (chỉ in được mẫu mặc định mà không có CLS) không có cấu hình CLS lên mẫu mặc định
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/1f89a45b-c8dd-40af-a7fe-4b1ed03ab1e8)

- Còn về CLS X-Quang thì phiếu BHYT  (mã CH01) và thu phí (mã CH36) nhìn giống nhau. đều có mã BHYT trên phiếu không biết phiếu nào BH phiếu nào thu phí . Em không biết BV có cần phân biệt không

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/3a5325b2-b9e1-42dd-b084-b07502055f35)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/58055bfc-ba4b-48d6-912f-cb6d4c1cb0ec)
