### ISSUE TITLE
Lỗi - chỉ định cls cho bệnh nhân BANT thu phí phần mềm lấy giá USD

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#147]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `60152`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Phúc**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamphuc_kochiphi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/0AxldaqjI)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023031293` - _**MaKB**_: `2308001193` - _**MaBA**_: `N2023000561` _**NgayKCB**_: `18/08/2023` - _**MaPhong**_: `10` - _**MaDV**_: `22` - _**ThangKT**_: `08` - _**NamKT**_: `2023`

   > _**MaDT**_: `06` - _**MAQG**_: `VN`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân BANT đối tượng thu phí khi chỉ định cls phần mềm lấy giá USD.

bệnh nhân thuộc quốc tịch VIỆT NAM

* Đối tượng thu phí ngoại trú lấy giá dân bình thường.

```
Chỉ định cls TH69
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/2f93f117-619a-4df0-afe9-317487dc4f0a)

Thông tin nhận bệnh
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/9784e0c4-98c0-40c0-b579-b94220005688)

DM CLS
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/6f14c4cd-368b-4336-ad5e-f8a79fccdc2c)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.0818.3](http://www.fsend.vn/download/IqsS680u_gVlKoWHyIZ2NaRP8pbtmP0N)

**Comment by le-an-87** [comment]
Đã fix!
