### ISSUE TITLE
Lỗi - Medic Miền Đông: BANT Kết thúc khám bắt chọn diễn biến sau cùng

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprescription#150]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74206`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Medic Miền Đông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_medicmd_ketthucbant`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/g2t8Ff7Ip

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaPhong**_: `18` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh án ngoại trú: Khám xong Kết thúc liền bản Pre 3.23.0906.1 Bắt chọn diễn biến sau cùng
Đơn vị yêu cầu: Khám xong cho kết thúc liền không bắt chọn diễn biến sau cùng
bản Pre 3.23.0630.10 có chức năng này

```
Bản Pre 3.23.0906.1
https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/26d39ffb-1cbe-4f0a-b9ae-5674822ca2c0

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/bbfb9db2-851b-4684-b39e-3aa812b0b7f9)

Bản Pre 3.23.0630.10
https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/ac2b1c95-16c3-4c96-8ba9-27fd982ee77f

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/dbc7536c-cb82-42e2-ace6-9d19f110ff3c)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.0919.2](http://www.fsend.vn/download/qPB8lzp4mY4DNI6-QBLvQxcxOK9kkNMV)

**Comment by minhduc2it** [comment]
đã test ok
