### ISSUE TITLE
Lỗi - Cập nhật thời gian diễn biến.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#156]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbthanhtri_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2014023199` - _**MaKB**_: `2309004551` - _**MaBA**_: `N2023001297` _**NgayKCB**_: `25/09/2023` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Có 2 Trường hợp:
1. BANT theo đợt: BN tái khám, chọn Đổi diễn biến để tái khám, chỉ định CLS lúc 8:16:02, sau đó nhấn nút Chỉnh diễn biến, cập nhật xong nhấn nút Lưu, thì trong bảng qtdieutri cập nhật lại thời gian lúc chỉnh diễn biến là 8:18:36 => Lỗi trên cổng giám định **Giờ diễn biến** ở bảng XML5 lớn hơn **Giờ CLS**, đề nghị khi Chỉnh diễn biến thì không cập nhật lại thời gian của diễn biến đó.
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/9833ef64-605e-4ad4-9023-02a0efaebf51)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/a9537646-d924-4fc3-b3da-3f653bc86e6a)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/5afb2796-e758-4f92-a032-88599bc94ba8)

2. BANT theo ngày khám: BN khám lần đầu hoặc tái khám, sau khi đổi diễn biến để tái khám, chọn phân loại bệnh, Lưu thì phần mềm ghi nhận bảng chidinhcls.ngaykcb của công khám tương ứng phân loại, sau đó chỉ định CLS khác, chỉ định xong cũng làm theo tác nút Chỉnh diễn biến như hình trên, chỉnh diễn biến xong nhấn Lưu thì phần mềm cập nhật lại giờ hiện tại cho chidinhcls.ngaykcb của công khám => giờ y lệnh công khám sau giờ lệnh các CLS khác => BH xuất toán.

**Comment by nghivanbi** [comment]
Cập nhập:
Prescription: [v2.23.0925.1](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3)
