### ISSUE TITLE
Lỗi - BANT in toa trắng không hiển thị chẩn đoán, mã ICD

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprescription#158]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/10/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74206`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Medic Miền Đông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_medic_captoa
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/GpGOyUwfc

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > - _**MaBN**_: `2020023862 - _**MaKB**_: `2310001678` - _**MaBA**_: `N2023013214 - _**NgayKCB**_: `04/10/2023` - _**MaPhong**_: `21` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
In toa trắng trên BANT không hiển thị chẩn đoán và mã ICD

```
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/d366c8c0-5ab2-406f-982a-e34de3cbf421)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/88cdea0c-fca4-414d-b684-04872a29450d)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/ae67551c-a567-44c1-8068-81e54695fff8)

**Comment by nghivanbi** [comment]
Cập nhập Pre mới nhất nhé

**Comment by minhduc2it** [comment]
đã test ok
