### ISSUE TITLE
Yêu cầu - chức năng phiếu hẹn

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#16]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Mắt-RHM CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_matct`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu có chức năng phiếu hẹn trên form BANT khi tham số bant.quyettoan=0.
Hiện tại khi tham số bant.quyettoan=1 thì có hiện chức năng phiếu hẹn để lập.

![image](https://user-images.githubusercontent.com/99630883/183840903-a1832dfe-3fcb-4e37-9522-7bceae722750.png)
![image](https://user-images.githubusercontent.com/99630883/183840984-558be882-d530-417c-972b-723ea36e952d.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0815.1](http://www.fsend.vn/download/QjgHuTplvOwRLSsTDqNu6gPl5uJvLf8_)
