### ISSUE TITLE
Lỗi - Sai trạng thái KCB khi chỉnh tình trạng (bình thường qua cấp cứu) form khám bệnh và Sổ khám bệnh bị lỗi khi xem

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#160]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **9/10/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74206`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Medic Miền Đông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_medic_md_capcuu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/RNUh4uMko)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023061474` - _**MaKB**_: `2310003614` - _**MaBA**_: `N2023013442` _**NgayKCB**_: `08/10/2023` - _**MaPhong**_: `01` - _**MaDV**_: `CC` - _**ThangKT**_: `10` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. PK báo lỗi: Bệnh nhân bệnh án ngoại trú có check cấp cứu nhưng in ra bảng kê thì ghi nhận bệnh nhân trái tuyến
      + Nguyên nhân là do bệnh nhân được đăng ký khám trái tuyến được hưởng cùng tuyến (psdangky.tinhtrang =0, psdangky.tuyenxml =1) khi cho chẩn đoán tại form khám bấm chọn tình trạng bệnh là cấp cứu. lập bệnh án ngoại trú thì phần mềm ghi nhận bệnh án có check cấp cứu nhưng in bảng kê ghi nhận bệnh nhân trái tuyến (do bnnoitru.tinhtrangvv =1, bnnoitru.tuyenxml =1) 
-> Lỗi chức năng chỉnh tình trạng bệnh khi khám bệnh
      > Cập nhật lại tuyến XML khi thay đổi tình trạng bệnh lúc khám cho phù hợp

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/12087fa5-ddfd-4341-9962-71da6b41ecbc)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/e5579313-113a-4d49-aad6-906ba5fc1813)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/7c5c346b-ff86-40df-866b-5875f466a254)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/087bfcdd-98de-4fc5-a5d6-ed56a2479d3f)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/f8a4240f-75b0-45f0-adfa-e9a69200232b)

2. Tương tự đối với bệnh nhân ngoại trú
      + Bệnh nhân trái tuyến được hưởng như cùng tuyến khi chỉnh tình trạng bệnh bình thường qua cấp cứu lúc khám bệnh thì bảng kê ghi nhận bệnh nhân trái tuyến (Mã BN: 2023061477, makb: 2310003618 , mã khoa: CC, mã phòng: 01, ngày: 09/10/2023)
      + Bệnh nhân nhận bệnh Cấp cứu khi chỉnh tình trạng bệnh cấp cứu qua bình thường lúc khám bệnh thì bảng kê ghi nhận bệnh nhân thông tuyến  (Mã BN: 2023061475, makb: 2310003616 , mã khoa: CC, mã phòng: 01, ngày: 09/10/2023)

3. Phần mềm Register , Prescription báo lỗi khi xem sổ khám bệnh

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/e2543f14-fade-4f0a-a120-f85fc7c17348)

**Comment by chauthanhtra** [comment]
Xem cái lỗi Sổ khám bệnh trước giúp em nha anh @nghivanbi , Prescription 06/10 còn lỗi

**Comment by nghivanbi** [comment]
Cập nhật: v 3.23.1011.2 nhé

**Comment by chauthanhtra** [comment]
Prescription 11/10 vẫn lỗi nha anh

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/2e0d3991-f25f-47af-b512-f99876780446)

**Comment by nghivanbi** [comment]
Cập nhật: [v 3.23.1012.1](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3) nhé

**Comment by chauthanhtra** [comment]
Sổ khám bệnh được rồi nha anh.
