### ISSUE TITLE
Lỗi - Kiểm tra sinh hiệu khi khám bệnh (BV Trà Cú)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#168]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tracu_sinhhieu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/i7nd0USdW)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019039293` - _**MaKB**_: `2311001722` - _**NgayKCB**_: `03/11/2023` - _**MaPhong**_: `07` - _**MaDV**_: `YHCT` - _**ThangKT**_: `11` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
BV sử dụng tham số ktsinhhieu = 1 bắt buộc nhập sinh hiệu mới được phép khám bệnh
1. Bệnh nhân chưa có thông tin sinh hiệu vẫn vào khám được.
  - Trường hợp bệnh nhân được nhập thông tin sinh hiệu nhưng KHÔNG LƯU -> phần mềm vẫn cho khám bệnh.
  (Phần mềm đang bắt thông tin trên form không bắt ở dữ liệu bệnh nhân).

2. Bệnh nhân đã in phiếu thanh toán rồi vẫn chỉnh được thông tin sinh hiệu.
  -> Khách hàng đề nghị khi in bảng kê rồi thì sẽ không cho cập nhật sinh hiệu
```
1.  > **Nhập sinh hiệu nhưng không lưu vẫn khám được** -> khi làm tươi danh sách lại bị mất thông tin sinh hiệu
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/e62ff41c-43d3-4fa4-ae46-9d1690d53e74)

2. > **Bệnh nhân đã in phiếu thanh toán rồi vẫn chỉnh được thông tin sinh hiệu**.
- BN đã in phiếu
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/ec659179-0dc7-4dc9-a19c-6da2297898c1)
- Form khám bệnh vẫn cho phép cập nhật sinh hiệu bệnh nhân đã in phiếu thanh toán
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/79227fc4-7983-4d31-837b-f85879859dc9)

**Comment by nghivanbi** [comment]
Cập nhật: [Prescription 3.23.1107](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3)

**Comment by le-an-87** [comment]
[Đã fix! ](https://drive.google.com/file/d/1zPTpwALnG4BY-R5SvK7vgbzn5VvLu2-e/view?usp=drive_link)
