### ISSUE TITLE
Lỗi - Trích biên bản hội chẩn khi in không hiển thị hết tất cả các thành viên & bị mất chữ phần kết luận

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#17]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_bbhc_matchu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [``](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022058248` - _**MaKB**_: `2208005242` - _**NgayKCB**_: `10/8/2022` - _**MaPhong**_: `36` - _**MaDV**_: `15` - _**ThangKT**_: `08` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Trích biên bản hội chẩn khi in ra:
- Không hiển thị hết tất cả các thành viên (hiện tại chỉ hiển thị được 4 thành viên).
- Phần kết luận bị mất chữ.

```
Trích biên bản hội chẩn
![image](https://user-images.githubusercontent.com/96155021/184099677-03a531b0-56d9-4b02-9084-da6e67e8f16b.png)

Danh sách thành viên
![image](https://user-images.githubusercontent.com/96155021/184099149-d01cd0b4-7306-413d-b59e-24c2cadff1b4.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0812.1](http://www.fsend.vn/download/uRIPKRXzrgjPeKyYfef4qqxqwb4KXoYO)

**Comment by le-an-87** [comment]
đã fix!
