### ISSUE TITLE
Lỗi - Phiếu vào viện tự thiết kế trường Tóm tắt kết quả lâm sàng không hiển thị khi người dùng có nhập thông tin

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprescription#170]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện đa khoa huyện Phước Long**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphuoclong_phieuvv`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022011639` - _**MaKB**_: `2311003724` - _**MaBA**_: `MaBA` _**NgayKCB**_: `08/11/2023` - _**MaPhong**_: `08` - _**MaDV**_: `10` - _**ThangKT**_: `11` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Bệnh viện đang sử dụng Phiếu vào viện tự thiết kế trường Tóm tắt kết quả lâm sàng có nhập thông tin nhưng in phiếu vào viện không hiển thị (HÌnh dưới)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/049fefe3-260e-4f65-9450-1558b81fe93b)

Phiếu vào viện in ra không hiển thị được trường Tóm tắt kết quả lâm sàng

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/7feed16f-c72f-49b3-bf3c-b0ada1093a4f)

```

**Comment by nghivanbi** [comment]
Cập nhật: Prescription [v3.23.11.10.3](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3)

**Comment by hvtuan1987** [comment]
ok rồi á !
