### ISSUE TITLE
Yêu cầu - Hỗ trợ ghép thêm mã ICD 10 trước tên chẩn đoán giấy ra viện Bệnh án ngoại trú

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprescription#175]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87044`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quân Dân y tỉnh Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquandanydt_hoichan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

Hiện tại giấy ra viện BANT không có mã ICD như hình dưới
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/9d8fc48b-1b13-473e-8727-2f4a46c86146)

Bệnh viện nhờ hỗ trợ giấy ra viện có ghép mã ICD giống như trong nội trú hình dưới
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/1c30d39f-f916-4458-8b9c-2d1c20bd62f3)

Nếu là BANT thường thì lấy mã ICD10 ghép với tên chẩn đoán ICD 10, nếu là bệnh án YHCT có chẩn đoán mã YHCT 
thì ghép mã YHCT ghép với tên chẩn đoán

Đang sử dụng mẫu thiết kế
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/c71cb665-1856-46f5-be23-d322908ee3d8)

**Comment by nghivanbi** [comment]
Thêm para "maicd": ghép hết mã chẩn đoán. Đơn vị tự thiết kế.

**Comment by hvtuan1987** [comment]
Đã ok rồi á anh Bi !
