### ISSUE TITLE
Lỗi - Giấy hẹn tái khám bệnh nhân thu phí

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#177]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmach_ct_112023_giayhenbnthuphi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/eiS63A4b4)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `23022590` - _**MaKB**_: `2311007848` - _**MaBA**_: `MaBA` _**NgayKCB**_: `10/11/2023` - _**MaPhong**_: `21` - _**MaDV**_: `01` - _**ThangKT**_: `11` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân thu phí khi bấm in phiếu hẹn tái khám thì phần mềm báo lỗi

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/fe9e9e25-a89d-48ae-aa94-0acc81aa92d2)

**Comment by chauthanhtra** [comment]
Xem giúp em chổ này nha anh @nghivanbi 
BV Ung Bướu cũng đang cần

**Comment by nghivanbi** [comment]
ok để anh kiểm dl

**Comment by nghivanbi** [comment]
<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h2>DHG.Hospital Prescription</h2>
  <h2>Ver: 3.24.0111.1</h2>
  
  
</div>

## Tập tin cài đặt (Setup Files)

<div align="center">
  
[![Tải về](https://img.shields.io/badge/Tải%20file%20cài%20đặt-Google-blue?logo=googledrive)](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3) 
  
</div>

## Nội dung cập nhật

<div align="center">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprescription/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by chauthanhtra** [comment]
Bệnh nhân này thu phí anh bỏ check Đúng tuyến nha anh

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/185f8dda-e1ce-4866-b3d1-5bda51cd3d2a)

**Comment by nghivanbi** [comment]
Lấy mới lại nhé @chauthanhtra

**Comment by chauthanhtra** [comment]
ok rồi anh
