### ISSUE TITLE
Lỗi - BA ngoại trú bấm in phiếu 01 báo lỗi

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprescription#178]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) duc_cairang_bangoai`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/1rI5VNvl3

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023015484` - _**MaKB**_: `2312000857` - _**`MaBA`**_: `N2023003360` - _**NgayKCB**_: `05/12/2023 - _**MaPhong**_: `07` - _**MaDV**_: `04` - _**ThangKT**_: `12` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bấm in phiếu 01 kết thúc tái khám báo lỗi không in được phiếu 01

```
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/51a7e28c-7d6b-4740-8a15-d1ada086e6a3)

**Comment by nghivanbi** [comment]
+ Chi tiết lỗi:
Phiên bản :2023.12.11.101539AM
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at OTH.Adapter.HosBHXH.AGiamDinh.CreateBangKeChiPhi()
   at OTH.XForms.HosPrinter.BKChiPhiKCB6556.CreateDataSource()
   at HosPrinter.Classes.ClsHauThem.ExportXMLAndPrint6556(String xml_MaBN, String xml_MaKB, Form parentForm, GridEX dgCls, String strTKLapToa, String strTenPK, Int32 solanin, String strTKNhapBenh, GridEX dgThuoc, v_FormInPhieu01 vFormInPhieu01, String strTKLapToa_Manv_PhuongNam, QuayPhatThuoc quayPhatThuoc)
   at HosPrinter.Forms.FrmInPhieuKK.InMauBHYT01BV(String pThemoi)
   at HosPrinter.Forms.FrmInPhieuKK.btnIn_Click(Object sender, EventArgs e)

+ Form sử dụng:
this.frmInPhieuKK = new HosPrinter.Forms.FrmInPhieuKK(false, this.bBant, false, LibraryApp.ClsThamSo.TayYKhongTruKhoIn38BV, LibraryApp.ClsThamSo.DongYKhongTruKhoIn38BV,
                        this.sMabn, this.bBant ? this.sMaba : this.dgQuaTrinh.GetValue("makb") + "", License.LicSupport.TenSYT, License.LicSupport.TenBV, License.LicSupport.DienThoai, FrmMain.strThangKT, FrmMain.strNamKT,
                        FrmMain.dNgayLV, strMaKhoCP, strMaKhoCPCha, 1, FrmMain.strTenMay, FrmMain.strUserName, false)
+ Cụ thể giá trị:
this.frmInPhieuKK = new HosPrinter.Forms.FrmInPhieuKK(false, false, false, "0","0",
                        2023015484, 2312000857, License.LicSupport.TenSYT, License.LicSupport.TenBV, License.LicSupport.DienThoai, "12", "2023",
                        {12/5/2023 12:00:00 AM}, "05", "14", 1, "NG2", "admin", false)

@ongtrieuhau check lại dùm anh cái nhé. ps lỗi khi:  this.frmInPhieuKK.ShowDialog(this);

**Comment by ongtrieuhau** [comment]
Lỗi do có dòng khám bệnh có khám, có mã ICD nhưng không ghi nhận manv. Hướng xử lý cập nhật lại giá trị này sẽ hết lỗi. @nghivanbi 
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/58720300/ddb80e61-5c5b-4056-b3cb-7b2187c8403a)

**Comment by minhduc2it** [comment]
@ongtrieuhau Em test trường hợp Null manv: Do đăng ký tái khám BANT vô maphong 26 
Xong chuyển phòng maphong 07 để khám
Khi đó maphong 26 bị Null manv

**Comment by ongtrieuhau** [comment]
Cái này nhờ @nghivanbi help mới được. Vì null thì đâu có maicd được. Xử lý tay cho bệnh viện in được trước đi.

**Comment by minhduc2it** [comment]
maicd có lúc đăng ký tái khám, lấy theo maicd của lần khám đầu
BV in tạm bên Printer được anh

**Comment by le-an-87** [comment]
Đối với BANT thanh toán ngày hiện tại em thấy có 2 trường hợp ghi nhận thiếu dữ liệu nhe anh @nghivanbi 
1. Khám bệnh phòng 02 và thực hiện chuyển phòng 29 và khám tiếp phòng 29. phần mềm sẽ ghi nhận thiếu trường maxt của phòng 29 nhe. 
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/ac98e546-3bb8-4183-bb7c-002fd59bb0f7)

2. Khi đăng ký tái khám bệnh án ngoại trú phần mềm sẽ ghi nhận có chẩn đoán nhưng không có manv và maxt -> người dùng thực hiện chuyển bệnh sang phòng 29 và khám tiếp.
   => dẫn đến phòng đầu tiên đăng ký tái khám thiếu dữ liệu manv và maxt
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/3fdb0dd9-c0d0-4de5-979b-612e7568816b)

**Comment by minhduc2it** [comment]
cập nhật Register mới ok
