### ISSUE TITLE
Lỗi - BBHC Bệnh nhân có nhiều BBHC khi chọn in thì chỉ in được BBHC đầu tiên

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#18]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamnong_bbhc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [``](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020015285` - _**MaKB**_: `2208005342` - _**NgayKCB**_: `12/08/2022` - _**MaPhong**_: `02` - _**MaDV**_: `03` - _**ThangKT**_: `08` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
BBHC: Bệnh nhân có lập 3 biên bản hội chẩn nhưng khi chọn in thì chỉ in được biên bản đầu tiên!

```
Hình ảnh đang chọn biển bản lập lúc 8h25 nhưng khi view và in ra thì ra biên bản lúc 8h30
![image](https://user-images.githubusercontent.com/96155021/184273242-a6b94fa8-46e3-4b27-9739-857bdc685820.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0812.1](http://www.fsend.vn/download/uRIPKRXzrgjPeKyYfef4qqxqwb4KXoYO)

**Comment by le-an-87** [comment]
đã fix!
