### ISSUE TITLE
Lỗi - Sai mẫu toa thuốc nghiện hướng thần

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#19]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_ungbuou_sinhthiet`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022032713` - _**MaKB**_: `2208003134` - _**MaBA**_: `MaBA` _**NgayKCB**_: `19/08/2022` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Sai thông tin đợt điều trị "từ ngày....đến ngày..." => "từ ngày....đến hết ngày..."

![ảnh](https://user-images.githubusercontent.com/97272332/185529600-f13eb2b1-0e83-4471-940c-be5a33fb80a0.png)
![ảnh](https://user-images.githubusercontent.com/97272332/185529622-69f29d46-45aa-4a80-a001-2e6dbb9d968f.png)
![ảnh](https://user-images.githubusercontent.com/97272332/185529635-119cd634-d161-4471-b992-ff16a16dcdb8.png)

**Comment by nghivanbi** [comment]
chính tả đó hả

**Comment by chauthanhtra** [comment]
dạ. thêm chữ ''hết'' vào là được 
cái para ngày tái khám này nó không hoạt động trên toa nghiện, hướng thần
![ảnh](https://user-images.githubusercontent.com/97272332/185530495-2d51b146-b84e-4c6f-94de-74ad3e7dc829.png)

**Comment by chauthanhtra** [comment]
không có chữ ''hết'' bệnh nhân đọc không hiểu đến lấy thuốc trước 1 ngày không hà anh

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0819.1](http://www.fsend.vn/download/5_nfKFVzPPREstwPqMP9scT-_lmkpgNz)

**Comment by chauthanhtra** [comment]
tải về phần mềm ngày 18/8 anh ơi
