### ISSUE TITLE
Lỗi - Chức năng cập nhật thời gian khám bệnh (BV Trà Cú

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#190]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tracu_ngaykb_11012023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_tracu_ngaykb_11012023`](https://gofile.me/78TQg/5FQ9MQIFU)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023012398` - _**MaKB**_: `2401003332` - _**NgayKCB**_: `08/01/2024` - _**MaPhong**_: `06` - _**MaDV**_: `KN` - _**ThangKT**_: `01` - _**NamKT**_: `2024`

- Bệnh nhân Test
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2401003333` - _**NgayKCB**_: `10/01/2024` - _**MaPhong**_: `03` - _**MaDV**_: `10` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
```
Khi sử dụng Prescription cấu hình cấp cứu để in phiếu BHYT bệnh nhân ngày củ chưa in
-> phần mềm hiển thị Form cập nhât thời gian khám bệnh lấy ngày khám là ngày hiện tại (không cho chỉnh ngày)
=> khi cập nhật xong Bệnh nhân không còn hiển thị lên phần mềm.

** Như trường hợp dưới đây bệnh nhân đăng ký ngày 10 thực hiện cập nhật ngày khám bệnh thành ngày 11
--> Prescription không hiển thị được bệnh nhân này nữa.
```
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/63b14cb8-e391-4b07-a118-f3249171b699)

**Comment by nghivanbi** [comment]
Này chức năng hỗ cho cc chỉnh giờ, sẽ khóa không cho chỉnh nếu khác ngày.

**Comment by nghivanbi** [comment]
[Prescription: v3.24.0111.2](https://drive.google.com/file/d/1pomi1gwd3dnRvFaSY9kvx_FzNAZwI_kU/view?usp=drive_link)

**Comment by le-an-87** [comment]
Đã fix!
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/7705da38-384d-4d7b-a0d8-e3e52d3df8f0)
