### ISSUE TITLE
Lỗi - Gọi bệnh ngoại trú, BANT xen kẽ ra đèn led báo lỗi và phần mềm không hiển thị tên bệnh nhân BANT ra màn hình TV

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#191]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/1/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmach_012024_goibenh_led_monitor_12012024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/kKSQeV2Eb)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `24001191 , 22025004` - _**MaKB**_: `2401010955 , 2401010956` - _**MaBA**_: ` , N24000140` _**NgayKCB**_: `15/1/2024` - _**MaPhong**_: `05` - _**MaDV**_: `10` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. Prescription báo lỗi khi gọi bệnh xen kẽ giữa ngoại trú và BANT
Ví dụ: gọi bệnh ngoại trú xong vào BANT bẫm gọi bênh sẽ báo lỗi và ngược lại. 

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/abadc257-3dc9-471d-866d-39763dbcf60f)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/45c61011-cff8-450a-af62-cc7e383913b8)

2. Phần mềm không hiển thị tên bệnh nhân BANT ra màn hình TV
Ví dụ: Bệnh nhân ngoại trú có STT = 1 đang khám trên màn hình TV thì bệnh nhân BANT có STT = 2 không hiển thị tên lên TV

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/45550312-e40a-4866-9dff-30497131182b)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/368fbd4c-3408-47e6-8185-c735154aaf54)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/028a8d93-a1e1-49c4-bf19-5fd913a87dc1)

**Comment by nghivanbi** [comment]
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/91751241/efd1cb98-d222-488a-b2cc-e8c1259bd334)

Báo sai nè nha

**Comment by chauthanhtra** [comment]
Mã đơn vị : 01
em gõ nhầm nha anh
