### ISSUE TITLE
Lỗi - Bệnh viện tuyến tỉnh khi nhập viện ghi nhận thông tin không đồng bộ với Treatment (trường bnnoitru.TUYEN, bnnoitru.TUYENXML) - BV Phụ Sản

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#195]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **92118**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_tonkho_tutruc_22122023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phusan_tonkho_tutruc_22122023`](https://gofile.me/78TQg/TAnC9pkUQ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000006` - _**MaKB**_: `2401000006` - _**MaBA**_: `000006` _**NgayKCB**_: `29/01/2024` - _**MaPhong**_: `35` - _**MaDV**_: `12` - _**ThangKT**_: `01` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh viện tuyến tỉnh khi nhập viện ghi nhận thông tin trường bnnoitru.tuyen và bnnoitru.tuyenxml không đồng bộ với module Treatment khi hiệu chỉnh thông tin.
cụ thể bệnh nhân có mã bệnh án 000006 ở trạng thái vào viện TRÁI TUYẾN ĐƯỢC HƯỞNG NHƯ CÙNG TUYẾN
Prescription: khi nhập viện ghi nhận 
+ bnnoitru.tuyen    = 1
+ bnnoitru.tuyenxml = 0
Treatment: sau khi hiệu chỉnh thông tin ghi nhận
+ bnnoitru.tuyen    = 0
+ bnnoitru.tuyenxml = 1
--> Treatment hiển thị thông tin giữa 2 bệnh nhân khác nhau nhưng cùng 1 trạng thái vào viện TRÁI TUYẾN ĐƯỢC HƯỞNG NHƯ CÙNG TUYẾN.

```
>Thông tin đăng ký ngoại trú
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/62710358-bf90-4fa0-83a6-0db49afd732a)

>Treatment ( trạng thái trái tuyến # bảng kê Trái tuyến được hưởng như cùng tuyến)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/edb15c1d-e67c-49c5-ae63-be15d5e27c1e)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/8c055ab0-1753-409b-ba66-83f10427dbaa)

>Bệnh nhân sau khi chỉnh thông tin treat
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/54ed5b72-437f-4324-a1e2-a275b7a20ed5)

>Ghi nhận dữ liệu:
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/020a53f0-adf0-458d-846a-434968270e2d)

**Comment by nghivanbi** [comment]
Mới nhập vô là dữ liệu vậy rồi hả @le-an-87 ?

**Comment by le-an-87** [comment]
Đúng rồi anh!

**Comment by nghivanbi** [comment]
<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h2>DHG.Hospital Prescription</h2>
 <h2>Ver: 3.24.0131.1</h2>
  
  
</div>

## Tập tin cài đặt (Setup Files)

<div align="center">
  
[![Tải về](https://img.shields.io/badge/Tải%20file%20cài%20đặt-Google-blue?logo=googledrive)](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3) 
</div>

## Nội dung cập nhật

<div align="center">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprescription/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by le-an-87** [comment]
Đã Fix! Bệnh nhâp viện thông tin đã khớp với Treatment.
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/7f19cd4e-02a6-47e6-9a89-6d88b271536c)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/5d91d2f2-fe81-432c-9bf6-2f8cea59a37a)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/f29ea307-1b9f-4173-bd1b-737e47378b24)
