### ISSUE TITLE
Lỗi - Lỗi thời gian công khám trùng với thời gian nhập viện.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#197]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/02/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_full_t12`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000003` - _**MaKB**_: `2401000006` - _**MaBA**_: `N2024000002` _**NgayKCB**_: `19/02/2024` - _**MaPhong**_: `24` - _**MaDV**_: `10` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện BANT theo đợt BV đang sử dụng tham số bant.giovv=0(Lấy giờ khám bệnh làm giờ nhập viện) => dẫn đến tình trạng thời gian phát sinh công khám bằng với thời gian nhập viện => cổng tiếp nhận báo lỗi.
Đề nghị có hướng giải quyết.

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/6d06090d-5da9-47ad-bf48-ab498b367a8e)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/10ef2757-50e9-4495-ba22-2d8b001673da)

**Comment by nghivanbi** [comment]
<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h2>DHG.Hospital Prescription</h2>
  <h2>Ver: 3.24.0219.1</h2>
  
  
</div>

## Tập tin cài đặt (Setup Files)

<div align="center">
  
[![Tải về](https://img.shields.io/badge/Tải%20file%20cài%20đặt-Google-blue?logo=googledrive)](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3) 
  
</div>

## Nội dung cập nhật

<div align="center">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprescription/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by lqbinh1987** [comment]
Đã hỗ trợ ok.
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/842bf29b-0fc0-47f0-ba18-d0f0bec45a97)
