### ISSUE TITLE
Lỗi - khi lập phiếu nghỉ ốm tại Register bị double chẩn đoán

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#20]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) ``
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi lập phiếu nghĩ ốm chẩn đoán bị lập lại

```
@minhduc2it em kiểm tra và test lại trường hợp này xem có đúng không nhe!
![1e74e3d7c2247ea31076553293e20fc10bbd69ff48b0fdee2a71baf871a7e6c4](https://user-images.githubusercontent.com/96155021/185530678-5ab44785-86ce-4a2d-9e85-6bc417f86866.png)

**Comment by minhduc2it** [comment]
Phiếu nghỉ ốm bệnh BA ngoại trú double chẩn đoán khi lập trên Register
Data: duc_medicmd2

![image](https://user-images.githubusercontent.com/98437757/185552322-7191f6e2-52a8-47b1-b1d0-6bbcfeade037.png)

![image](https://user-images.githubusercontent.com/98437757/185552461-2e0cd47d-a00b-4c22-8e57-5ede3509f88f.png)

**Comment by le-an-87** [comment]
vậy là Register chổ đó không có chức năng lọc trùng!
@minhduc2it em test 1 bệnh khác thử xem lập được như vậy không?
kiểm tra Prescription luôn và bệnh ngoại trú luôn xem có bị không?

**Comment by minhduc2it** [comment]
Prescription luôn và bệnh án ngoại trú: Lập phiếu Nghỉ ốm không bị double chẩn đoán
Register có trường hợp: khám ngoại trú Prescription > chẩn đoán A > chuyển phòng > Chẩn đoán B > Lập Phiếu nghỉ ốm trên Register > Chẩn đoán sẽ load: chẩn đoán A, Chẩn đoán B

**Comment by le-an-87** [comment]
vậy cả Register và Prescription đều không có lỗi hả @minhduc2it

**Comment by minhduc2it** [comment]
Prescription không lỗi anh @le-an-87

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.22.0823.1](http://www.fsend.vn/download/D9_zeb4uK6JR23wNNeGkuKR1NhWYh0ZM)
