### ISSUE TITLE
Lỗi - BANT lịch sử bệnh load thiếu dữ liệu khám bệnh

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprescription#204]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/02/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_dongtay_lichsu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/ewrXZt70E

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022002186` - _**MaKB**_: `2306027423` - _**MaBA**_: `N2023002761` _**NgayKCB**_: `08/07/2023` - _**MaPhong**_: `H27` - _**MaDV**_: `K17` - _**ThangKT**_: `07` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
mo_ta_loi

```
BANT khi xem lịch sử bệnh load thiếu dữ liệu
VD: ngày 8/7 BN có Chỉ định CLS và Cấp toa - Lịch sử bệnh không có
Trên dữ liệu bảng chidinhcls có ngày 8/7/2023

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/80816149-7b4c-43b8-a5c4-e639cf92d296)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/dd3ff765-234d-46cf-ba71-92652abfb542)

**Comment by nghivanbi** [comment]
<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h2>DHG.Hospital Prescription</h2>
 <h2>Ver:3.24.0309.2</h2>
  
  
</div>

## Tập tin cài đặt (Setup Files)

<div align="center">
  
[![Tải về](https://img.shields.io/badge/Tải%20file%20cài%20đặt-Google-blue?logo=googledrive)](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3) 
  
</div>

## Nội dung cập nhật

<div align="center">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprescription/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by minhduc2it** [comment]
Bản mới xem lịch sử bệnh vẫn chưa load dữ liệu các ngày trong đó có ngày 8/7/2023

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/b478d2d4-0d06-4326-ab7f-745f2bfdc086)

**Comment by nghivanbi** [comment]
Chọn bệnh án chỗ Combo
