### ISSUE TITLE
Lỗi - cấp mã đơn thuốc gửi dược quốc gia bị trùng với năm cũ

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#211]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87159`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM QUÂN DÂN Y GIỒNG GĂNG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbgionggang_trung_madonthuoc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000057` - _**MaKB**_: `2401000328` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

qui cách cấp mã đơn thuốc dược quốc gia bị trùng với năm cũ

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/c6fae736-e35d-473c-aa6f-43c6b7a8b25a)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/2ac38679-d2dc-40a3-a500-2b1cd80ccfdc)

**Comment by nqhoa1005** [comment]
khi cấp quyển mới bị trùng Ký hiệu vẫn bị trùng mã đơn thuốc với năm cũ

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/d66bb267-2668-4f0d-84b1-e8a2ec08c8b0)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/237ff2f8-e5a4-4c04-abbf-519d1b454c7f)

**Comment by nghivanbi** [comment]
<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h2>DHG.Hospital Prescription</h2>
  <h2>Ver: 3.24.0312.1</h2>
  
</div>

## Tập tin cài đặt (Setup Files)

<div align="center">
  
[![Tải về](https://img.shields.io/badge/Tải%20file%20cài%20đặt-Google-blue?logo=googledrive)](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3) 
  
</div>

## Nội dung cập nhật

<div align="center">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprescription/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by nqhoa1005** [comment]
đã cập nhật tạo quyển mới với thông tin năm và ký hiệu để phân biệt
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/efec3828-22f4-4b7d-87de-9aa4e828a49f)
