### ISSUE TITLE
Lỗi - Chỉ định CLS có cấu hình % miễn giảm báo lỗi

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#213]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51219`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PKĐK Minh Quang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_st_nhanbenh_makhuvuc_06022024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/K6yH2cjX8)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000003 , 2024000004` - _**MaKB**_: `2402005131 , 2402005132` - _**MaBA**_: `MaBA` _**NgayKCB**_: `28/02/2024` - _**MaPhong**_: `011` - _**MaDV**_: `02` - _**ThangKT**_: `02` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DI33  (BHYT), DO23  (thu phí)` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

CLS có cấu hình có % miễn giảm trong danh mục:
- Bệnh nhân BHYT khi chỉ định thì không có % miễn giảm và tiền miễn giảm (CLS thu phí có miễn giảm)
- Bệnh nhân thu phí thì phần mềm báo lỗi và không tính miễn giảm (CLS thu phí và thanh BHYT có cấu hình % miễn giảm)

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/b33f4af1-4608-4813-b374-3c886e203bef)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/42020541-2917-47d3-9767-dc604889bf1c)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/fc3a14fa-4619-44e6-939b-fde751b665eb)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/f4db15b0-7b60-4be9-9dba-da7a6d7b7ff4)

**Comment by chauthanhtra** [comment]
Data: tra_phusan_130
mã BN: 2024035270
mã KB: 2405000196
khoa: 11
phòng: 40
ngày: 30/07

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0730.7 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407307-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407307-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407307-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi chỉ định cận lâm sàng có miễn giảm (bệnh nhân thu phí).

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/213

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40nghivanbi-informational?logo=github)](https://github.com/nghivanbi) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nghivanbi** [comment]
![image](https://github.com/user-attachments/assets/322e4c98-fb6a-4e1d-b6c5-8e756c39827c)
