### ISSUE TITLE
Lỗi - Không cập nhật chẩn đoán cho toa thuốc khi chỉnh diễn biến, chỉnh chẩn đoán (toathuoc.chandoan = 1)

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#227]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmach_ct_lechtien_02022024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Ia3RdhF6H)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `24000011 , 24000004` - _**MaKB**_: `2402001566 , 2402001557` - _**MaBA**_: `    , N2024000002` _**NgayKCB**_: `06/03/2024` - _**MaPhong**_: `21` - _**MaDV**_: `01` - _**ThangKT**_: `02` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Tham số toathuoc.chandoan = 1 : cập nhật các toa chưa in
Phần mềm không cập nhật chẩn đoán cho toa thuốc đối với bệnh nhân ngoại trú và BANT thanh toán theo đợt. 
Hiện tại chỉ cập nhật chẩn đoán toa thuốc cho bệnh nhân BANT thanh toán theo ngày.

- Bệnh nhân ngoại trú

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/a209ad9f-fd0f-4d5a-8b3d-ef9cb33d9f27)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/b75162c1-ae8f-48f0-ab35-25d1b5e24ef7)

- Bệnh nhân BANT thanh toán theo đợt

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/ee837920-85a6-4f5e-ad8c-fe9037b645fd)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/1100383e-49bc-49c8-9cc7-ab3488310ca8)

**Comment by nghivanbi** [comment]
<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h2>DHG.Hospital Prescription</h2>
  <h2>Ver:3.24.0308.1</h2>
  
  
</div>

## Tập tin cài đặt (Setup Files)

<div align="center">
  
[![Tải về](https://img.shields.io/badge/Tải%20file%20cài%20đặt-Google-blue?logo=googledrive)](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3) 
  
</div>

## Nội dung cập nhật

<div align="center">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprescription/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by chauthanhtra** [comment]
Phần mềm mới vẫn chưa được nha anh @nghivanbi 

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/eb21e7d5-9c98-421b-9a31-0f1e53cc5d78)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/26355f6b-61d6-4aaf-bf4e-cb7a3572a56c)

**Comment by nghivanbi** [comment]
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/91751241/2850700b-bffb-496b-bcc2-f039a89a72c2)
<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h2>DHG.Hospital Prescription</h2>
  <h2>Ver:3.24.0308.2</h2>
  
  
</div>

## Tập tin cài đặt (Setup Files)

<div align="center">
  
[![Tải về](https://img.shields.io/badge/Tải%20file%20cài%20đặt-Google-blue?logo=googledrive)](https://drive.google.com/drive/folders/1RtYOc1Mt7PauLAZhuGwL2Aba5bhpeyh3) 
  
</div>

## Nội dung cập nhật

<div align="center">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprescription/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by chauthanhtra** [comment]
BANT theo ngày và ngoại trú cập nhật được rồi 

Còn BANT theo đợt chưa cập nhật được

**Comment by chauthanhtra** [comment]
Phần mềm đã fix lỗi không cập nhật chẩn đoán toa thuốc khi chỉnh chẩn đoán (toathuoc.chandoan = 1)

Kiểm tra bệnh nhân mới chưa phát hiện lỗi. Các chức năng Thu phí, bảng kê 6556, XML xuất bình thường
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/ca0ddbae-50c2-43ba-85b9-48dcd1d87d0e)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/d2e2fb8b-de76-4fc1-b2eb-c59d8ef23913)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/621802ea-51c2-4192-8eb6-90de78009c71)
