### ISSUE TITLE
Lỗi - Bảng kê theo đối tượng tủ trực thống kê thiếu đối tượng KSK và khác 

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#229]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/3/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Quảng Ngãi**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_quangngai_baocaosudungthuoctutruc_01_022024_19032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/6mMYNHoxf)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024003295` - _**MaKB**_: `2402002175` - _**MaBA**_: `MaBA` _**NgayKCB**_: `6/2/2024` - _**MaPhong**_: `A1-09` - _**MaDV**_: `02` - _**ThangKT**_: `02` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `02` - _**TuTruc**_: `TNG` - _**MaHH**_: `BO56` - _**SoHD**_: `B12.00011/02` - _**NgayHD**_: `6/2/2024` - _**ThangKT**_: `02` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Quản lý tủ trực trên Prescription -> Thống kê theo đối tượng hiện tại chỉ hiển thị các đối tượng BHYT, Trẻ em, Thu phí, Miễn phí -> thiếu các đối tượng khác như Khám sức khỏe và Khác
- Khi in ra thì có thêm đối tượng khác
-> Cột tổng cộng tính số lượng đủ nhưng cộng chi tiết theo từng đối tượng thì thiếu  số lượng so với tổng cộng do không hiển thị các đối tượng KSK và khác
=> Thêm các đối tượng KSK và khác vào form và trang in

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/9f2ea2fd-d9a2-4b66-9d5c-55bb43e12390)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/a417e446-0f84-464f-9efc-9e08b75e6e25)

**Comment by gh-dh-bot-02** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại📣

**Comment by gh-dh-bot-02** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại📣
