### ISSUE TITLE
Lỗi - Sổ khám bệnh trường hợp bệnh ngoại trú thanh toán hàng ngày bị sai số lần khám bệnh

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#23]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_cairang_31082022`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018019370` - _**MaKB**_: `2207000032` - _**MaBA**_: `N2019000908` _**NgayKCB**_: `01/07/2022` - _**MaPhong**_: `30` - _**MaDV**_: `06` - _**ThangKT**_: `07` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh án ngoại trú thanh toán hàng ngày:
1 - Trong ngày có 3 diễn biến nhưng lên sổ khám bệnh thì hiển thị đến 6 dòng!
2 - Khi đăng ký tái khám bệnh án ngoại trú ở phòng 29 nhưng không khám mà thực hiện chuyển qua phòng 05 để khám
-> thì Prescription sẽ xin ra 1 dòng diễn biến của phòng 29 nhưng không có mã bs và phân loại bệnh dẫn đến sai ở sổ khám bệnh!

```
bệnh nhân có 3 diễn biến ngày 01/7/2022
![image](https://user-images.githubusercontent.com/96155021/187633901-8ecb65b5-5a52-4162-8bf5-9e0784b9b1ad.png)
sổ khám bệnh sinh ra 6 dòng dữ liệu
![image](https://user-images.githubusercontent.com/96155021/187635216-5ae965aa-fb06-409a-b0a7-591b97f383f1.png)

Đăng ký tái khám phòng 29 nhưng được chuyển qua phòng 05 khám thì diễn biến phòng 29 không có mã BS
![image](https://user-images.githubusercontent.com/96155021/187635558-c4f3547b-6d32-422b-9c7b-6abbe0efa59e.png)

**Comment by le-an-87** [comment]
anh kiểm tra lỗi này giùm em nhe!

**Comment by nghivanbi** [comment]
Cập nhật:
Register: [v3.22.0907.1](http://www.fsend.vn/download/udFJNV4PM-JB7SDhBzCJy_aa_llXyXe2)

**Comment by le-an-87** [comment]
Chổ Register kiểm tra lại Ok rồi đó anh @nghivanbi ơi! anh cập nhật lại Prescription giùm em nhe!
anh @vinh-dh ơi anh cập nhật lại sổ khám bệnh ở Reports giùm em luôn nhe anh!

**Comment by le-an-87** [comment]
đã cập nhật!
