### ISSUE TITLE
Lỗi - TREO PRE KHI CHO 2 LOẠI THUỐC VÀO TOA

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#230]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77114`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA BÌNH AN**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_binhan1`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024004065` - _**MaKB**_: `2403002856` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `004` - _**MaDV**_: `004` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `14` - _**MaHH**_: `CE50` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi ra toa cho 2 mặt hàng CE50 và TE82 thì treo không thông báo lỗi
Em đã kiểm tra dữ liệu tồn kho và thông tin trong danh mục thuốc không có vấn đề, vẫn chưa xác định được nguyên nhân
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/c26fdb52-844e-4796-934c-f0d09eb1498f)

**Comment by gh-dh-bot-00** [comment]
<details> <summary>   ℹ️<code>2024-19-03 18:21:41</code> <code>@nqhoa1005</code><code>projects_v2_item.created</code>   <code>-NtLRWlFEwt738BMfelt</code> </summary> <code>[bot]</code><code>1.24.0319.1539@gh-dh-hos-more-alien-weekly-ubuntu-latest-gh-svr-listen-yml-1710846237146</code><code>[<a href='https://github.com/dh-hos/more-alien-weekly-ubuntu-latest/actions/runs/8341865168'>webhook-logs</a>]</code></details>

**Comment by nghivanbi** [comment]
Đã kiểm: lỗi do cấu hình chỉ đinh và chống chỉ định thuốc sai (hết danh mục) nên kiểm lâu --> treo

**Comment by nqhoa1005** [comment]
Đã hoạt động bình thường khi reset ICD chống chỉ định
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/ba2f2c73-8838-4640-a304-96a330916f3e)
