### ISSUE TITLE
Lỗi - Tham số yc.chandoan không cập nhật vào cột chidinhcls.mayhct và chidinhcls.tenyhct

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprescription#231]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) **74206**
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Medic Miền Đông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_medicmd_yhct`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`]  https://gofile.me/78TQg/rlYP9Bdak

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023004120` - _**MaKB**_: `2403011319` - _**MaBA**_: `MaBA` _**NgayKCB**_: `19/03/2024` - _**MaPhong**_: `11` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Chẩn đoán YHCT:
Áp dụng Tham số yc.chandoan 
Khi chỉnh chấn đoán YHCT không cập nhật vào cột chidinhcls.mayhct và chidinhcls.tenyhct

Hiện tại dữ liệu đang sử dụng tham số yc.chandoan =2. Các trường hợp tham số yc.chandoan =1 và 3 vẫn không cập nhật chẩn đoán YHCT

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/4b17640e-a595-4d42-b195-b9b7856d4b2d)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/eb0b68dd-8dca-4cf2-8e8b-0f129a62577f)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại📣

**Comment by nghivanbi** [comment]
Trước khi chỉnh chẩn đoán


![Image](https://github.com/dh-hos/dhg.hospitalprescription/assets/91751241/4f8b90bd-09cd-4bc8-86fb-86502c01d920)

Sau khi chỉnh chẩn đoán


![Image](https://github.com/dh-hos/dhg.hospitalprescription/assets/91751241/50c80272-df5b-44d3-b2a8-b7d1e09e7790)



![Image](https://github.com/dh-hos/dhg.hospitalprescription/assets/91751241/2c6786fc-a94d-4721-91a7-d7d8a7ae6d32)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0625.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406251-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406251-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406251-NasDHSolutions.json)

## Nội dung thay đổi

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/231

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/246

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40nghivanbi-informational?logo=github)](https://github.com/nghivanbi) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
Kiểm tra lỗi đã fix ok 
Trước khi chỉnh chẩn đoán
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/9598df54-c8f0-4aed-95b9-2521cc39949e)

Sau khi chỉnh chẩn đoán
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/9a44a5d0-cff0-4fd5-8335-57a5573f0b60)

Kiểm tra các chức năng cơ bản: Đăng ký, khám bệnh, in 01 chưa ghi nhận bất thường
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/b5c33d52-a063-46d3-a226-f1110a6a44a7)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/ef878f9d-cb1a-4b07-b5ac-35b200a97bd5)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/e7563726-2d75-4c29-8e58-75a3788accb3)
