### ISSUE TITLE
Lỗi - Không in được bảng kê chi phí đối tượng thu phí

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#233]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_prescription_inbangke_25032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Evuhebpwd)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023092972` - _**MaKB**_: `2403011550` - _**MaBA**_: `MaBA` _**NgayKCB**_: `18/03/2024` - _**MaPhong**_: `20` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Phần mềm Prescription không in được bảng kê chi phí đối tượng thu phí

- Phần mềm Prescription cũ khi in bảng kê phần mềm báo không có chi phí hoặc CLS và thông báo lỗi (nguyên nhân do bệnh nhân đăng ký khám có chỉ định CLS tự do nhưng không khám mà chuyển sang phòng khác khám và in bảng kê)

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/f121ff81-ae45-409a-aca6-d1975f66f266)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/4f23ed92-ef88-46a3-9943-47619c6a6c3e)

- Phần mềm Prescription mới PrescriptionSetup20240318V1 thì phần mêm không báo lỗi nhưng luôn hiện form xem bảng kê mẫu bảng kê BHYT (thiếu mã khoa, tên khoa), không in được mẫu bảng kê chi phí đối tượng thu phí

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/c93e89f8-f3ff-4442-adac-9a175319ffc1)

- Mẫu bảng kê chi phí đối tượng thu phí cũ

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/23b486c5-23f7-4fb5-9c22-8b5c6ed29d66)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/233)

**Comment by nghivanbi** [comment]
Hiện tại Pre đã chuyển sang mẫu bảng kê thu phí như BHYT, xác nhận lại với đơn vị vậy ok không nhé @chauthanhtra

**Comment by chauthanhtra** [comment]
BV Phụ Sản không chịu sử dụng mẫu bảng kê thu phí như BHYT nha anh @nghivanbi 
Kế toán BV không chịu sử dụng mẫu mới, mẫu cũ đơn giản, dể nhìn không rườm rà

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/2f6b3449-511b-49dc-88b9-30064a091b99)

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/5b75f0fe-16d2-4e71-82eb-6597b1577985)

**Comment by nghivanbi** [comment]
ok để làm riêng cho nó

**Comment by chauthanhtra** [comment]
Alo anh @nghivanbi 
Anh có mã lại mẫu bảng kê thu phí cũ cho BV Phụ Sản chưa vậy anh?

**Comment by nghivanbi** [comment]
Để anh lập yêu cầu thực hiện cái này cho thiết kế để bảo đảm tính tổng thể cho các đơn vị.

**Comment by chauthanhtra** [comment]
BV báo lỗi Em test phần mềm mới thì thấy
- Tên CLS dài thì bị mất không tự xuống hàng được -> thiết kế cho tự xuống dòng luôn nha anh
![ảnh](https://github.com/user-attachments/assets/229724c7-ceff-4bab-be01-71ac20a06781)

**Comment by chauthanhtra** [comment]
> BV báo lỗi Em test phần mềm mới thì thấy
> 
>     * Tên CLS dài thì bị mất không tự xuống hàng được -> thiết kế cho tự xuống dòng luôn nha anh
>       ![ảnh](https://private-user-images.githubusercontent.com/97272332/355280298-229724c7-ceff-4bab-be01-71ac20a06781.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0OTk1NTMsIm5iZiI6MTcyNTQ5OTI1MywicGF0aCI6Ii85NzI3MjMzMi8zNTUyODAyOTgtMjI5NzI0YzctY2VmZi00YmFiLWJlMDEtNzFhYzIwYTA2NzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDAxMjA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmN2FmMjE2YTY4MmMyN2JiYzc1YmNiYTA1YTY0Y2RmZmRjN2FjZTQzY2FmNGMwNDdhM2RhM2IwM2FjOTdmMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r8HjX0g5Xf9smcOt8bPTWAtRcfWVnuo7rX18iJnAels)

Alo anh @nghivanbi 
Fix lại lỗi này giúp em trước nha anh .  BV yêu cầu

**Comment by chauthanhtra** [comment]
hủy git
