### ISSUE TITLE
Lỗi - test yêu cầu ra toa Vật tư kèm theo được chọn tủ trực Vật tư

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#234]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Thốt Nốt**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thotnot_toatt_27032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_thotnot_toatt_27032024`](https://gofile.me/78TQg/o34bsM2J5)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024012043` - _**MaKB**_: `2403015711` - _**NgayKCB**_: `27/03/2024` - _**MaPhong**_: `20` - _**MaDV**_: `12` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)
Git yêu cầu
[ Yêu cầu - Mở chức năng ra toa nhiều tủ trực dh-hos/To_Ho_Tro#31](https://github.com/dh-hos/To_Ho_Tro/issues/31)
```
Đã bổ sung chức năng cho phép chọn tủ trực VTYT khi ra toa Vật tư kèm theo.
còn phát sinh vấn đề sau:
1. Khi ra toa tủ trực ghi nhận trường loaitoatt chưa đúng. table chungtu và pshdxn (hiện tại trường này chỉ hỗ trợ module Treatment)
2. bảng kê in tại Prescription không có mã icd chính

```
1.
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/fb0c73aa-7a29-46f8-9de2-f17437ba0c90)
2.
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/b0917702-9808-49ed-a089-dfccc5b9c78b)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/4c55ce9d-b20d-4489-9cb5-8df1a275f039)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/234)

**Comment by le-an-87** [comment]
Đã fix lỗi tại git https://github.com/dh-hos/dhg.hospitalprescription/issues/251
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/ce02d6b8-afbc-4aeb-bd6e-31eb3bb72c9d)
