### ISSUE TITLE
Lỗi - chức năng chụp hình bệnh nhân báo lỗi (BV Phụ Sản)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#235]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_chitiettheodichvu_06032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_phusan_chitiettheodichvu_06032024`](https://gofile.me/78TQg/zgOV5vFw7)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Chức năng chụp hình khi nhận bệnh`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Lỗi chức năng chụp hình khi nhận bênh.

```
khi vào chức năng chụp hình Prescription báo lỗi
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/ffeb5ea8-ee97-4606-80ad-dbc5ae31b21f)
Không lấy được tín hiệu vedcam
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/1ab776fc-70e7-40d3-bebc-34db74eb2a0a)
Register vẫn chụp hình được
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/a42db419-f6cc-4263-968c-5cd30ed4a8c8)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/235)
<details> <summary>   ℹ️<code>2024-29-03 09:31:47</code> <code>@le-an-87</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-Nu728-oPiZlA1smO6Om'>-Nu728-oPiZlA1smO6Om</a>]</code></code><code>GH</code> </summary> <code>[bot]</code><code>1.24.0321.1600@gh-dh-hos-more-alien-weekly-ubuntu-latest-gh-svr-listen-yml-1711678343244</code><code>[<a href='https://github.com/dh-hos/more-alien-weekly-ubuntu-latest/actions/runs/8476281265'>webhook-logs</a>]</code></details>

**Comment by nghivanbi** [comment]
Kiểm lại lỗi này trên bảng Prescription mới 0919.3, thực hiện  được:
![](https://i.imgur.com/oEBbcjb.png)
@le-an-87 nhờ kiểm lại.

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ KIỂM TRA SẢN PHẨM**
***
> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/a4813079-105a-45ff-9bb1-03ece6d80f2a)
![ảnh](https://github.com/user-attachments/assets/a2ebc2c1-f768-47e6-b9c7-e610cbed3ba0)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
