### ISSUE TITLE
Lỗi - HIỂN THỊ THIẾU THÔNG TIN TRÊN BẢNG KÊ 6556

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#236]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87163`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV TÂM THẦN ĐỒNG THÁP**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_bvttdt2024000246`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000803` - _**MaKB**_: `2404000002` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `KB` - _**MaDV**_: `10` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bản cập nhật hỗ trợ in bảng kê 6556 cho đối tượng thu phí thiếu thông tin tên và mã khoa không hiển thị

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/64dab02e-1da1-41ad-916a-c094809b125a)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/18f83119-35e1-408a-9ee3-05f5f7175f20)

và thông tin tài khoản in phiếu và tài khoản lập toa em đã kéo vào và bật tham số 6556 nhưng cũng không hiển thị.

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/b94990b2-638e-45db-a6a6-f2575ea24055)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/8b459756-0ca0-473e-b938-c39a4f92f34c)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/5810fb07-8ceb-4c5f-880f-84c53167e093)

check dùm em gấp các thông tin này để đơn vị in nộp cho giám định BHXH

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/236)

**Comment by lqbinh1987** [comment]
coi này dùm em a @nghivanbi , hiều BV bị, Trà nó cũng báo tương tự #238

**Comment by lqbinh1987** [comment]
Anh @nghivanbi coi dùm em, BV đang bị thanh tra.

**Comment by nqhoa1005** [comment]
anh @nghivanbi coi sớm dùm em, Phổi lại hối làm để cung cấp cho thanh tra

**Comment by nghivanbi** [comment]
@ongtrieuhau kiểm lỗi này dùm anh nhé, hiện đang sử dụng DLL cú pháp:
private OTH.XForms.HosPrinter.BKChiPhiKCB6556 objBKChiPhiKCB6556;
objBKChiPhiKCB6556 = new OTH.XForms.HosPrinter.BKChiPhiKCB6556(this.htBNKhamBenh["mabn"] + "", this.htBNKhamBenh["makb"] + "", "", "",
                                OTH.Entity.Enum.BHXH.v_LoaiHoSoKCB.NGOAI_TRU,
                                OTH.Entity.Enum.BHXH.v_LoadBenhNhan.TATCA_CHIPHI,
                                OTH.Entity.Enum.BHXH.v_LoadDataFor.Inphieu01ByPrescription,
                                "");
                        objBKChiPhiKCB6556.PrintDia(OTH.Entity.HosBHXH.EBKChiPhiKCB.v_PrintChiphi.TatCa);

**Comment by nqhoa1005** [comment]
anh @ongtrieuhau coi dùm em chổ này, BV hối quá

**Comment by ongtrieuhau-dh** [comment]
ok, để check nhé

**Comment by lqbinh1987** [comment]
alo anh @ongtrieuhau ơii

**Comment by ongtrieuhau-dh** [comment]
ok

**Comment by ongtrieuhau-dh** [comment]
Check lại database và link dữ liệu nhé @lqbinh1987 , hổng thấy tên này hoa_bvttdt2024000246

**Comment by lqbinh1987** [comment]
Ok anh, Hòa đang chec lại

**Comment by nqhoa1005** [comment]
em đã restore lại
thông tin khám
madv : 01
maphong : 01
ngaykcb : 22/05/2024

**Comment by nqhoa1005** [comment]
em vừa nhận khám lại để dễ mở, anh @ongtrieuhau check dùm em

**Comment by ongtrieuhau-dh** [comment]
OK

**Comment by ongtrieuhau-dh** [comment]
Thống pull libraries về để fix lỗi này nhé 
![](https://i.imgur.com/r5Vnh2n.png)

Lưu ý: **Phải truyền tài khoản đăng nhập vào chức năng này khi gọi hàm**

![](https://i.imgur.com/WRBtGIU.png)

**Comment by ongtrieuhau-dh** [comment]
@nghivanbi, chỉ hết mấy chỗ nào in cái phiếu này cho @lequocthong29  cái a

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0522.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32405220-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32405220-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32405220-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi hiển thị thiếu thông tin trên bảng kê 6556

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/236

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
Thông tin đã được bổ sung
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/6d8b0b48-640f-4812-a652-f6f1f940a8cd)
