### ISSUE TITLE
Lỗi - Phát sinh lỗi cảnh báo công khám khi chỉnh/xóa phiếu nhập viện.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#237]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_full_t12`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000023` - _**MaKB**_: `2401000034` - _**MaBA**_: `MaBA` _**NgayKCB**_: `02/04/2024` - _**MaPhong**_: `16` - _**MaDV**_: `10` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Có 2 trường hợp lỗi:

1. Đã lập phiếu nhập viện, công khám đã chuyển vào nội trú, sau đó nhấn nút Chỉnh phiếu nhập viện, sau đó Lưu thì phần mềm vẫn cảnh báo không có công khám, do công khám không còn ở ngoại trú mà đã chuyển vào nội trú.
2. Đã lập phiếu nhập viện, công khám đã chuyển vào nội trú, sau đó Xóa phiếu nhập viện nhưng công khám không được tự động chuyển ra ngoại trú, công khám đó trong bảng chidinhcls.noitru vẫn =1 và chidinhcls.maba vẫn đang còn lưu số BA đã xử lý nhập viện trước đó như hình dưới, cho nên khi lập phiếu nhập viện lại thì phần mềm lại báo **Không có công khám**, trường hợp này cũng dẫn đến tình trạng lỗi ở đây #221.

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/66f349f5-5132-404e-9b69-15c08163bdcc)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/237)
<details> <summary>   ℹ️<code>2024-02-04 09:33:23</code> <code>@lqbinh1987</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-NuRdrnINcl9BKCESLf7'>-NuRdrnINcl9BKCESLf7</a>]</code></code><code>GH</code> </summary> <code>[bot]</code><code>1.24.0321.1600@gh-dh-hos-more-alien-weekly-ubuntu-latest-gh-svr-listen-yml-1712024154651</code><code>[<a href='https://github.com/dh-hos/more-alien-weekly-ubuntu-latest/actions/runs/8516466565'>webhook-logs</a>]</code></details>

**Comment by nghivanbi** [comment]
<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h2>DHG.Hospital Prescription</h2>
 <h2>Ver:3.24.0411.1</h2>
  
  
</div>

## Tập tin cài đặt (Setup Files)

<div align="center">
  
[![Build Status](https://img.shields.io/badge/Tải%20file%20cài%20đặt-NAS-blue?logo=googledrive)](https://gofile.me/78TQg/14P0fy1VH) 
  
</div>

## Nội dung cập nhật

<div align="center">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprescription/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by nghivanbi** [comment]
1. Chỉnh không kiểm tra công khám.
2. Fix: xóa nhập viện trả công khám về ngoại trú.

**Comment by lqbinh1987** [comment]
Đã hỗ trợ.
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/80ae4ced-9460-435c-a93e-0e026ec4b75b)
