### ISSUE TITLE
Lỗi - Chức năng in phiếu BHYT trên Prescription 02/04/2024

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#238]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **2/4/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_so10_02_032024_ngayylenhsauketthuc_19032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/1pn8iNV61)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024013258` - _**MaKB**_: `2404000001` - _**MaBA**_: `MaBA` _**NgayKCB**_: `2/4/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Test in phiếu BHYT trên Prescription mới 2/4/2024

- Bảng kê thiếu thông tin khoa, ngày kết thúc khám, icd chính, chẩn đoán chính, ICD chính và chẩn đoán chính hiện tại đang gom chung với ICD và chẩn đoán phụ.
- Dữ liệu psdangky, chidinhcls, chungtu, pshdxn không ghi nhận bệnh nhân đã in phiếu và thông tin kết thúc khám như tháng năm quyết toán, icd chính thiếu (bị gọp chung với ICD phụ), ngày in phiếu, trạng thái  đã in,...
- Có cấu hình trừ kho trực tiếp nhưng không trừ kho. không khóa chỉnh chẩn đoán
- Cấu hình tách chi phí BHYT và ngoài BHYT (DV) ra 2 bảng in nhưng không tách

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/4ae373cc-e697-4f47-9c02-2a537b8c0af1)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/9b288eb6-6f73-45fd-a595-770faf9d6eda)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/35805c16-863e-4620-9287-37d030ae0a61)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/40a670f0-2cfc-4c99-a4c1-e645efc20e47)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/238)
<details> <summary>   ℹ️<code>2024-02-04 16:52:20</code> <code>@chauthanhtra</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-NuTDKhgUYAQyJJuRI69'>-NuTDKhgUYAQyJJuRI69</a>]</code></code><code>AZ</code> </summary> <code>[bot]</code><code>1.24.0321.1600@az-o-adv-more-alien-weekly-ubuntu-latest-definitionId28-1712051513391</code><code>[<a href='https://dev.azure.com/o-adv/more-alien-weekly-ubuntu-latest/_build/results?buildId=6301&view=logs'>webhook-logs</a>]</code></details>

**Comment by nghivanbi** [comment]
@ongtrieuhau  xem lại chỗ DLL nhé.

**Comment by ongtrieuhau-dh** [comment]
Cái này chờ @nghivanbi chỉnh lại như trước khi in phiếu 01 cho thu phí nhé

**Comment by nghivanbi** [comment]
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/91751241/24384741-7db4-4351-8cef-834fbc94a96a)

**Comment by chauthanhtra** [comment]
- Bảng kê sai trạng thái khám bệnh: cùng tuyến, trái tuyến, thông tuyến

  - Bệnh nhân trái tuyến được hưởng cùng tuyến khi in bảng kê thể hiện bệnh nhân đúng tuyến

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/0af776c4-a79e-4c2e-a3ea-f2228b23d205)

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/614857b0-997e-4bdc-8480-65bbac289bd2)

  - Bệnh nhân thông tuyến in bảng kê thể hiện bệnh nhân đúng tuyến

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/0a1e57b1-5c41-4a67-bc7e-047b700e5bbd)

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/7414f28f-df68-49c1-a623-00c42e8c9ec4)

- Khi bệnh nhân khám 2 khoa, in phiếu ở khoa thứ 2 thì lần đầu in sẽ thể hiện đơn vị là khoa khám thứ đầu, đóng form khám mở lại in lại thì đơn vị đổi thành khoa khám 2

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/703b810e-3b09-4ce5-9998-4d943c10eca1)

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/ae94e8bb-d3bb-483b-b399-3d12c3ffe07e)

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/ff690891-639a-43b2-9852-0aac8c6c5ef2)

**Comment by chauthanhtra** [comment]
- Khi bệnh nhân khám 2 phòng : Cấu hình lấy chẩn đoán phòng khám sau cùng nhưng in ra thì chẩn đoán chính là chẩn đoán phòng khám đầu tiên

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/195c1cec-929b-45d7-856d-94139d4b1ef0)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/fcd75e93-38c3-4637-bcdd-cb759f10b5b7)

- Bệnh kèm theo và mã bệnh kem theo không xếp đúng thứ tự. và khác nhau giữa 2 lần in (lần đầu và khi đóng form khám bệnh rồi in lại). Mất dấu " ; " giữa 2 tên các tên bệnh kèm theo

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/b607bd0f-e8b9-4076-b3cf-bbec970d4d93)

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/53afffdc-c526-4a4c-8aa8-edadaf2de957)

- Dữ liệu psdangky cột kết quả chẩn đoán và các mã ICD không xếp theo đúng thứ tự và khác với bảng kê

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/7233feaa-38e7-4cd6-9ca6-bd15d1700f5f)

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/70a4c7d7-f8df-407f-b71f-9569f158d5fd)

**Comment by le-an-87** [comment]
Prescription mới khi in bảng kê 6556 luôn đánh dấu psdangky.dain = 1
-> không áp dụng được theo tham số trừ kho ở Prescription.
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/1081b4a6-27f8-471d-9746-02fad8b94b5f)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/92a70fa2-bfcd-489f-a9cd-03d1a1daca28)

**Comment by chauthanhtra** [comment]
>  Bảng kê thiếu thông tin khoa, ngày kết thúc khám, icd chính, chẩn đoán chính, ICD chính và chẩn đoán chính hiện tại đang gom chung với ICD và chẩn đoán phụ.
>   Dữ liệu psdangky, chidinhcls, chungtu, pshdxn không ghi nhận bệnh nhân đã in phiếu và thông tin kết thúc khám như tháng năm quyết toán, icd chính thiếu (bị gọp chung với ICD phụ), ngày in phiếu, trạng thái đã in,...
>    Có cấu hình trừ kho trực tiếp nhưng không trừ kho. không khóa chỉnh chẩn đoán
>    Cấu hình tách chi phí BHYT và ngoài BHYT (DV) ra 2 bảng in nhưng không tách

-> đã fix
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/66bf0b62-884d-4059-a5cf-c0c77f9bc165)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/2e8b9864-1a5e-4d7c-9dce-7d6b37a7d65b)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/a744bc52-6438-43aa-bc35-643bb40a729c)


> * Bảng kê sai trạng thái khám bệnh: cùng tuyến, trái tuyến, thông tuyến
 
>     * Bệnh nhân trái tuyến được hưởng cùng tuyến khi in bảng kê thể hiện bệnh nhân đúng tuyến

>     * Bệnh nhân thông tuyến in bảng kê thể hiện bệnh nhân đúng tuyến

>     * Khi bệnh nhân khám 2 khoa, in phiếu ở khoa thứ 2 thì lần đầu in sẽ thể hiện đơn vị là khoa khám thứ đầu, đóng form khám mở lại in lại thì đơn vị đổi thành khoa khám 2

-> Đã fix
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/205ce66b-8477-4c5f-822f-a0b49a9b2e89)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/7e3a582c-f224-4750-8063-490a5de4e772)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/6b35ec0a-9f02-4508-9989-282b6323b12a)


> Khi bệnh nhân khám 2 phòng : Cấu hình lấy chẩn đoán phòng khám sau cùng nhưng in ra thì chẩn đoán chính là chẩn đoán phòng khám đầu tiên
> Bệnh kèm theo và mã bệnh kem theo không xếp đúng thứ tự. và khác nhau giữa 2 lần in (lần đầu và khi đóng form khám bệnh rồi in lại). Mất dấu " ; " giữa 2 tên các tên bệnh kèm theo
> Dữ liệu psdangky cột kết quả chẩn đoán và các mã ICD không xếp theo đúng thứ tự và khác với bảng kê

-> Đã fix và có hướng xử lý trong issue https://github.com/dh-hos/dhg.hospitalprescription/issues/253

> Dữ liệu bnnoitru: kết quả chẩn đoán xml (kqcdoanxml) và các mã icd (maicdxml và maicdpxml) không xếp đúng thứ tự -> CODE: chưa có hướng xử lý, chỉ lọc trùng

**Comment by chauthanhtra** [comment]
hủy git
