### ISSUE TITLE
Lỗi - Lỗi chỉnh chỉ định uống đối với bệnh nhân đã in ngoại trú đã in phiếu thanh toán bảo hiểm

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#239]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_yhct_mau21_04042024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_yhct_mau21_04042024`](https://gofile.me/78TQg/qAd4hLe6N)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023022829` - _**MaKB**_: `2403000576` - _**NgayKCB**_: `06/03/2024` - _**MaPhong**_: `05` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

   > _**sohd**_: `NB9.00007/202403`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân đã in phiếu thanh toán bảo hiểm
-> nhưng vẫn cho phép chỉnh lại chỉ định uống của toa thuốc.

* Tài khoản thường và cấu hình máy bình thường vẫn chỉnh được.
*** Gây sai lệch giữa cổng bh và toa thuốc đã chỉnh.
```
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/ab29cde3-9dc1-4acd-9d12-fcf9514ace19)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/288b8087-1da6-4b01-aab3-2aa9d71855a9)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/239)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0818.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408182-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408182-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408182-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Giới hạn chỉ có tài khoản admin hoặc có quyền Admin phân hệ mới được chỉnh chỉ định uống.

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/239

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40nghivanbi-informational?logo=github)](https://github.com/nghivanbi) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nghivanbi** [comment]
Đã test trên dữ liệu: : tra_phusan_saidiachi_12082024  port: 5434
![image](https://github.com/user-attachments/assets/a391c6e9-fe68-43dc-8cc8-ef85e4bf7616)
![image](https://github.com/user-attachments/assets/466e326e-fb19-460e-b528-05bb5c33db31)

**Comment by le-an-87** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '20/08/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ TEST**
***
> Hình ảnh Phiếu 01, 02, xuất XML.
![ảnh](https://github.com/user-attachments/assets/b37c30cd-ae2b-4528-a3a6-b12085eec586)

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này: Tài khoản không có quyền admin (Prescription)
![ảnh](https://github.com/user-attachments/assets/2b820b28-d918-41e5-93d3-53878e2067b9)
![ảnh](https://github.com/user-attachments/assets/d565dda2-13a2-49f0-807b-e089df68ad36)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
