### ISSUE TITLE
Yêu cầu - In lại phiếu theo dõi TT/PT

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#24]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Mắt-RHM CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_matct_`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Khi lập **Lập phiếu PT theo dõi** thì có thêm chức năng cho phép in lại phiếu đã tạo(đã có lưu vào bảng phauthuat)
Và yêu cầu nút **Lập phiếu PT theo dõi** luôn hiện lên cho người dùng thầy, hiện mới vào form thì không thấy, nhấn thêm phiếu lưu lại hoặc nhấn Chỉnh phiếu rồi nhấn bỏ qua thì mới hiện nút đó lên.

![image](https://user-images.githubusercontent.com/99630883/188346006-998c914f-f051-44d5-a915-ccaf7d83397d.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.09051](http://www.fsend.vn/download/VlbaadxiEwaEj634PaGIpMMV6rXwPzL_)
