### ISSUE TITLE
Lỗi - Ghi nhận y lệnh công khám trùng thời gian đăng ký.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#240]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_full_t12`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023015671` - _**MaKB**_: `2401000039` - _**MaBA**_: `N2023002165` _**NgayKCB**_: `08/04/2024` - _**MaPhong**_: `16` - _**MaDV**_: `10` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BANT thanh toán ngày, khi đăng ký tái khám thì công khám trong chidinhcls.ngaykcb = psdangky.ngaydk, vô tới phòng khám BS nhấn Chỉnh diển biến, lúc lưu lại thì chidinhcls.ngaykcb cập nhật theo thời gian thực tế chỉ định.
Tình trạng lỗi xảy ra khi người dùng xóa bỏ công khám và chỉ định lại thì lúc chỉ định lại phần mềm cập nhật giờ công khám bảng **chidnhcls.ngaykcb = psdangky.ngaydk** như lúc ban đầu đăng ký => dẫn đến tình trạng cổng báo lỗi giờ công khám trùng giờ đăng ký.
Đề nghị khi BS chỉ định lại công khám thì xử lý lấy lại giờ khám bệnh ban đầu(như khám bệnh thường). và xử lý cảnh báo thêm trường hợp thời gian khám bệnh quá gần với thời gian đăng ký tái khám <= **BANT NGÀY**

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/2fee08d7-20a5-4cc0-82e4-c38cdd87bba1)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/5051f031-2952-44bf-8ec5-08513808dd8f)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/240)

**Comment by lqbinh1987** [comment]
Anh @nghivanbi xem dùm em.

**Comment by nghivanbi** [comment]
Này ngoại trú có bị không?

**Comment by lqbinh1987** [comment]
> Này ngoại trú có bị không?

Không nhe anh

**Comment by lqbinh1987** [comment]
Đã fix.
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/41c21b1d-37bb-414e-81e0-137cc1d39de5)
