### ISSUE TITLE
Lỗi - Bệnh án ngoại trú theo ngày lỗi khi chỉ định công khám

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprescription#242]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51214`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Nội Tiết Tỉnh Quảng Ngãi**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbnoitiet_loithemcongkham`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `tuan_dbnoitiet_loicongkham` - _**MaKB**_: `2404002950` - _**MaBA**_: `N2024003094` _**NgayKCB**_: `15/04/2024` - _**MaPhong**_: `03` - _**MaDV**_: `10` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `KH36` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh án ngoại trú thanh toán theo ngày BS chỉ định công khám xong lưu lại. Sau đó BS xóa và chỉ định lại công khám báo lỗi như hình dưới nhưng Chỉ định các cận lâm sàng khác thì bình thường. 
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/b9ce70e8-b987-484d-a4c1-5b4b8360bbe0)

Chi tiết lỗi:
Phiên bản :2024.04.12.154058PM
Npgsql.NpgsqlException:
invalid input syntax for type timestamp: ""
Severity: ERROR
Code: 22007
   at DataAccess.Adapters.ChiDinhCLSAdapter.Insert(IEntity entity, String pMaphongdp)
   at BusinessLogic.ChiDinhCLS.Insert(String pMaphongdp)
   at Prescription.Forms.FrmCanLamSang.pLuu()
insert into current.chidinhcls(mabn,makb,madt,madv,maphong,ngaykcb,manv,soctvp,macls,soluong,dongia,giabh,chenhlech,dichvu,miengiam,ptmiengiam,thanhtienmg,thanhtien,taikhoan,tenmay,thangkt,namkt,maicd,kqcdoan,stt,tinhtrang,maba,bhyt,ktcao,ldanh,pttraituyen,mienphi,mathe,bant,chiphint,tenclsphu,tile,giabhdm,iddienbien,maicdp,kqcdoanp,sophong,stt_led,idchidinh,sdnguonkhac,mayhct,tenyhct,dinhsuat) values ((('2022003629')),(('2404002950')),(('01')),(('10')),(('03')),(('')),(('005')),(('')),(('KH36')),((1.00)),((33200.000000)),((33200.000000)),((0)),((0)),((0)),((0)),((NULL)),((33200.00000000)),(('ntnhuynh')),(('K45')),(('04')),(('2024')),(('E11')),(('Bệnh đái tháo đường không phụ thuộc insuline')),((5)),((1)),(('N2024003094')),((1)),((0)),((0)),((0)),((0)),(('HT2516697444238')),((1)),((0)),(('')),((100)),((33200.000000)),(('K1.20240415072506')),(('E04.2;I10')),(('Bướu giáp đa nhân -không độc;Bệnh lý tăng huyết áp')),((NULL)),((NULL)),(('2022003629_20240415104752')),((NULL)),(('')),(('')),((0)));

**Comment by nghivanbi** [comment]
Này bệnh án đợt hay ngày @hvtuan1987 ?

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/242)
<details> <summary>   ℹ️<code>2024-15-04 11:08:01</code> <code>@lqbinh1987</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-NvUwBKqursAVdxWYKJo'>-NvUwBKqursAVdxWYKJo</a>]</code></code><code>AZ</code> </summary> <code>[bot]</code><code>1.24.0321.1600@az-o-adv-more-alien-weekly-ubuntu-latest-definitionId28-1713153691387</code><code>[<a href='https://dev.azure.com/o-adv/more-alien-weekly-ubuntu-latest/_build/results?buildId=8140&view=logs'>webhook-logs</a>]</code></details>

**Comment by hvtuan1987** [comment]
@nghivanbi Dạ bệnh án theo ngày á

**Comment by lqbinh1987** [comment]
Đã hỗ trợ fix tại #252 .
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/a03add00-ce31-43c6-b0bb-796a82267901)

**Comment by lqbinh1987** [comment]
Phát hiện lỗi mới khi fix lỗi này(lỗi mới trước khi fix không bị)

**Comment by nghivanbi** [comment]
@lequocthong29 check thử coi bản mới lỗi không nhé.

**Comment by lqbinh1987** [comment]
Lỗi mới không liên quan lỗi cũ, đã lập git mới, close này.
