### ISSUE TITLE
Lỗi - In toa thuốc không được khi áp cks.url

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#244]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **79035**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvgovap_042024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://dhsolutions.synology.me:5001/d/s/y5MH822mKEnRGWc3kpUkToScyl8q7Qbx/oT2M8LvaYut1wCtKYD-oIeAOOgThuFgm-z7qA33qSSgs)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `ALL` - _**MaKB**_: `ALL` - _**MaBA**_: `MaBA` _**NgayKCB**_: `01/04/2024` - _**MaPhong**_: `115` - _**MaDV**_: `10` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi không áp giá trị địa chỉ cho tham số **cks.url** thì in toa thuốc ra tất cả đều bình thường theo thiết kế.
Nếu áp giá trị cho tham số **cks.url** thì lúc in toa thì:
Tài khoản nào không có map chữ ký thì cũng in toa thuốc ra tất cả đều bình thường theo thiết kế.
Tài khoản nào có map chữ ký thì in ra nó cố định 1 mẫu như hình dưới, mặc dù là mẫu thiết kế đã có sẳn.

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/0d153bb5-dcd8-4d0c-ba02-cbe8fb88eb38)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/244)
