### ISSUE TITLE
Lỗi - Bệnh án ngoại trú theo ngày, Kết thúc điều trị xử lý Nhập viện báo lỗi

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprescription#247]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện đa khoa Thành phố Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbtpct_bant_nhapvien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/s9jZ87Yup)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024011168` - _**MaKB**_: `2405009424` - _**MaBA**_: `N2024005455` _**NgayKCB**_: `09/05/2024` - _**MaPhong**_: `18` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2024`

-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

 Bệnh nhân  có lập Bệnh án ngoại trú theo ngày. Kết thúc điều trị và và sau đó bấm vào Nút  Nhập viện báo lỗi như hình dưới
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/b85a6a1e-cd06-424a-ac62-42c89776c7de)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/247)

**Comment by ongtrieuhau-dh** [comment]
Nhờ @nghivanbi  hướng dẫn nghiệp vụ chỗ này để giao cho @lequocthong29 fix nhé, hiện trạng đang lấy mặc định ngày nhỏ nhất của ngaykcb trong khambenh để làm giá trị mặc định với điều kiện dakham<>0, nhưng dữ liệu lại là = 0, thì trường hợp này lỗi ở chỗ kết thúc điều trị không set dakham hay sao?

**Comment by nghivanbi** [comment]
Để kiểm lỗi và hướng dẫn @lequocthong29 fix.

**Comment by nghivanbi** [comment]
https://storage.googleapis.com/remmesionlangter-01.appspot.com/msiFiles/Prescription.exe/Setup-Prescription.exe.v3.24.0510.1.msi

**Comment by nghivanbi** [comment]
Thử này dùm anh cái @hvtuan1987, up bài bản sau.

**Comment by hvtuan1987** [comment]
@nghivanbi Bản này khi Kết thúc điều trị và bấm vào Nút Nhập viện thì hết nhưng lỗi phát sinh là khi bấm vào nút Nhập viện thì thông tin anh hiển thị như hình dưới. Nếu người dùng bấm chỉnh chọn khoa cho nhập viện thì báo như hình dưới. Nếu bấm xóa thì thông tin bệnh nhân tìm lại không thấy nữa !
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/9afc2bd3-2e49-4467-9ce0-f0fd5c09dfc7)

**Comment by hvtuan1987** [comment]
@lequocthong29 Coi tiếp vụ này dùm anh hén ! 
Kiểm tra bệnh nhân hình dưới 
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/b6c12f67-d35b-42fc-ab97-a4cd67f770ad)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0527.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32405270-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32405270-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32405270-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi khi ấn nhập viện, chỉnh thông tin thì không lưu được

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/247

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Vẫn còn lỗi ! Khi bấm vào nút nhập viện phải lấy số bệnh án mới theo bảng soba, Hiện tại đang lấy số Bệnh án Ngoại trú của bệnh nhân vừa kết thúc làm số bệnh án Nội trú .
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/877c1bf5-d858-46ca-a1fa-16c67e4d4f29)

**Comment by lequocthong29** [comment]
@hvtuan1987 cho e xin cái hình số bệnh án mới phát sinh trong bảng soba

**Comment by hvtuan1987** [comment]
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/15b60d51-560c-44de-898e-45fc84234b7e)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0529.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32405290-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32405290-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32405290-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi khi ấn nhập viện, chỉnh thông tin thì không lưu được

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/247

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Tiếp tục lấy sai bảng mã bệnh án:
Xử trí **02 [NHẬP VIỆN]** phải lấy số bệnh án từ bảng soba. Hiện tại tại đang lấy bảng sobangoai
Khi nào xử trí **[07 Bệnh án ngoại trú]** mới cấp số bệnh án từ bảng sobangoai
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/f1369229-f13b-49ed-bb76-2bfd05854d8c)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/db5d25bf-d980-4465-a554-996b06a85d1a)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/5bc493b8-0e91-43df-82c8-d2b3b6c9cc91)

**Comment by ongtrieuhau-dh** [comment]
@lequocthong29 check tiếp lỗi này nhé

**Comment by lequocthong29** [comment]
@hvtuan1987 Thử lại trên bản Prescription mới nhất nha a

**Comment by hvtuan1987** [comment]
Đã ok !
