### ISSUE TITLE
Lỗi - Báo cáo BN OPC

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#249]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Quận Thốt Nốt**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thotnot_full_14052024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `ALL` - _**MaKB**_: `ALL` - _**MaBA**_: `ALL` _**NgayKCB**_: `ALL` - _**MaPhong**_: `HIV` - _**MaDV**_: `10` - _**ThangKT**_: `ALL` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trên form khám BN HIV, tất cả các báo cáo trong menu Báo cáo OPC đều bị lỗi khi lấy số liệu, **chạy số liệu của bất kỳ ngày nào cũng bị:**

Error [0]Message: Lỗi code [OTH.FHI.Adapter.AFHI_BaoCaoBenhNhan.loadBCFHIV2].

Error [0]HResult: -2146233088
Error [0]Source: OTH.Model.FHI
Error [0]StackTrace:    at OTH.FHI.Adapter.AFHI_BaoCaoBenhNhan.loadBCFHIV2(RptTimeBC timeBC, Form parentForm, List`1 lstSoBA, v_BCFHI numBCFHI)
   at OTH.FHI.Forms.XFrmBCFHIV2.xTab_CustomHeaderButtonClick(Object sender, CustomHeaderButtonEventArgs e)
Error [0]TargetSite: Void loadBCFHIV2(OTH.Model.Reports.RptTimeBC, System.Windows.Forms.Form, System.Collections.Generic.List`1[OTH.Entity.fhi.fhi_dieutriarv], OTH.FHI.Adapter.v_BCFHI)

Error [1]=== INNER EXCEPTION ===
Error [1]Message: Lỗi xảy ra tại [Name:System.String OTH.Common.ClsExtensionMethods.ToJsonNewtonSerialize(System.Object),Assembly:OTH.Common.dll,Version: Version=1.24.117.0].
Error [1]HResult: -2146233088
Error [1]Source: OTH.Common
Error [1]StackTrace:    at OTH.Common.ClsExtensionMethods.ToJsonNewtonSerialize(Object objModel)
   at OTH.FHI.Adapter.AFHI_BaoCaoBenhNhan.loadBCFHIV2(RptTimeBC timeBC, Form parentForm, List`1 lstSoBA, v_BCFHI numBCFHI)
Error [1]TargetSite: System.String ToJsonNewtonSerialize(System.Object)

Error [2]=== INNER EXCEPTION ===
Error [2]Message: Exception of type 'System.OutOfMemoryException' was thrown.
Error [2]HResult: -2147024882
Error [2]Source: mscorlib
Error [2]StackTrace:    at System.Text.StringBuilder.ToString()
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   at OTH.Common.ClsExtensionMethods.ToJsonNewtonSerialize(Object objModel)
Error [2]TargetSite: System.String ToString()

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/ae9d5855-2486-46ce-9f31-062951448c96)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/249)
<details> <summary>   ℹ️<code>2024-15-05 08:12:53</code> <code>@lqbinh1987</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-NxtnnX7aVA9u_WXqtR7'>-NxtnnX7aVA9u_WXqtR7</a>]</code></code><code>AZ</code> </summary> <code>[bot]</code><code>1.24.0321.1600@az-o-adv-more-alien-weekly-ubuntu-latest-definitionId28-1715734985463</code><code>[<a href='https://dev.azure.com/o-adv/more-alien-weekly-ubuntu-latest/_build/results?buildId=12453&view=logs'>webhook-logs</a>]</code></details>

**Comment by nghivanbi** [comment]
@ongtrieuhau kiểm dùm anh lỗi này cái. Mấy cái báo HIV nó lỗi.

**Comment by ongtrieuhau-dh** [comment]
@nghivanbi pull dll thử lại nhé

**Comment by lqbinh1987** [comment]
Này em đã thử trên dữ liệu của Cái răng cũng bị nữa nhe anh @ongtrieuhau , anh @nghivanbi , em xài bản cũ xì lun cũng bị nữa á.
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/cbb68959-b589-44bb-8fea-5474e7b49648)

**Comment by ongtrieuhau-dh** [comment]
@nghivanbi , pull libraries để fix lỗi này nhé ![image](https://i.imgur.com/NRgLG6O.png)

**Comment by lqbinh1987** [comment]
anh @nghivanbi ơi, bv nó dzí quá.

**Comment by nghivanbi** [comment]
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/91751241/d70ad7eb-4903-4a36-b832-c4f7dc4d91cb)
Pull mới về cũng còn lỗi, @ongtrieuhau kiểm tra fix nhé.

**Comment by ongtrieuhau-dh** [comment]
Hạn 22/05 nhé

**Comment by ongtrieuhau-dh** [comment]
Nhờ anh @nghivanbi , check lại nhé, pull libraries lại thử xem
![](https://i.imgur.com/60hraeV.png)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0521.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32405212-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32405212-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32405212-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix báo cáo bệnh nhân OPC

- ☑:  https://github.com/dh-hos/dhg.hospitalprescription/issues/249

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40nghivanbi-informational?logo=github)](https://github.com/nghivanbi) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nghivanbi** [comment]
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/91751241/5b8d1958-eda9-400f-93a0-799a003d91fc)

**Comment by lqbinh1987** [comment]
Đã fix
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/14831b29-e4c2-4c80-8388-0d88d9b7993f)
