### ISSUE TITLE
Lỗi - Chỉnh thông tin BANT theo đợt không cập nhật thông tin trên form BANT, danh sách bệnh nhân đăng ký KCB có 2 dòng khi lập bệnh án

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#25]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_giairai_diagnose_tmh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022000001` - _**MaKB**_: `2209000467` - _**MaBA**_: `N2022000001A` _**NgayKCB**_: `05/09/2022` - _**MaPhong**_: `12` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- khi hiệu chỉnh thông tin bệnh nhân BANT theo đợt thì trên form vẫn thể hiện thông tin lúc nhận bệnh phải vào hiệu chỉnh thêm thông tin ngoại trú của bệnh nhân 
![ảnh](https://user-images.githubusercontent.com/97272332/188352281-6fdb5894-1187-4d07-84c6-9a8cdd28e740.png)

- Khi lập BANT cho bệnh nhân thì danh sách đăng ký của bệnh nhân sẽ có 2 dòng trên Register và Prescription đều bị
![ảnh](https://user-images.githubusercontent.com/97272332/188352561-10c98693-dd9e-445c-8517-a18c3803d7a5.png)
![ảnh](https://user-images.githubusercontent.com/97272332/188352596-9d779c6c-6412-4771-870f-bb2548b13e80.png)

-- em chuyển lỗi này bên nhóm cũ qua đây.

**Comment by nghivanbi** [comment]
Chức năng này là đúng. Khi bệnh nhân đã lập bệnh án ngoại trú thì hiệu chỉnh chỉ có tác dụng trong bệnh án ngoại trú thôi.

**Comment by chauthanhtra** [comment]
chỉnh xong trong Hiệu chỉnh TT của bệnh án nhưng thông tin hiển thị trên form bên ngoài BANT vẫn thể hiện thông tin cũ gây hiểu lầm chưa chỉnh được thông tin

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0909.3](http://www.fsend.vn/download/h1qkqKYJYiSmvl8kShqRO2G7G_NKcBiT)

**Comment by chauthanhtra** [comment]
1- Chỉnh đối tượng BANT theo đợt psdangky bị cập nhật lại madt, ví dụ: nhận bệnh thu phí 06 lập BANT chỉnh đối tượng BANT sang bảo hiểm 01 thì psdangky.madt -> 01 nhưng thông tin thẻ BHYT trên psdangky bị trống.
![ảnh](https://user-images.githubusercontent.com/97272332/189572000-c89ae367-6144-44f5-8bc6-36afd81b2930.png)
![ảnh](https://user-images.githubusercontent.com/97272332/189572228-7fd1ef2e-3790-4b06-9eaf-20d95f775fb4.png)

2- Ô thông tin tên đối tượng trên bant đang load theo psdangky, ví dụ: bnnoitru.madt = 01 (BHYT) và psdangky.madt = 06 (thu phí)
![ảnh](https://user-images.githubusercontent.com/97272332/189572604-0a7f4fe7-1a9a-426e-b353-5ef03704fe98.png)
