### ISSUE TITLE
Lỗi - Chức năng in bảng kê 6556 (BV Ô Môn)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#251]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_omon_bangke_27052024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_omon_bangke_27052024`](https://drive.google.com/file/d/1k_A1fvgrChUbj4mK-Q-kJ9aIMNjkc_na/view?usp=drive_link)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021057923` - _**MaKB**_: `2405023045` - _**NgayKCB**_: `27/05/2024` - _**MaPhong**_: `CC1` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng in bảng kê 6556 in thiếu
- Thông tin khoa
- Tên bệnh chính
- mã bệnh chính

-> Đối với trường hợp đăng ký phòng 05 (không khám) rồi chuyển qua khám tại phòng CC1

*Printer 22/05/2024 in có thông tin bình thường

```
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/57bb44ef-5e10-495a-baf3-f0e329549b6c)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprescription/251)

**Comment by ongtrieuhau-dh** [comment]
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/155862740/750d9c47-552f-4500-82e7-f2720646cbca)

**Comment by le-an-87** [comment]
đã chỉnh link anh thử lại giúp.
hoặc sử dụng link nas sau nhe: https://gofile.me/78TQg/lykfpAy9R

**Comment by nghivanbi** [comment]
@le-an-87 check lại dùm anh lỗi này, nhớ là có sử lý lỗi tương tự xong rồi.

**Comment by le-an-87** [comment]
Đã fix khi kiểm tra với Prescription phiên bản 10/06/2024!
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/617b7e4a-a0f7-4c1b-9af4-8d1292d90c83)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/ae0a713d-0eed-4d2e-997a-752b65c127fd)
