### ISSUE TITLE
Lỗi - PHÁT SINH LỖI KHI CHỈ ĐỊNH CÔNG KHÁM CHO BANT

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#252]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/60/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbthanhtri_loichidinhcls_bant`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/tI2oIgWXG)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2014015757` - _**MaKB**_: `2406004866` - _**MaBA**_: `N2021001631` _**NgayKCB**_: `14/06/2024` - _**MaPhong**_: `16` - _**MaDV**_: `10` - _**ThangKT**_: `06` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi chỉ định CLS cho BANT các kho CLS khác lưu được bình thường chỉ riêng kho Công khám là phát sinh lỗi.
Test ban đầu bản Pre 02/02 lưu bình thường, bản BV đang sử dụng là 11/4 và bản mới nhất 12/6 phát sinh lỗi.

Hiện tại BV không chỉ định CK được cho BANT nên cần fix gấp để sử dụng. 

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/38950044-fc0d-441b-b80f-6989b701a7c2)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0617.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406170-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406170-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406170-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi phát sinh khi chỉ định công khám - do khám khác phòng đăng ký

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/252

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
Trường hợp phát sinh lỗi khi Đăng ký BANT theo ngày tại 1 phòng nhưng khám tại phòng khác sẽ không lấy được ngaykcb để gán cho công khám >> đã fix

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/a4f8d7e7-8dd9-4894-8faf-7f1039a9ca62)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/2a7765f3-b3be-4114-afe9-9fb622b7d0d1)

**Comment by nqhoa1005** [comment]
phát sinh thể hiện sai trên danh sách theo trường hợp Đăng ký 1 phòng nhưng khám 1 phòng khác cùng khoa, khi có chẩn đoán và chi phí đang thể hiện 2 dòng.

Đăng ký phòng 01
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/0a1a2ac8-68b5-40dc-90d2-b9ead7fcb308)

Khám phòng 02
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/a0de6144-ae05-4bfa-9e93-82efef556fa7)

sẽ xuất hiện 2 dòng
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/be2bdb7d-0fc3-433c-8fe6-bf4cb05dd035)

**Comment by lequocthong29** [comment]
@nqhoa1005 Này không liên quan đến lỗi chỉ định công khám ở trên, anh chuyển qua Git mới dùm e nha a
