### ISSUE TITLE
Lỗi - Trùng chẩn đoán chính và chẩn đoán kèm theo bệnh nhân khám nhiều phòng

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#253]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Quảng Ngãi**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_quangngai_trungchandoan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/6FDpTlLND)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020030876` - _**MaKB**_: `2406002585` - _**MaBA**_: `MaBA` _**NgayKCB**_: `10/06/2024` - _**MaPhong**_: `A1=29` - _**MaDV**_: `10` - _**ThangKT**_: `06` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trùng chẩn đoán chính và chẩn đoán kèm theo bảng kê 6556 bệnh nhân khám 2 phòng có chẩn đoán giống nhau
- Test thấy không phải chẩn đoán nào cũng bị trùng, bệnh nhân mới chỉ định giống bệnh nhân lỗi cũng bị trùng, chưa tìm được nguyên nhân cụ thể
- Dữ liệu chẩn đoán psdangky.kqchandoan đúng, không bị trùng
- Prescription và Printer in đều bị trùng giống nhau

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/acb939c9-1857-4a21-a247-d237c3ea7112)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0618.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32406180-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32406180-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32406180-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Trùng chẩn đoán chính và chẩn đoán kèm theo bệnh nhân khám nhiều phòng

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/253

- ![](https://i.imgur.com/493rDKv.png)

- 📕: Xử lý trim khoảng trắng trước và sau trước khi replace, để loại bỏ trùng

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0618.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406180-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406180-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406180-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Trùng chẩn đoán chính và chẩn đoán kèm theo bệnh nhân khám nhiều phòng

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/253

- ![](https://i.imgur.com/493rDKv.png)

- 📕: Xử lý trim khoảng trắng trước và sau trước khi replace, để loại bỏ trùng

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- Printer đã fix lỗi trùng tên bệnh kèm theo

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/8c1cfa68-cbb7-407e-8b02-4b13ef7a5add)

- Test Prescription còn lỗi sai tên bệnh kèm theo : in lần đầu thiếu mã bệnh, in lại thì thiếu dấu " ; " giữa tên bệnh và sai vị trí tên bệnh và mã bệnh
> mã BN: 2024000005
> mã KB: 2406002591
> ngày: 19/6/2024
> khoa: 10
> phòng: A1-08

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/bc3af8be-52f8-4834-b630-589638d52119)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/571ddf57-e0f2-4d8f-a741-42421a63cdc5)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/8e6a74a9-177f-443f-bac6-c60f7eb8515a)

**Comment by ongtrieuhau-dh** [comment]
Nhờ @chauthanhtra tạo một bệnh nhân mới, để test thử lần đầu nhé, còn thứ tự chẩn đoán và mã iCD đó giờ chỉ xử lý trùng thôi, không theo thứ tự nhé

**Comment by chauthanhtra** [comment]
mã BN: 2024000004
mã KB: 2406002590
ngày : 19/6/2024
khoa: 10
phòng: A1=29

bệnh nhân cũ anh mở khóa trên Printer rồi qua Prescription in cũng bị vậy

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0622.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406221-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406221-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406221-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Trùng chẩn đoán chính và chẩn đoán kèm theo bệnh nhân khám nhiều phòng

- 🐛: Lỗi - In lần đầu thiếu chẩn đoán

- ![](https://i.imgur.com/sF4SkIj.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/253

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
Prescription in bảng kê vẫn còn lỗi nha anh

- In lần đầu: thiếu chẩn đoán

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/bfabe4ad-8692-434a-8cb4-6340f0dcdcd3)

- In lại: mất dấu ' ; '

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/d19be95d-ad6f-4beb-b088-b893a375c3ea)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0624.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406241-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406241-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406241-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Trùng chẩn đoán chính và chẩn đoán kèm theo bệnh nhân khám nhiều phòng

- 🐛: Lỗi - In lần đầu thiếu chẩn đoán

- [](https://i.imgur.com/eR0lBlS.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/253

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
Prescription.exe v.3.24.0624.1 vẫn còn lỗi nha anh

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/5aef1249-aaba-4f8b-b919-13dcb67fffca)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/e838499c-36aa-47d3-be76-8fea31320fe2)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/9ca56d93-3e8c-4c67-878d-41e5d50be0e6)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0624.3 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406243-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406243-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406243-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Trùng chẩn đoán chính và chẩn đoán kèm theo bệnh nhân khám nhiều phòng

- 🐛: Lỗi - In lần đầu thiếu chẩn đoán

![](https://i.imgur.com/i8BJyyz.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/253

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0624.4 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406244-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406244-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406244-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Trùng chẩn đoán chính và chẩn đoán kèm theo bệnh nhân khám nhiều phòng

- 🐛: Lỗi - In lần đầu thiếu chẩn đoán

![](https://i.imgur.com/i8BJyyz.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/253

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- Đã lấy đủ chẩn đoán và không thiếu dấu ' ; ' giữa các chẩn đoán

- Cần thống nhất lại cách lấy chẩn đóan và mã bệnh giữa các phần mềm Prescription, Printer : hiện tại Prescription in lần 1 và lần 2 chần đoán kèm theo khác nhau và khác với Printer (số lượng đủ nhưng thứ tự bị khác) -> mỗi phần mềm in ra bảng kê mỗi khác. mã bệnh kèm theo giữa Prescription và Printer cũng khác nhau (số lượng đủ nhưng thứ tự bị khác)

  - Prescription 
    - ![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/c62e6af7-20a6-4939-a031-a43b8a2c0515)
    - ![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/12567058-410e-4000-ad16-dd3ca246c44d)

  - Printer 
    - ![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/52a26b8f-cc7c-4641-b8ac-f22ebde69007)

**Comment by ongtrieuhau-dh** [comment]
> Cần thống nhất lại cách lấy chẩn đóan và mã bệnh giữa các phần mềm Prescription, Printer : hiện tại Prescription in lần 1 và lần 2 chần đoán kèm theo khác nhau và khác với Printer (số lượng đủ nhưng thứ tự bị khác) -> mỗi phần mềm in ra bảng kê mỗi khác. mã bệnh kèm theo giữa Prescription và Printer cũng khác nhau (số lượng đủ nhưng thứ tự bị khác)

Phần này chưa có hướng xử lý, vì hiện tại gom lại rồi xử lý trùng nên khó xác định ở chỗ nào. Cái này để xem có hướng khác không nhé
