### ISSUE TITLE
Lỗi - Bảng kê 6556 bệnh nhân ngoại trú thu phí in không có ngày kết thúc (BV CLM)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#258]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_130_tohotro_issues_20`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_130_tohotro_issues_20`](https://gofile.me/78TQg/YtB4Weguy)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024010762` - _**MaKB**_: `2406000032` - _**NgayKCB**_: `25/06/2024` - _**MaPhong**_: `11` - _**MaDV**_: `10` - _**ThangKT**_: `06` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bảng kê 6556 bệnh nhân ngoại trú thu phí in không có ngày kết thúc.

```
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/6b2986d1-5567-409a-8bcb-9d448d7bc78b)

**Comment by ongtrieuhau-dh** [comment]
Cái này là view hay in vậy @le-an-87

**Comment by le-an-87** [comment]
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/67fc6577-f5b1-4a5f-b476-89028fd57b0b)
em gửi bản in

**Comment by ongtrieuhau-dh** [comment]
Ok, để kiểm lại nhé

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0625.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406250-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406250-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406250-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Thêm chức năng để tùy chọn in hay preview để set ngayinphieu trong psdangky

- 🐛: Lỗi - Bảng kê 6556 bệnh nhân ngoại trú thu phí in không có ngày kết thúc

- ![](https://i.imgur.com/fdDTJKx.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/258

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Đã fix ngày kết thúc bảng kê 6556
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/830c3cc9-c77d-4208-a7f3-40c132a91b92)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/96155021/31ab3f15-ddea-48d6-95fc-0922ecd524fb)
