### ISSUE TITLE
Lỗi - BV QDY ST: không sử dụng được nút cập nhật chỉ số sinh hiệu, tự đổi bệnh nhân khi lưu Chỉnh thông tin form khám bệnh, hỗ trợ tab nhập sinh hiệu

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#259]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/6/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94009`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV QDY ST**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_st_capnhatsinhhieu_25062024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `25/06/2024` - _**MaPhong**_: `003` - _**MaDV**_: `02` - _**ThangKT**_: `06` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. Chức năng cập nhật chỉ số sinh hiệu form khám bệnh không sử dụng được  -> bệnh nhân đã có chẩn đoán không chỉnh được sinh hiệu form khám bệnh, phải vài hiệu chỉnh thông tin

  ![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/40122284-cc00-4d8d-a2fa-2495ecd8ec57)

2. Chỉnh thông tin form khám bệnh xong lưu lại thì phần mềm load dữ liệu bệnh nhân khác. phải tìm lại bệnh nhân mới khám được -> chậm, dể nhầm bệnh nhân 

  ![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/7ecdbda7-882e-4ea5-8bb7-5fc2ccbcf1fb)
  ![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/9e36da3c-b580-402c-b09d-a14c85502bfc)

3. Đề nghị hỗ trợ BV sử dụng phím Tab hoặc enter nhập chỉ số sinh hiệu giúp giảm thời gian nhập thông tin chỉ số

  - Form khám bênh
    - Khi bấm phím Tab để nhập số sịnh hiệu thì bị bỏ qua Huyết áp
    - Đến nhịp thở bấm phím Tab thì mất con trỏ phải nhấn phím Tab lần 2 mới cho nhập Hb 

    ![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/fbf5c567-6c35-433a-ba9b-e031973f6d0d)

  - Form nhận bệnh Prescription , Register . nếu được thứ tự Tab nhập chỉ số sinh hiệu nên nhập theo thứ tự -> dễ nhập

  ![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/a480bfe5-8c19-48e0-9dbd-8d4cb3bc7cbf)

**Comment by le-an-87** [comment]
mục 1.
-> đề xuất khi nhấn cập nhật nếu phần mềm có ràng buộc thì hiển thị thông báo lý do không cho cập nhật.

**Comment by ongtrieuhau-dh** [comment]
@lequocthong29 xem xử lý mấy cái trên nhé

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0626.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406261-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406261-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406261-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi không dùng được chức năng cập nhật chỉ số hiệu sinh - form khám bệnh

- 🐛: Fix lỗi chỉnh thông tin form khám bệnh xong lưu lại phần mềm load dữ liệu bệnh nhân khác.

- 🐛: Fix lỗi khi ấn Tab để nhập số sinh hiệu không theo thứ tự

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/259

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
Prescription.exe v.3.24.0626.1

Đã fix lỗi: 

- Fix lỗi không dùng được chức năng cập nhật chỉ số hiệu sinh - form khám bệnh
- Fix lỗi chỉnh thông tin form khám bệnh xong lưu lại phần mềm load dữ liệu bệnh nhân khác.
- Fix lỗi khi ấn Tab để nhập số sinh hiệu không theo thứ tự

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/9d1e5340-eb57-48c1-b5bd-24aaf2bfddac)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/c3600410-019a-43b6-b1cb-c499651874e5)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/f29da7ec-1d67-4246-b44c-c758c83fb048)
![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/89afa119-6565-4b98-a9d4-3f9b53634df2)


Cần thêm Register mới

**Comment by chauthanhtra** [comment]
Thêm Register luôn nha @lequocthong29

**Comment by chauthanhtra** [comment]
Register đã fix hỗ trợ tab chỉ số sinh hiệu

![ảnh](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272332/d9a47906-e9b4-4b3c-95d7-93b5435a1dac)
