### ISSUE TITLE
Lỗi - Chức năng ra toa / chọn toa mẫu báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#26]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92017`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Da Liễu CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dalieu_chotoamau`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021022394` - _**MaKB**_: `2209004233` - _**NgayKCB**_: `12/09/2022` - _**MaPhong**_: `2` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2022` - _**TaiKhoan**_: `nthau`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi ra toa cho bệnh nhân -> chọn toa mẫu Prescription báo lỗi

```
chọn toa mẫu
![image](https://user-images.githubusercontent.com/96155021/189565245-d90dcdf8-3935-4061-aea3-56111f8bc53f.png)
Prescription báo lỗi
![image](https://user-images.githubusercontent.com/96155021/189565298-4c1f25fc-5b6e-4aef-9d3b-8c86ee855923.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0913.1](https://drive.google.com/file/d/1t5cyD7mPk4XFlO6mSF4CuejUZDcJd6kZ/view?usp=sharing)

**Comment by le-an-87** [comment]
![image](https://user-images.githubusercontent.com/96155021/189804622-db2dfdab-6f35-4b4b-be06-051515ae2ccd.png)
không tải được anh ơi

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0913.1](http://www.fsend.vn/download/AOmzg76UjT4xUWCEA0idK27v95ykh3e-)

**Comment by le-an-87** [comment]
đã fix!
