### ISSUE TITLE
Lỗi - Test - Lỗi Sổ khám bệnh trên Prescription

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprescription#261]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Đông Hải**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_donghai_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/96oMBbPpO

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**ThangKT**_: `06` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Sổ khám bệnh bấm Xem báo Lỗi khi nạp dữ liệu
File lỗi chi tiết 
[Lỗi Sổ Khám bệnh_Pre.txt](https://github.com/user-attachments/files/16007775/L.i.S.Kham.b.nh_Pre.txt)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/0c0c36a2-fabc-4eec-9bc9-26b50963eea4)

**Comment by ongtrieuhau-dh** [comment]
@lequocthong29 xem qua nhé

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0627.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406272-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406272-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406272-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi không load được danh sách sổ khám bệnh

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/261

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
Đã kiểm tra Sổ khám bệnh trên Pre xuất dữ liệu bình thường
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/d617acba-6874-4f83-821f-3e957ab66b39)

Các chức năng cơ bản khác: Đăng ký, khám bệnh, in 01 chưa ghi nhận bất thường
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/510a4a66-c8c0-48ad-add6-6ae3c72e5af0)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/87c6ede6-515f-479a-ba37-38b5c85b0271)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/98437757/24648d74-bfd9-400c-a8a4-88b0a61fc6df)
