### ISSUE TITLE
Lỗi - BANT Theo đợt không xuất được XML khi kết thúc điều trị

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprescription#266]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#
-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77156`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PKĐK PHÚC GIA KHANG 1**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphucgiakhang_072024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/rCrAHTy0a)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024005717` - _**MaKB**_: `2407000001` - _**MaBA**_: `N2024000001` _**NgayKCB**_: `03/07/2024` - _**MaPhong**_: `K12` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

  Bệnh án ngoại trú theo đợt Kết thúc điều trị ngày 03/07/2024 nhưng vào Module Admin Kiểm tra xuất XML không thấy bệnh nhân. Nhờ code kiểm tra còn vướng tham số nào để hỗ trợ phòng khám !
Các bước đã làm:
1.Cho kết thúc điều trị
2.n bảng kê
3. Vào Printer xác nhận in phiếu phát thuốc
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/2a32bd61-4526-457f-a811-96a28baff6d4)
Khi vào xem XML tại admin
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/97272364/1ea8c059-4ce8-41a4-add2-956b487a86a8)

**Comment by ongtrieuhau-dh** [comment]
@lequocthong29 tiếp nhận thì ghi nhận theo qui trình vào đây nhé

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Kiểm tra lỗi Bệnh án ngoại trú theo đợt Kết thúc điều trị nhưng vào Module Admin Kiểm tra xuất XML không thấy bệnh nhân.
-  📆 **Thời gian hoàn thành :**  04/07/2024.

**Comment by lequocthong29** [comment]
@hvtuan1987 chổ này phải Tổng kết CP -> in tổng kết thì Admin mới hiển thị lên nha a
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/110148171/31a7cdf8-ad89-4295-beb7-14c742003249)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/110148171/01a178b5-0baa-4404-a5d8-844fc630b8da)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/110148171/5d9d6ec7-81a1-4a8b-9c03-a563c522b7e8)

**Comment by hvtuan1987** [comment]
ok !
