### ISSUE TITLE
Lỗi - SAI SỐ TIỀN CẢNH BÁO GIỚI HẠN TIỀN THUỐC

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#267]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN QUẬN 12 **
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_bvq12_canhbaotienthuoc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/QtX6SXYda)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024048410` - _**MaKB**_: `2407004222` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `09` - _**MaDV**_: `10` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Tham số ghtienthuoc = 1.000.000
khi ra toa thuốc tổng tiền thuốc chưa đến số tiền giới hạn đã chặn không cho lưu
nghi ngờ tổng tiền thuốc + tổng chi phí bên dưới.
Fix thêm thông báo chỉnh lại số tiền cho đúng định dạng có dấu phân cách hàng nghìn hiện thông báo lấy trực tiếp 1000000
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/95849aad-1231-4203-b1ba-ca1e62b6aedc)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Lỗi - SAI SỐ TIỀN CẢNH BÁO GIỚI HẠN TIỀN THUỐC
-  📆 **Thời gian hoàn thành :**  06/07/2024.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0706.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407060-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407060-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407060-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi khi ra toa thuốc tổng tiền thuốc chưa đến số tiền giới hạn đã chặn không cho lưu

- 🐛: Fix - thông báo chỉnh lại số tiền cho đúng định dạng có dấu phân cách hàng nghìn hiện thông báo lấy trực tiếp 1000000

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/267

![](https://i.imgur.com/U929qOw.png)

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
Đã fix

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/8f3bc3ff-8667-4808-8eb0-c906b80a17bb)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/3a08e9ae-48ab-4d8e-a3f8-9177722ae4c7)
