### ISSUE TITLE
Lỗi - THỜI GIAN THỰC HIỆN PT/TT CHƯA BẮT THEO NGÀY GIỜ Y LỆNH 

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#269]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **ngay_tiep_nhan**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87163`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV TÂM THẦN ĐỒNG THÁP**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_bvttdt2021`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/9041D5t2i)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024003717` - _**MaKB**_: `2407001623` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `KB` - _**MaDV**_: `10` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. Thời gian bắt đầu PT/TT hiện tại vẫn cho phép người dùng chỉnh nhỏ hơn giờ chỉ định
>> Ràng buộc thời gian bắt đầu > thời gian chỉ định
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/d4366fde-d7b4-4f23-9534-999c17f0e284)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/17d5ca7a-0aef-43c4-94d3-f64878ccd8e5)

2. Khi thêm toa thuốc ràng buộc thời gian ra toa phải lớn hơn ngày giờ kết thúc của phiếu PT/TT (cùng phòng)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/5d61b3f5-129d-4e81-ab95-a7307dd291e2)
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/130281806/0760e970-3ac9-47f1-8812-8ad48ae44aef)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Fix lỗi - THỜI GIAN THỰC HIỆN PT/TT CHƯA BẮT THEO NGÀY GIỜ Y LỆNH.
-  📆 **Thời gian hoàn thành :**  2024/07/12.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0711.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407110-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407110-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407110-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Lập phiếu PT,TT - Kiểm tra thời gian bắt đầu và kết thúc không được nhỏ hơn thời gian chỉ định.

- ✨: Toa thuốc ràng buộc thời gian ra toa phải lớn hơn ngày giờ kết thúc của phiếu PT/TT

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/457

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/269

![](https://i.imgur.com/2s9MCBc.png)

![](https://i.imgur.com/8UfoGho.png)

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0711.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407111-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407111-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407111-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Chuyển câu thông báo sang dạng cảnh báo.

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/457

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/269

![](https://i.imgur.com/ilC5Krd.png)

![](https://i.imgur.com/NBAFjQf.png)

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
đã ràng buộc thời gian bắt đầu TT/PT lớn hơn thời gian chỉ định
![image](https://github.com/user-attachments/assets/f0c92e9d-4a35-40e9-8a90-38b882356e82)
![image](https://github.com/user-attachments/assets/b7b7c505-7594-4542-bca9-56557b93e0d9)

**Comment by nqhoa1005** [comment]
Khi lập PT/TT xong > ra toa thuốc kiểm tra và cảnh báo giờ lập toa thuốc phải lớn hơn thời gian kết thúc PT/TT
Test lại khi lập toa thuốc với giờ lập nhỏ hơn thời gian kết thúc vẫn chưa có cảnh báo/chặn
![image](https://github.com/user-attachments/assets/7d478510-b33f-4d29-99ec-dca5d5c070f0)
![image](https://github.com/user-attachments/assets/4e17ffbd-64ac-4d57-ae9c-6543ac82c2b7)

Trường hợp toa thuốc được cấp trước khi lập phiếu TT/PT thì ràng buộc 
Thời gian bắt đầu TT > ngày giờ chỉ định
thời gian kết thúc TT < giờ lập toa thuốc

đây là các trường hợp bị cổng giám định trả lỗi về > khuyến nghị thêm tham số chặn các trường hợp trên

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0715.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407150-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407150-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407150-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - khi lập toa thuốc với giờ lập nhỏ hơn thời gian kết thúc vẫn chưa có cảnh báo/chặn

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/269

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
đã chặn khi lập toa thuốc nhỏ hơn giờ kết thúc phiếu PT/TT
![image](https://github.com/user-attachments/assets/b7707445-a19b-4cf6-be45-0a2341f3e124)
![image](https://github.com/user-attachments/assets/ba430155-9765-4cac-b07f-b0fe56fe4c05)
