### ISSUE TITLE
Lỗi - In hồ sơ bệnh án ngoại trú thanh toán hàng ngày báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#27]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/9/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dalieu_phieuvaovien_bant`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022048934` - _**MaKB**_: `2209004555` - _**MaBA**_: `N2022000660` _**NgayKCB**_: `29/08/2022` - _**MaPhong**_: `36` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Đăng nhập ngày củ 29/8/2022 khi chọn in hồ sơ bệnh án ngoại trú thanh toán hàng ngày báo lỗi!

```
In HỒ SƠ báo lỗi
![image](https://user-images.githubusercontent.com/96155021/189808275-8899e006-e6ba-477f-bd8c-12a586102220.png)
đăng nhập ngày 12/9/2022 thì in bình thường
![image](https://user-images.githubusercontent.com/96155021/189808301-d338a7a4-efd8-4443-b0df-35657d977328.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.1012.1](http://www.fsend.vn/download/oMbnxCxS_ARcpA2B3mBxDmsBuIGFiyVt)

**Comment by le-an-87** [comment]
![image](https://user-images.githubusercontent.com/96155021/195482836-a24d8a5e-3a8d-401a-9c0f-8ec1ae2384b0.png)
vẫn còn lỗi anh ơi

**Comment by le-an-87** [comment]
đã fix!
