### ISSUE TITLE
Lỗi - Lỗi in bảng kê bệnh án ngoại trú thanh toán theo ngày (BV Bình Thủy)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#274]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_binhthuy_dakham_14072024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_binhthuy_dakham_14072024`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021000375` - _**MaKB**_: `2407004084` - _**MaBA**_: `N2021000344` _**NgayKCB**_: `11/07/2024` - _**MaPhong**_: `911` - _**MaDV**_: `01` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân ngoại trú thanh toán theo ngày:
Trường hợp đăng ký tái khám và thực hiện khám bệnh cho bệnh nhân xong (không thêm thuốc và cls) (khambenh.dakham=0)
=> in bảng kê bệnh nhân báo lỗi.

```
![ảnh](https://github.com/user-attachments/assets/92f47480-f59d-42e9-b24b-22fb02f3b585)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-17**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: Check xem trường hợp này, xem lỗi chỗ nào mà khám rồi, mà dakham = 0 nhé

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Lỗi in bảng kê bệnh án ngoại trú thanh toán theo ngày (BV Bình Thủy).
-  📆 **Thời gian hoàn thành :**  2024-07-17.

**Comment by minhduc2it** [comment]
@lequocthong29  xem luôn lỗi in 01 BANT 
Data: duc_thoilai_bant01
postgres port 5434

MABN: 2023020367  -  MAKB: 2406008794  -  MABA: 2023020367 - NGAYKB: 17/07/2024 - MADV: 10 - MAPHONG: 11

![image](https://github.com/user-attachments/assets/35dceeac-7c74-4842-a3d7-75d537fe4605)

Phiên bản :2024.07.25.155803PM
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at OTH.Adapter.HosBHXH.AGiamDinh.<>c__DisplayClass231_0.<createBangKeChiPhiFor>b__10(dmdonvi x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at OTH.Common.Lamdba.FirstOrNew[T](IEnumerable`1 items)
   at OTH.Adapter.HosBHXH.AGiamDinh.createBangKeChiPhiFor(v_CreateBangKeChiPhiFor v_CreateBangKeChiPhiFor)
   at OTH.Adapter.HosBHXH.AGiamDinh.CreateBangKeChiPhi(v_CreateBangKeChiPhiFor createBangKeChiPhiFor)
   at OTH.XForms.HosPrinter.BKChiPhiKCB6556.CreateDataSource()
   at HosPrinter.Classes.ClsHauThem.ExportXMLAndPrint6556(String xml_MaBN, String xml_MaKB, Form parentForm, GridEX dgCls, String strTKLapToa, String strTenPK, Int32 solanin, String strTKNhapBenh, GridEX dgThuoc, v_FormInPhieu01 vFormInPhieu01, String strTKLapToa_Manv_PhuongNam, QuayPhatThuoc quayPhatThuoc)
   at HosPrinter.Forms.FrmInPhieuKK.InMauBHYT01BV(String pThemoi)
   at HosPrinter.Forms.FrmInPhieuKK.btnIn_Click(Object sender, EventArgs e)

**Comment by ongtrieuhau-dh** [comment]
Xin dữ liệu link cái nhé @minhduc2it

**Comment by minhduc2it** [comment]
> Xin dữ liệu link cái nhé @minhduc2it 

Em gửi link data
https://gofile.me/78TQg/b0M55F4m8

**Comment by minhduc2it** [comment]
**Lỗi in 01 BN ARV** 
Data: duc_cairang_t7
postgres port 5434
Link tải dữ liệu: https://gofile.me/78TQg/t7dDzjvdd

MABN: 2020015941 - MAKB: 2407006098 - MABA: CTCRNK001081 - NGAYKB: 17/07/2024 - MADV: 01 - MAPHONG: 42

![image](https://github.com/user-attachments/assets/1ca65b88-6d41-4583-beec-19d3b6824bf8)

Phiên bản :2024.07.24.103716AM
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at OTH.Adapter.HosBHXH.AGiamDinh.createBangKeChiPhiFor(v_CreateBangKeChiPhiFor v_CreateBangKeChiPhiFor)
   at OTH.Adapter.HosBHXH.AGiamDinh.CreateBangKeChiPhi(v_CreateBangKeChiPhiFor createBangKeChiPhiFor)
   at OTH.XForms.HosPrinter.BKChiPhiKCB6556.CreateDataSource()
   at HosPrinter.Classes.ClsHauThem.ExportXMLAndPrint6556(String xml_MaBN, String xml_MaKB, Form parentForm, GridEX dgCls, String strTKLapToa, String strTenPK, Int32 solanin, String strTKNhapBenh, GridEX dgThuoc, v_FormInPhieu01 vFormInPhieu01, String strTKLapToa_Manv_PhuongNam, QuayPhatThuoc quayPhatThuoc)
   at HosPrinter.Forms.FrmInPhieuKK.InMauBHYT01BV(String pThemoi)
   at HosPrinter.Forms.FrmInPhieuKK.btnIn_Click(Object sender, EventArgs e)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0726.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407261-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407261-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407261-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - Lỗi in bảng kê bệnh án ngoại trú thanh toán theo ngày

- ![](https://i.imgur.com/FxPDEYR.png)

![](https://i.imgur.com/kKKMvxe.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/274

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0726.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407262-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407262-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407262-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Không cho phép in phiếu 01 đối với bệnh án ngoại trú thanh toán đợt (Có check [`Theo Đợt`]), phải vào chức năng Tổng kết CP thực hiện,

- ![](https://i.imgur.com/wcKWDhT.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/274#issuecomment-2249843169

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
này là sao anh @ongtrieuhau 
![ảnh](https://github.com/user-attachments/assets/342e8c20-3996-441b-b78a-d7b5e6ba215f)

**Comment by le-an-87** [comment]
Giờ bệnh án ngoại trú phải thao tác thế nào thì mới khám rồi?
mới in được bảng kê anh.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0726.4 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407264-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407264-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407264-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Lỗi in bảng kê bệnh án ngoại trú thanh toán theo ngày (Cảnh báo chưa phát sinh chi phí khi in phiếu 01)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/274

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @le-an-87 , @nghivanbi

**Comment by le-an-87** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '20/08/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ TEST**
***
> Hình ảnh Phiếu 01, 02, xuất XML.
![ảnh](https://github.com/user-attachments/assets/e3ce35f6-f0e1-42c1-bdb8-aeb7a6713ab1)

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/37976232-b052-4d49-a658-5a1432d72785)
![ảnh](https://github.com/user-attachments/assets/91741b0e-0db5-49e7-813f-c0ece377cf7f)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.

**Comment by le-an-87** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Phân công kiểm tra: @minhduc2it Kiểm tra lại vấn đề em báo nhé.
- Kết quả hoàn thành thì close issuse.
***
- Ghi nhận hạn hoàn thành và kết quả kiểm tra:
 1. Ghi nhận hạn hoàn thành dự kiến.
 2. Ghi nhận kết quả kiểm tra.

**Comment by minhduc2it** [comment]
https://github.com/dh-hos/dhg.hospitalprescription/issues/274#issuecomment-2251933713

**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Đã kiểm tra in được phiếu 01

![image](https://github.com/user-attachments/assets/f11a8496-45ec-4bac-a670-deee6eaa0229)

**Comment by minhduc2it** [comment]
https://github.com/dh-hos/dhg.hospitalprescription/issues/274#issuecomment-2249843169

**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Đã kiểm tra in được phiếu 01
![image](https://github.com/user-attachments/assets/c90d01e9-3363-460a-8685-afcb5a6508f6)
