### ISSUE TITLE
Lỗi - Lỗi in phiếu 01KCB tại Prscription 

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprescription#275]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87114`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Phổi Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphoidt_01kcbloi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/FuEuqBqKb)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022000454` - _**MaKB**_: `2407001103` - _**MaBA**_: `MaBA` _**NgayKCB**_: `15/07/2024` - _**MaPhong**_: `01` - _**MaDV**_: `01` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

Khi in phiếu 01KCB tại Prescription chọn máy in xuất hiện lỗi như hình dưới
![image](https://github.com/user-attachments/assets/494f3eb3-a9af-4184-8ca8-180ce0562ab9)

Chi tiết lỗi:
Phiên bản :2024.07.12.083442AM
System.Exception: Lỗi xảy ra tại [Name:Void OTH.Adapter.HosBHXH.AGiamDinh.Print01Finished(),Assembly:OTH.Adapter.dll,Version: Version=1.24.711.2]. ---> System.Exception: Lỗi xảy ra tại [Name:Void OTH.Adapter.HosBHXH.AGiamDinh.SaveXML130(),Assembly:OTH.Adapter.dll,Version: Version=1.24.711.2]. ---> System.Exception: Lỗi code [OTH.ClsPostgres.CmdPgSQL.ExecuteSQL].
[{"[Name]":"sSQL","[Type]":"System.String","[Value]":" UPDATE xml130.psxml SET  ma_lk=\u002787115_2024_07_2022000454_2407001103\u0027 , ngay_ttoan=\u00272024-07-15 08:27:00.000000\u0027 , thang_qt=\u002707\u0027 , nam_qt=\u00272024\u0027  WHERE  COALESCE(mabn,\u0027\u0027)  =  \u00272022000454\u0027   AND  COALESCE(makb,\u0027\u0027)  =  \u00272407001103\u0027   AND  COALESCE(maba,\u0027\u0027)  =  \u0027\u0027   AND  COALESCE(mabattconbh2,\u0027\u0027)  =  \u0027\u0027   AND  COALESCE(loaihosokcb,\u0027\u0027)  =  \u0027NGOAI_TRU\u0027 ; DELETE FROM xml130.bang1 WHERE  COALESCE(ma_lk,\u0027\u0027)  =  \u002787115_2024_07_2022000454_2407001103\u0027 ; INSERT INTO xml130.bang1(ma_lk,stt,ma_bn,ho_ten,so_cccd,ngay_sinh,gioi_tinh,ma_quoctich,ma_dantoc,ma_nghe_nghiep,dia_chi,matinh_cu_tru,mahuyen_cu_tru,maxa_cu_tru,dien_thoai,ma_the_bhyt,ma_dkbd,gt_the_tu,gt_the_den,ngay_mien_cct,ly_do_vv,ly_do_vnt,ma_ly_do_vnt,chan_doan_vao,chan_doan_rv,ma_benh_chinh,ma_benh_kt,ma_benh_yhct,ma_pttt_qt,ma_doituong_kcb,ma_noi_di,ma_noi_den,ma_tai_nan,ngay_vao,ngay_vao_noi_tru,ngay_ra,giay_chuyen_tuyen,so_ngay_dtri,pp_dieu_tri,ket_qua_dtri,ma_loai_rv,ghi_chu,ngay_ttoan,t_thuoc,t_vtyt,t_tongchi_bv,t_tongchi_bh,t_bntt,t_bncct,t_bhtt,t_nguonkhac,t_bhtt_gdv,nam_qt,thang_qt,ma_loai_kcb,ma_khoa,ma_cskcb,ma_khuvuc,can_nang,can_nang_con,nam_nam_lien_tuc,ngay_tai_kham,ma_hsba,ma_ttdv,du_phong,nhom_mau,makb,version) VALUES ( \u002787115_2024_07_2022000454_2407001103\u0027 , 1 , \u00272022000454\u0027 , \u0027\u003c![CDATA[Trần Thị Cẩm Thu]]\u003e\u0027 , \u0027087304013811\u0027 , \u0027200404150000\u0027 , 2 , \u0027000\u0027 , \u002756\u0027 , \u002700000\u0027 , \u0027\u003c![CDATA[Tổ 27 Khóm 3, Phường 6, Thành phố Cao Lãnh, Tỉnh Đồng Tháp]]\u003e\u0027 , \u002787\u0027 , \u0027866\u0027 , \u002729878\u0027 , \u00270762425287\u0027 , \u0027GD4878723891760\u0027 , \u002787012\u0027 , \u002720240623\u0027 , \u002720250622\u0027 , \u0027\u0027 , \u0027\u003c![CDATA[Viêm phổi, tác nhân không xác định;Di chứng do lao kháng thuốc;Xẹp phổi(T);Các bệnh phổi tắc nghẽn mãn tính khác;Thiếu kẽm do chế độ ăn]]\u003e\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027Viêm phổi, tác nhân không xác định;Di chứng do lao kháng thuốc;Xẹp phổi(T);Các bệnh phổi tắc nghẽn mãn tính khác;Thiếu kẽm do chế độ ăn\u0027 , \u0027\u003c![CDATA[Viêm phổi, tác nhân không xác định;Di chứng do lao kháng thuốc;Xẹp phổi(T);Các bệnh phổi tắc nghẽn mãn tính khác;Thiếu kẽm do chế độ ăn]]\u003e\u0027 , \u0027J18\u0027 , \u0027J44;J98.1;E60;B90\u0027 , \u0027\u0027 , \u0027\u0027 , \u00279\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027202407150822\u0027 , \u0027\u0027 , \u0027202407150827\u0027 , \u00272407001103\u0027 , \u00270\u0027 , \u0027\u0027 , \u00277\u0027 , \u00271\u0027 , \u0027\u0027 , \u0027202407150827\u0027 , \u002713020.00\u0027 , 0 , 50520.00 , 50520.00 , 0.00 , 0.00 , 50520.00 , 0 , 0 , \u00272024\u0027 , \u002707\u0027 , \u002701\u0027 , \u0027K0102\u0027 , \u002787115\u0027 , \u0027\u0027 , \u00270.00\u0027 , \u0027\u0027 , \u002720270623\u0027 , \u002720240812\u0027 , \u00272407001103\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u00272407001103\u0027 , \u00271.24.0711.2\u0027 ); DELETE FROM xml130.bang2 WHERE  COALESCE(MA_LK,\u0027\u0027)  =  \u002787115_2024_07_2022000454_2407001103\u0027 ; INSERT INTO xml130.bang2(ma_lk,stt,ma_thuoc,ma_pp_chebien,ma_cskcb_thuoc,ma_nhom,ten_thuoc,don_vi_tinh,ham_luong,duong_dung,dang_bao_che,lieu_dung,cach_dung,so_dang_ky,tt_thau,pham_vi,tyle_tt_bh,so_luong,don_gia,thanh_tien_bv,thanh_tien_bh,t_nguonkhac_nsnn,t_nguonkhac_vtnn,t_nguonkhac_vttn,t_nguonkhac_cl,t_nguonkhac,muc_huong,t_bntt,t_bncct,t_bhtt,ma_khoa,ma_bac_si,ma_dich_vu,ngay_yl,ma_pttt,nguon_ctra,vet_thuong_tp,du_phong,ngay_th_yl,mabn,makb,mahh,sohd) VALUES ( \u002787115_2024_07_2022000454_2407001103\u0027 , 1 , \u002740.725\u0027 , \u0027\u0027 , \u0027\u0027 , \u00274\u0027 , \u0027\u003c![CDATA[Zinc 10]]\u003e\u0027 , \u0027viên\u0027 , \u0027\u003c![CDATA[70mg]]\u003e\u0027 , \u00271.01\u0027 , \u0027Viên nén\t\u0027 , \u0027.\u0027 , \u0027Uống 1 viên buổi sáng\u0027 , \u0027VD-22801-15\u0027 , \u0027965/QĐ-SYT;G1;N4;2023\u0027 , 1 , \u0027100\u0027 , 28.00 , 145.000 , 4060.00 , 4060.00 , 0 , 0 , 0 , 0 , 0 , 100 , 0.00 , 0.00 , 4060.00 , \u0027K0102\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027202407150826\u0027 , \u00271\u0027 , \u00271\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u00272022000454\u0027 , \u00272407001103\u0027 , \u0027ZI05\u0027 , \u0027K20.00001/202407\u0027 ); INSERT INTO xml130.bang2(ma_lk,stt,ma_thuoc,ma_pp_chebien,ma_cskcb_thuoc,ma_nhom,ten_thuoc,don_vi_tinh,ham_luong,duong_dung,dang_bao_che,lieu_dung,cach_dung,so_dang_ky,tt_thau,pham_vi,tyle_tt_bh,so_luong,don_gia,thanh_tien_bv,thanh_tien_bh,t_nguonkhac_nsnn,t_nguonkhac_vtnn,t_nguonkhac_vttn,t_nguonkhac_cl,t_nguonkhac,muc_huong,t_bntt,t_bncct,t_bhtt,ma_khoa,ma_bac_si,ma_dich_vu,ngay_yl,ma_pttt,nguon_ctra,vet_thuong_tp,du_phong,ngay_th_yl,mabn,makb,mahh,sohd) VALUES ( \u002787115_2024_07_2022000454_2407001103\u0027 , 2 , \u002740.972\u0027 , \u0027\u0027 , \u0027\u0027 , \u00274\u0027 , \u0027\u003c![CDATA[Baburol]]\u003e\u0027 , \u0027viên\u0027 , \u0027\u003c![CDATA[10mg]]\u003e\u0027 , \u00271.01\u0027 , \u0027Viên nén\t\u0027 , \u0027.\u0027 , \u0027ngày uống 1 viên tối\u0027 , \u0027VD-24113-16\u0027 , \u0027965/QĐ-SYT;G1;N4;2023\u0027 , 1 , \u0027100\u0027 , 28.00 , 320.000 , 8960.00 , 8960.00 , 0 , 0 , 0 , 0 , 0 , 100 , 0.00 , 0.00 , 8960.00 , \u0027K0102\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027202407150826\u0027 , \u00271\u0027 , \u00271\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u00272022000454\u0027 , \u00272407001103\u0027 , \u0027BA48\u0027 , \u0027K20.00001/202407\u0027 ); DELETE FROM xml130.bang3 WHERE  COALESCE(MA_LK,\u0027\u0027)  =  \u002787115_2024_07_2022000454_2407001103\u0027 ; INSERT INTO xml130.bang3(ma_lk,stt,ma_dich_vu,ma_pttt_qt,ma_vat_tu,ma_nhom,goi_vtyt,ten_vat_tu,ten_dich_vu,ma_xang_dau,don_vi_tinh,pham_vi,so_luong,don_gia_bv,don_gia_bh,tt_thau,tyle_tt_dv,tyle_tt_bh,thanh_tien_bv,thanh_tien_bh,t_trantt,muc_huong,t_nguonkhac_nsnn,t_nguonkhac_vtnn,t_nguonkhac_vttn,t_nguonkhac_cl,t_nguonkhac,t_bntt,t_bncct,t_bhtt,ma_khoa,ma_giuong,ma_bac_si,nguoi_thuc_hien,ma_benh,ma_benh_yhct,ngay_yl,ngay_th_yl,ngay_kq,ma_pttt,vet_thuong_tp,pp_vo_cam,vi_tri_th_dvkt,ma_may,ma_hieu_sp,tai_su_dung,du_phong,mabn,makb,mahh,sohd,macls,ngaykcb) VALUES ( \u002787115_2024_07_2022000454_2407001103\u0027 , 1 , \u002702.1897\u0027 , \u0027\u0027 , \u0027\u0027 , \u002713\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u003c![CDATA[Khám Nội]]\u003e\u0027 , \u0027\u0027 , \u0027Lần\u0027 , 1 , 1.00 , 37500.00 , 37500.00 , \u0027\u0027 , \u0027100\u0027 , \u0027100\u0027 , 37500.00 , 37500.00 , \u0027\u0027 , 100 , 0 , 0 , 0 , 0 , 0 , 0.00 , 0.00 , 37500.00 , \u0027K0102\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027J18;B90;J98.1;J44;E60\u0027 , \u0027\u0027 , \u0027202407150824\u0027 , \u0027\u0027 , \u0027\u0027 , \u00271\u0027 , \u0027\u0027 , \u00274\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u00272022000454\u0027 , \u00272407001103\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027KH01\u0027 ,  CAST(TO_TIMESTAMP(\u002715/07/2024 08:24:17\u0027,\u0027DD/MM/YYYY HH24:MI:SS\u0027) AS TIMESTAMP WITHOUT TIME ZONE)  ); DELETE FROM xml130.bang5 WHERE  COALESCE(MA_LK,\u0027\u0027)  =  \u002787115_2024_07_2022000454_2407001103\u0027 ; INSERT INTO xml130.bang5(ma_lk,stt,dien_bien_ls,giai_doan_benh,hoi_chan,phau_thuat,thoi_diem_dbls,nguoi_thuc_hien,du_phong,mabn,makb) VALUES ( \u002787115_2024_07_2022000454_2407001103\u0027 , \u00271\u0027 , \u0027\u003c![CDATA[CSST\u003cHA(/)\u003e]]\u003e\u0027 , \u0027\u0027 , \u0027\u003c![CDATA[]]\u003e\u0027 , \u0027\u003c![CDATA[]]\u003e\u0027 , \u0027202407150824\u0027 , \u0027\u0027 , \u0027\u0027 , \u00272022000454\u0027 , \u00272407001103\u0027 ); DELETE FROM xml130.bang7 WHERE  COALESCE(ma_lk,\u0027\u0027)  =  \u002787115_2024_07_2022000454_2407001103\u0027 ; INSERT INTO xml130.bang7(ma_lk,so_luu_tru,ma_yte,ma_khoa_rv,ngay_vao,ngay_ra,ma_dinh_chi_thai,nguyennhan_dinhchi,thoigian_dinhchi,tuoi_thai,chan_doan_rv,pp_dieutri,ghi_chu,ma_ttdv,ma_bs,ten_bs,ngay_ct,ma_cha,ma_me,ma_the_tam,ho_ten_cha,ho_ten_me,so_ngay_nghi,ngoaitru_tungay,ngoaitru_denngay,du_phong,mabn,makb) VALUES ( \u002787115_2024_07_2022000454_2407001103\u0027 , \u00272407001103\u0027 , \u00272022000454\u0027 , \u0027K0102\u0027 , \u0027202407150822\u0027 , \u0027202407150827\u0027 , \u00270\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027Viêm phổi, tác nhân không xác định;Di chứng do lao kháng thuốc;Xẹp phổi(T);Các bệnh phổi tắc nghẽn mãn tính khác;Thiếu kẽm do chế độ ăn\u0027 , \u0027Ngoại khoa\u0027 , \u0027\u0027 , \u0027\u0027 , NULL , \u0027 \u0027 , \u002720240715\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027Trần Văn Chông\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u0027\u0027 , \u00272022000454\u0027 , \u00272407001103\u0027 );"},{"[Name]":"htPara","[Type]":"System.Collections.Hashtable","[Value]":"NULL"}]
 ---> Npgsql.NpgsqlException: ERROR: 23502: null value in column "ma_bs" violates not-null constraint
   at OTH.ClsPostgres.CmdPgSQLConn.ExecuteSQL(String sSQL, NpgsqlConnection pConn, Hashtable htPara)
   at OTH.ClsPostgres.CmdPgSQL.ExecuteSQL(String sSQL, Hashtable htPara)
   --- End of inner exception stack trace ---
   at OTH.ClsPostgres.CmdPgSQL.ExecuteSQL(String sSQL, Hashtable htPara)
   at OTH.Adapter.HosBHXH.AGiamDinh.SaveXML130()
   --- End of inner exception stack trace ---
   at OTH.Adapter.HosBHXH.AGiamDinh.SaveXML130()
   at OTH.Adapter.HosBHXH.AGiamDinh.Print01Finished()
   --- End of inner exception stack trace ---
   at OTH.Adapter.HosBHXH.AGiamDinh.Print01Finished()
   at OTH.XForms.HosPrinter.BKChiPhiKCB6556.PrintFinish(Boolean IsUpdateChandoanXml)
   at OTH.XForms.HosPrinter.BKChiPhiKCB6556.PrintByOption(Form parentForm, Boolean IsUpdateChandoanXml, Int16 forceCopies)
   at HosPrinter.Classes.ClsHauThem.ExportXMLAndPrint6556(String xml_MaBN, String xml_MaKB, Form parentForm, GridEX dgCls, String strTKLapToa, String strTenPK, Int32 solanin, String strTKNhapBenh, GridEX dgThuoc, v_FormInPhieu01 vFormInPhieu01, String strTKLapToa_Manv_PhuongNam, QuayPhatThuoc quayPhatThuoc)
   at HosPrinter.Forms.FrmInPhieuKK.InMauBHYT01BV(String pThemoi)
   at HosPrinter.Forms.FrmInPhieuKK.btnIn_Click(Object sender, EventArgs e)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Fix lỗi - in phiếu 01KCB tại Prscription.
-  📆 **Thời gian hoàn thành :**  2024-07-19.

**Comment by lequocthong29** [comment]
Cập nhật cấu trúc rồi thử lại nha a @hvtuan1987 
![image](https://github.com/user-attachments/assets/c634b5fa-3836-44e9-acb9-e6fcaec34ce9)

**Comment by hvtuan1987** [comment]
Đã in được !
![image](https://github.com/user-attachments/assets/12094435-45cc-4ad5-b8fd-d08c3e55d315)
