### ISSUE TITLE
Lỗi - Lấy chỉ số sinh hiêu sai khi chuyển phòng

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#276]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/027/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbthanhtri_052024042024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/455On1zg3)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024005990` - _**MaKB**_: `2406000014` - _**MaBA**_: `MaBA` _**NgayKCB**_: `15/07/2024` - _**MaPhong**_: `17 và 01` - _**MaDV**_: `10` - _**ThangKT**_: `06` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Như BN dưới đây, đk khám Phòng 17, sau đó chuyển phòng 01. thì chỉ số sinh hiệu nó lóa bị sai, nó load sinh hiệu của BN nào khám trước đó đó.

![image](https://github.com/user-attachments/assets/923e63d4-1d12-4869-b4e3-21b405efdde7)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Fix lỗi - Lấy chỉ số sinh hiêu sai khi chuyển phòng.
-  📆 **Thời gian hoàn thành :**  2024-07-19.

**Comment by lequocthong29** [comment]
@lqbinh1987 test lại với bản cập nhật mới nhất xem còn lỗi không a, hiện tại e test không thấy phát sinh lỗi 
![image](https://github.com/user-attachments/assets/1d47869a-a995-4003-9741-b7aa5befa216)

**Comment by lqbinh1987** [comment]
Bản mới không còn trình trạng này nữa.
![image](https://github.com/user-attachments/assets/db20d080-4afb-40a6-a531-11fad54595de)
