### ISSUE TITLE
Lỗi - Test - Nhận bệnh trên Prescription không bắt thiếu Trạng thái Chuyển tuyến

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprescription#277]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92137`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Ninh Kiều**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_ninhkieu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/QV2ZBm9hv

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000194` - _**MaKB**_: `2407000056` - **NgayKCB**_: `16/07/2024` - _**MaPhong**_: `06` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

**1. Nhận bệnh trên Prescription không bắt nhập thiếu Trạng thái Chuyển tuyến**

![image](https://github.com/user-attachments/assets/c702ad6a-5564-4476-9478-45357c49380c)

![image](https://github.com/user-attachments/assets/69588616-59d4-4f0b-b8e6-3a77b6e9b161)

**2. Chẩn đoán Chuyển tuyến:**
 **- Tên bệnh bị lặp lại**
 
![image](https://github.com/user-attachments/assets/81bc61a8-2f28-4fc9-b4dd-f0a2f2e75673)

**- Tên bệnh cũ không xóa**
![image](https://github.com/user-attachments/assets/2edb8da5-111d-4950-a681-9bdf70a77765)

**Comment by minhduc2it** [comment]
P/S: **- Tên Bệnh bị lặp lại**
Tại ô Chẩn đoán chuyển tuyến bấm F2 > lên Danh mục ICD > chọn ICD từ danh mục sẽ bị lặp lại tên Chẩn đoán

![image](https://github.com/user-attachments/assets/9f526ffc-5c93-4b1d-b7c2-a1ba68d478ad)

![image](https://github.com/user-attachments/assets/c92bea80-b721-4e9d-9a1c-7a8320e48aac)

_Nếu gõ trực tiếp mã ICD vào ô Chẩn đoán thì không bị lặp lại chẩn đoán_

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-18**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Fix lỗi - Nhận bệnh trên Prescription không bắt thiếu Trạng thái Chuyển tuyến.
-  📆 **Thời gian hoàn thành :**  2024-07-18.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0718.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407181-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407181-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407181-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - BANT Chuyển phòng - chưa cập nhật được bnnoitru.madv khi chuyển phòng

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/483

- 🐛: Fix - Nhận bệnh trên Prescription không bắt thiếu Trạng thái Chuyển tuyến

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/277

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
1. Lỗi Bắt nhập thiếu Trạng thái chuyển tuyến
2. Chẩn đoán chuyển tuyến: Tên bệnh bị lặp lại
    Hai lỗi trên đã kiểm tra thành công

![image](https://github.com/user-attachments/assets/5fe4d590-b537-464f-aab0-57662c46483f)

**Comment by minhduc2it** [comment]
P/s: Số chuyển và Điều trị từ ... đến ngày ... nếu nhập thiếu thông tin Có cảnh báo bắt nhập
(Đảm bảo dữ liệu chuyển tuyến được nhập đầy đủ)
[ Yêu cầu bắt thêm như bên Register](https://github.com/dh-hos/dhg.hospitalregister/issues/74#issuecomment-2237857434)

![image](https://github.com/user-attachments/assets/3e3fa443-bdc9-4830-bed3-9724dc4f05ad)

**Comment by lequocthong29** [comment]
@minhduc2it Test lại trên bản Prescription mới nhất nha a

**Comment by minhduc2it** [comment]
Đã Kiểm tra thành công

![image](https://github.com/user-attachments/assets/12dc9896-5719-4b4a-a41c-5b1971955c00)

![image](https://github.com/user-attachments/assets/79ef60c0-ecfc-4be6-b051-f72a9462de99)

![image](https://github.com/user-attachments/assets/e4977382-a562-4872-9ff7-38d5ff2a144b)

Các chức năng khác chưa ghi nhận bất thường: Đăng ký, khám bệnh, in phiếu 01
