### ISSUE TITLE
Lỗi - nhập mã icd chẩn đoán phụ nhưng Prescription không lấy tên chẩn đoán phụ

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#28]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_medic123_r05`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022012528` - _**MaKB**_: `2209001788` - _**NgayKCB**_: `14/09/2022` - _**MaPhong**_: `P22` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2022`_**MA_ICD**_: `R05`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi cho chẩn đoán phụ:
chẩn đoán thứ nhất R42 + chẩn đoán thứ 2 R05 thì phần mềm không lấy được tên chẩn đoán phụ R05!

```
cho chẩn đoán R05 trước R42
![image](https://user-images.githubusercontent.com/96155021/190085443-6de77983-3350-46b4-966d-44fd942b098d.png)
cho chẩn đoán R42 trước R05 thì mất tên chẩn đoán R05
![image](https://user-images.githubusercontent.com/96155021/190085589-78dd44af-4c6f-48d2-8849-d6a2ab6ac268.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: v3.22.1012.1

**Comment by le-an-87** [comment]
đã fix!
