### ISSUE TITLE
Lỗi - BANT không load được thông tin phiếu thủ thuật đã lập (BV Ung Bướu)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#283]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_thuthuat_bant_24072024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_ungbuou_thuthuat_bant_24072024`](https://gofile.me/78TQg/4S80OpIZw)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024007512` - _**MaKB**_: `2407003589` - _**MaBA**_: `N2024007693` _**NgayKCB**_: `08/072024` - _**MaPhong**_: `NO03` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `CH620` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân bệnh án ngoại trú không load được thông tin phiếu thủ thuật đã lập.

```
![ảnh](https://github.com/user-attachments/assets/15316264-0d58-4674-ae76-8a5d78efb5e8)
![ảnh](https://github.com/user-attachments/assets/af33247c-b9d0-4cfd-b443-5b6da040e5df)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-26**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Fix Lỗi - BANT không load được thông tin phiếu thủ thuật đã lập (BV Ung Bướu).
-  📆 **Thời gian hoàn thành :**  2024-07-26.

**Comment by lequocthong29** [comment]
- Kiểm tra dữ liệu nhận thấy chưa lập phiếu thủ thuật nên chưa có thông tin để lấy
![image](https://github.com/user-attachments/assets/1432e48b-a1ca-42a5-8738-1df1015fb8b8).
- Test thử một ca mới cho ra kết quả bình thường
![image](https://github.com/user-attachments/assets/6cb5e2a1-78ad-40ae-9f13-08fa5ccbe6b8)

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @le-an-87 @nghivanbi

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
1. Vấn đề 1: phiếu thủ thuật đã lập rồi hay chưa?
 - BV đã chụp hình phiếu thủ thuật đã lập và in kèm theo.
 - Dữ liệu table phẫu thuật vẫn có.
 -> Tổ lập trình trả lời chưa lập phiếu là không đúng.
***

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Khách hàng đã xử lý xong trường hợp lỗi trên.
***
- Tiến hành hỗ trợ khách hàng.

**Comment by nghivanbi** [comment]
> ### **Trả lời vướng mắc**
> 1. Vấn đề 1: phiếu thủ thuật đã lập rồi hay chưa?
> 
> * BV đã chụp hình phiếu thủ thuật đã lập và in kèm theo.
> * Dữ liệu table phẫu thuật vẫn có.
>   -> Tổ lập trình trả lời chưa lập phiếu là không đúng.

Để tránh lặp lại trường hợp này thì yêu cầu giải pháp gì không @le-an-87, @ongtrieuhau

**Comment by ongtrieuhau-dh** [comment]
#### 📢 @nghivanbi 
- Vấn đề là cả 2 tổ hông tổ nào tìm được nguyên nhân gây lỗi. Bản mới nhất đã không còn, thì theo dõi tiếp thôi.
