### ISSUE TITLE
Lỗi - Chọn ngày bắt đầu hẹn tái khám là ngày khám bệnh

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#291]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbthanhtri_ngayhen_kl`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/p5dpACfKS)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Tại form ra toa thuốc, khi BS chọn ngày tái khám là ngày khám bệnh phần mềm vẫn cho lưu(lưu ý là chổ form chẩn đoán thì không chọn được ngày hẹn là ngày khám bệnh, chỉ được chọn ngày hẹn lớn hơn ngày khám), dữ liệu sẽ lưu vào psdangky.ngaytaikham = ngày khám bệnh lun => **xuất XML gửi cổng báo lỗi Ngày hẹn phải lớn hơn ngày khám bệnh.**

![image](https://github.com/user-attachments/assets/fc0ca205-5c71-4beb-9fa8-5ee984784888)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Fix Lỗi - Chọn ngày bắt đầu hẹn tái khám là ngày khám bệnh.
-  📆 **Thời gian hoàn thành :**  2024-08-06.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0806.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408061-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408061-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408061-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: fix lỗi cho lưu toa thuốc khi ngày tái khám trùng với ngày khám bệnh

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/291

![](https://i.imgur.com/QehOWEp.png)

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
Khi thêm toa lần đầu đã bắt được ngày hẹn, nhưng lưu xong, bấm Chỉnh lại thì ko bắt được, vãn cho lưu nếu ngày hẹn = ngày khám, và chọn lại thì không thấy ngày hẹn được nữa

https://github.com/user-attachments/assets/42b64c33-3892-43ed-a104-198ca27c1b36

**Comment by nqhoa1005** [comment]
Đề nghị điều chỉnh như sau :
XML14 không cho bỏ trống trường ngày hẹn
Quá trình test lại Form chỉ bắt được không chọn ngày nhỏ hơn hoặc bằng ngày hiện tại

Xử lý thêm các vấn đề sau :
1. không cho bỏ trống trường ngày hẹn (theo tham số hentaikham thì chỉ hỗ trợ set sẳn theo ngày toa thuốc) > bản 04/08 vẫn cho phép bỏ trống.
2. Ngày hẹn tại form chẩn đoán đồng bộ với ngày hẹn tại form toa thuốc, nếu dữ liệu không lưu tại psdangky.ngaytaikham
Clip test
https://github.com/user-attachments/assets/e7bf41b0-2995-4fd9-acc0-e7dfdfdac527

**Comment by nqhoa1005** [comment]
Chức năng ngày hẹn tái khám có liên quan tới hệ thống SMS 
Check thêm về việc ảnh hưởng đế SMS

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0809.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408090-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408090-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408090-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - ràng buộc ngày tái khám phải lớn hơn ngày ra toa

- 🐛: Fix - khi nhập ngày uống trên toa thuốc, ấn Enter thì tự động gợi ý ngày tái khám

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/291

![](https://i.imgur.com/GG1Hq4T.png)

![](https://i.imgur.com/ZNEYMNP.png)

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
Đã hỗ trợ lấy ngày tái khám đúng theo thao tác nhập số ngày uống > Enter
và nếu thay đổi giá trị ở trường hẹn tái khám thì ngày hẹn cũng update theo
![image](https://github.com/user-attachments/assets/56d4c768-7d2e-47ff-93b0-e71f9a056dd5)

Đã ràng buộc ngày tái khám phải lớn hơn ngày ra toa thuốc 
![image](https://github.com/user-attachments/assets/b25d5115-4336-4711-8645-7a1e99cfbde6)

**Comment by nqhoa1005** [comment]
Đồng thời test trường hợp nếu khám 2 phòng thì psdangky.ngaytaikham sẽ lưu theo giá trị ngày hẹn của phòng sau cùng.
![image](https://github.com/user-attachments/assets/2502200e-68f3-460b-a539-9ab2aa766d4c)

Đồng thời nếu tại phòng sau cùng xoá toa thuốc thì không update lại psdangky.ngaytaikham
![image](https://github.com/user-attachments/assets/9e04d4d0-b7d7-4d85-b32f-56613db9db52)
![image](https://github.com/user-attachments/assets/7fa97ed4-21cd-43c9-ab17-92382bb17b02)

và khi Bs phòng đầu khám vào in giấy hẹn tái khám sẽ lấy giá trị ngày tái khám đã set lại của phòng sau cùng
![image](https://github.com/user-attachments/assets/9e9c3aee-f768-482e-8bd6-a128a7e1f220)

Quá trình test cũng phát hiện thêm nếu BN chuyển phòng thì chỉ số sinh hiệu không lấy lại theo phòng đầu @lequocthong29 check dùm nhé
![image](https://github.com/user-attachments/assets/7fdb73a1-3e1c-499f-b802-8c93fd6f5f1b)
![image](https://github.com/user-attachments/assets/70747e9c-ca41-4905-9b3f-f564807fa5bc)




anh @nghivanbi anh @ongtrieuhau xem xét qui trình này dùm em nếu đồng ý theo chổ này thì em đóng Git

**Comment by lqbinh1987** [comment]
Lỗi chỉ số sinh hiệu thì lập GIT khác.
Còn trường hợp này xem dùm em anh @nghivanbi, phát sinh trường hợp BN khám 2 phòng như @nqhoa1005 báo.

**Comment by ongtrieuhau-dh** [comment]
## 📣📣❓❓XÁC NHẬN MÔ TẢ CHỨC NĂNG MỚI, CHỈNH LỖI

- 📘 Nhờ GĐ: @nghivanbi **_xem xét, góp ý luồng mô tả này_**
- 📙 Nhờ TT.HT, TT.TK: @le-an-87, @lqbinh1987 **_xem xét, góp ý luồng mô tả này_**
- 📄 Thông tin kèm theo **Trường hợp người dùng đã chọn ngày tái khám, nếu trong psdangky chưa ghi nhận thông tin này, thì sẽ cập nhật vào psdangky, ngược lại, nếu có rồi thì  cảnh báo để người dùng quyết định là chọn ngày nào làm ngày tái khám. Cái này không phân biệt phòng hay 1 phòng nhiều toa (nếu có rồi, thì cảnh báo để người dùng xác nhận, thì cập nhật lại)**
- 📢 Lưu ý: **_sau 2 giờ không phản hồi xem Tổ CODE sẽ thực hiện theo luồng mô tả_**

**Comment by nghivanbi** [comment]
### 💡 MÔ TẢ THỰC HIỆN 💡
📣 **Phân công thực hiện**: @ongtrieuhau
- Mô tả việc ghi nhận ngày hẹn tách bạch không phụ thuộc vào toa, ghi nhận bổ sung thêm tài khoản bác sĩ hẹn. Kiểm tra, xác nhận và ghi nhật ký trường hợp phòng khám sau đổi ngày hẹn.

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-20**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-08-20.

**Comment by lequocthong29** [comment]
[Mô tả ghi nhận ngày hẹn tái khám](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/Thong-mo-ta-ghi-nhan-ngay-hen-kham-lai.md)

**Comment by ongtrieuhau-dh** [comment]
## 📣📣❓❓XÁC NHẬN MÔ TẢ CHỨC NĂNG MỚI, CHỈNH LỖI

- 📘 Nhờ GĐ: @nghivanbi **_xem xét, góp ý luồng mô tả này_**
- 📙 Nhờ TT.HT, TT.TK: @le-an-87, @lqbinh1987 **_xem xét, góp ý luồng mô tả này_**
- 📄 Thông tin kèm theo **__**
- 📢 Lưu ý: **_sau 2 giờ không phản hồi xem Tổ CODE sẽ thực hiện theo luồng mô tả_**

**Comment by lqbinh1987** [comment]
![image](https://github.com/user-attachments/assets/071f3ec5-1380-4d5d-8c7a-3ad445179a89)
Nếu BV đang xài tham số này thì sao anh? Khi đánh số ngày uống của toa thì chổ phiếu hẹn nó cũng load theo ngày trong form ra toa, do phần mềm tự đông lưu ngày tái khám vào psdangky.ngaytaikham, lúc này người dùng không cần Chỉnh diễn biến để cập nhật ngày hẹn nữa, thì phần mềm sẽ kiểm soát thế nào?
**hentaikham**: Hỗ trợ ghi ngày tái khám trên toa thuốc (mặc định 0: tự nhập ; 1: hỗ trợ lấy theo ngày uống)
![image](https://github.com/user-attachments/assets/ade96e66-d951-47f7-9ddb-264af931a870)

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: Mô tả thêm luồng chức năng này nhé

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
[Mô tả ghi nhập ngày hẹn tái khám](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/Thong-mo-ta-ghi-nhan-ngay-hen-kham-lai.md)
- Cập nhật trường hợp có tham số `hentaikham`
![image](https://github.com/user-attachments/assets/95e19b52-2b30-49ee-b163-5b8d13786884)

**Comment by nghivanbi** [comment]
---------------------------------------------------------------------
### 💡 GÓP Ý MÔ TẢ💡
---------------------------------------------------------------------
- Tham số nên mặc định là 0: vì không phải bệnh nhân nào cũng cần hẹn nhé @lequocthong29

**Comment by ongtrieuhau-dh** [comment]
#### 👉 @lequocthong29 mô tả kỹ hơn liên quan tới thao tác của người dùng cũng như áp dụng tham số trên:
1. Thao tác lưu ở Form **[`Khám Bệnh`]**
2. Thao tác lưu toa thuốc ở Form **[`Toa Thuốc`]**

**Comment by lequocthong29** [comment]
Cập nhật [mô tả ghi nhận ngày hẹn tái khám](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/Thong-mo-ta-ghi-nhan-ngay-hen-kham-lai.md)
![image](https://github.com/user-attachments/assets/f26a3b71-9660-427a-8699-c0c944b5bda1)

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: Thực hiện theo mô tả nhé
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
> ## HD.05
> * ✔️ **Đã tiếp nhận**
> * 👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
> * 📆 **Thời gian hoàn thành :**  2024-08-22.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0821.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408211-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408211-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408211-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Cập nhật theo mô tả [ghi nhận ngày hẹn tái khám](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/Thong-mo-ta-ghi-nhan-ngay-hen-kham-lai.md)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/291

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0821.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408212-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408212-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408212-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Cập nhật theo mô tả [ghi nhận ngày hẹn tái khám](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/Thong-mo-ta-ghi-nhan-ngay-hen-kham-lai.md)

- 🐛: Fix lỗi thiếu điều kiện - dẫn đến không thể lưu khám bệnh khi ngày hẹn = null

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/291

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nghivanbi** [comment]
### 💡KIỂM TRA SẢN PHẨM💡
---------------------------------------------------------------------
📣 **Phân công kiểm tra**: @lqbinh1987
📣 **Hạn hoàn thành mong muốn**:

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @nghivanbi @lqbinh1987

**Comment by nghivanbi** [comment]
⚠️ NHẮC NHỞ ⚠️
---------------------------------------------------------------------
-  👉 **Assign**: @lqbinh1987 
-  📘 **Nội dung**: phân công kiểm tra chức năng theo mỗ tả
- 📣 Hạn hoàn thành: 09/10/2024

**Comment by lqbinh1987** [comment]
💡KIỂM TRA SẢN PHẨM💡
***
Mô tả:
 - Khi đã có ngày hẹn ở phòng khám trước, sau đó chuyển phòng khác khám, khi Lưu khám bệnh thì có cảnh báo có muồn thay đổi ngày hẹn không, nếu chọn ngày hẹn khác thì lưu lại ok, còn trường hợp nếu BS không muốn hẹn, chọn Không thì phần mềm không cho lưu, cứ bấm chọn Không và Lưu hoài thì cứ cảnh báo như vây hoài, khi nào bấm Đồng ý thì mới cho lưu, vì BS phòng khám sau không hẹn, không chọn ngày hẹn, nên bấm Đồng ý thì trong psdangky.ngaytaikham sẽ bị mất của BS phòng khám trước.



***
Thông tin bệnh nhân(nếu có)
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `Tên data`
- ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link)
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000013` - _**MaKB**_: `2408000013` - _**MaBA**_: `MaBA` _**07/10/2024**_: `` - _**MaPhong**_: `01 và 30` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
![image](https://github.com/user-attachments/assets/de8c654c-7051-4c23-bb81-a4eeafe43fe5)
![image](https://github.com/user-attachments/assets/0f883825-51f6-4bed-8d8b-328a6ae304d0)
Clip:

https://github.com/user-attachments/assets/2c881b4c-2d91-4da7-9299-dc4d0b8e665b


***
❌ Không thể tiếp tục kiểm tra sản phẩm, **tạm dừng kiểm tra.**

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.1008.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410081-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410081-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410081-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - Lưu khám bệnh thì có cảnh báo có muồn thay đổi ngày hẹn không, nếu chọn ngày hẹn khác thì lưu lại ok, còn trường hợp nếu BS không muốn hẹn, chọn Không thì phần mềm không cho lưu

- Xữ lý khi có cảnh báo đã hẹn tái khám, nếu bác sĩ chọn không thay đổi thì hiển thị lại ngày hẹn củ

![](https://i.imgur.com/pWSbITo.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/291

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
✅ **Đã hỗ trợ**
Kiểm tra tại form khám bệnh.

https://github.com/user-attachments/assets/45063d5f-10a0-42da-86ef-620037c36849

Kiểm tra tham số hentaikham=1 tại form ra toa

https://github.com/user-attachments/assets/9ab5c73a-defc-4730-b283-acbc28648274
