### ISSUE TITLE
Lỗi - Prescription BANT In phiếu Tổng lỗi  kết Admin không lấy được file XML4750

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprescription#292]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbbvdkomon_xml`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/4qMOr6tRa)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2017082528` - _**MaKB**_: `2407000104` - _**MaBA**_: `N2024005350` _**NgayKCB**_: `31/07/2024` - _**MaPhong**_: `LT1` - _**MaDV**_: `12` - _**ThangKT**_: `07` - _**NamKT**_: `2024`
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`

Khi bấm in nút Tổng kết chi phí bấm in ra phiếu 01KCB và đóng lại xuất hiện lỗi như hình dưới. Và trên Admin không thấy file XML
![image](https://github.com/user-attachments/assets/0bc9d182-6abf-4bf4-93ba-6347da96bce3)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Kiểm tra Lỗi - Prescription BANT In phiếu Tổng lỗi kết Admin không lấy được file XML4750.
-  📆 **Thời gian hoàn thành :**  2024-08-07.

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @hvtuan1987 
![](https://i.imgur.com/nlrXIAy.png)

**Comment by hvtuan1987** [comment]
Đã ok !
![image](https://github.com/user-attachments/assets/37357892-8ebb-443a-98ff-c7a9927baa3f)
