### ISSUE TITLE
Lỗi - BANT đã khám thêm diễn biến có công khám nhưng psdangky.dakham = 0 gây lỗi khi nhập viện và Printer không tìm thấy bệnh nhân

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#294]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **7/8/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92092`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV QDY CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_ct_bant_nhapvien_chuyenvien_07_082024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/snBRU4QYW)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018022682` - _**MaKB**_: `2408002106` - _**MaBA**_: `N2024000027` _**NgayKCB**_: `7/8/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân BANT đăng ký tái khám đã khám thêm diễn biến mới nhưng psdangky.dakham = 0
- Nếu kết thúc bệnh án rồi vào nhập viện thì phần mềm báo lỗi
- Bệnh nhân có công khám nhưng Printer không tìm thấy bệnh nhân để in bảng kê

![ảnh](https://github.com/user-attachments/assets/8da92dda-a856-419b-9ec9-6894ff2f5014)
![ảnh](https://github.com/user-attachments/assets/0c4faa74-0ea1-4d2d-a85e-8ee343d52d76)
![ảnh](https://github.com/user-attachments/assets/6c01e58f-5f41-457d-9158-f3ff5d5c872d)

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-08-09.

**Comment by chauthanhtra** [comment]
Ghi lại thông tin mô tả lỗi bị sai
"Bệnh nhân BANT đăng ký tái khám đã khám thêm diễn biến mới nhưng psdangky.dakham = 0"
=> "Bệnh nhân BANT đăng ký tái khám đã khám thêm diễn biến mới nhưng khambenh.dakham = 0"

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0808.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408081-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408081-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408081-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - BANT đã khám thêm diễn biến có công khám nhưng psdangky.dakham = 0 gây lỗi khi nhập viện

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/294

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
Để thử lại

**Comment by chauthanhtra** [comment]
Prescription.exe v.3.24.0808.1 

Đã fix lỗi BANT đã khám thêm diễn biến có công khám nhưng khambenh.dakham = 0 gây lỗi khi nhập viện và Printer không tìm thấy bệnh nhân

![ảnh](https://github.com/user-attachments/assets/6f09fd0b-e4c4-4f07-9204-3246590934c5)
![ảnh](https://github.com/user-attachments/assets/743a8c45-9744-44b6-9d92-d4b36333492e)
![ảnh](https://github.com/user-attachments/assets/bf7ab5bb-bd7e-4550-bb61-771cd29e058b)
![ảnh](https://github.com/user-attachments/assets/dde88830-b7f7-48ea-96b0-e13bfefb50df)
![ảnh](https://github.com/user-attachments/assets/18494520-527e-4a6d-a51f-3ce42435166d)
