### ISSUE TITLE
Lỗi - Prescription 07/08 Lỗi khi in, xem toa thuốc khi CÂN NẶNG = rỗng ở Prescription bệnh nhân ngoại trú, BANT 

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#296]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_cairang_t8`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/6oDiyNDn8)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024009658` - _**MaKB**_: `2408001326` - _**MaBA**_: `MaBA` _**NgayKCB**_: `07/08/2024` - _**MaPhong**_: `32` - _**MaDV**_: `03` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Lỗi Bệnh nhân ngoại trú hay BANT không có BHYT
Do bệnh nhân thu phí, không có BHYT không cần nhập cân nặng nên nhiều bệnh nhân khi in hay xem toa thuốc trên Prescription sẽ báo lỗi

![image](https://github.com/user-attachments/assets/7069725b-baa9-499c-b8a9-69c3b563d492)
![image](https://github.com/user-attachments/assets/e0b4232f-3b54-4741-9fd7-271e0258d501)
![image](https://github.com/user-attachments/assets/59d1db8c-e510-47f8-91e9-673f529a806d)

**Comment by lequocthong29** [comment]
@chauthanhtra thử lại trên bản pre mới nhất nha a

**Comment by chauthanhtra** [comment]
ok để thử lại

**Comment by chauthanhtra** [comment]
Prescription 08/08 
Đã fix lỗi khi in hay xem toa thuốc bệnh nhân không có cân nặng

![ảnh](https://github.com/user-attachments/assets/f3db9e1e-83bc-4828-b32c-a6b9dc9e6ed9)
![ảnh](https://github.com/user-attachments/assets/85c7cee3-e87d-4f8b-9489-dc5c97a2a117)
