### ISSUE TITLE
Lỗi - Khi xóa chuyển phòng bệnh nhân BANT thì mất thông tin bệnh nhân ở phòng khám

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#297]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_cairang_t8`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/6oDiyNDn8)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024009657` - _**MaKB**_: `2408001325` - _**MaBA**_: `N2024003280` _**NgayKCB**_: `7/8/2024` - _**MaPhong**_: `32` - _**MaDV**_: `32` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Bệnh nhân BANT khi thực hiện chuyển sang phòng khác , chuyển xong thì xóa phiếu chuyển phòng đó thò phần mềm không trả bệnh nhân đó về phòng đầu mà mất thông tin bệnh nhân đó ở cả 2 phòng, không tìm thấy bệnh nhân
- Ngyên nhân là do khi xóa phiếu chuyển phòng thì không cập nhật lại mã đơn vị (madv) và mã phòng (maphong) ở bảng bnnoitru trả lại phòng đầu ( do dữ liệu bảng khambenh ở phòng 2 bị xóa khi xóa phiếu chuyển nên bệnh nhân bị treo giữa 2 phòng) 
-> Cập nhật lại mã đơn vị (madv) và mã phòng (maphong) ở bảng bnnoitru trả lại phòng đầu như trước khi chuyyển nếu xóa phiếu chuyển (lưu ý: chỉ được xóa phiếu chuyển phòng nếu bệnh nhân chưa khám ở phòng 2)

![image](https://github.com/user-attachments/assets/6b07757a-be1b-4f65-bba6-1fd22e192006)
![image](https://github.com/user-attachments/assets/2cf979e6-342d-4d7a-bf72-177e38cc4307)
![image](https://github.com/user-attachments/assets/b9dafaeb-4d61-49ac-b4db-aded06b9be1c)

![image](https://github.com/user-attachments/assets/bb4a5ae5-b203-42ad-ba01-9272381537f7)
![image](https://github.com/user-attachments/assets/332eec3a-8ad1-4cb9-b6a3-2426acae9014)
![image](https://github.com/user-attachments/assets/ff43e63a-15c2-4bdd-be38-e34204c7ccc6)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-08-14.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0826.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408260-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408260-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408260-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - Lỗi khi xóa chuyển phòng bệnh nhân BANT thì mất thông tin bệnh nhân ở phòng khám

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/297

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '  2/9/2024  '.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Prescription.exe v.3.24.0827.0
***
>Lỗi, yêu cầu đã hoàn thành 
- Nội dung: 
  - Đã fix lỗi bệnh nhân BANT xóa chuyển phòng không thấy bệnh nhân ở phòng chuyển

- Hình ảnh: 

![ảnh](https://github.com/user-attachments/assets/9d018111-ea75-48a1-ba5d-90fe7adbe9bc)

  - Trước khi xóa chuyển phòng

![ảnh](https://github.com/user-attachments/assets/91647786-f063-4416-9d42-5993bb4fb48c)
![ảnh](https://github.com/user-attachments/assets/2a61beea-4446-4559-8223-7286186806a6)
![ảnh](https://github.com/user-attachments/assets/8a607520-e423-4c3b-a93b-cfe7afc79946)

  - Sau khi xóa chuyển phòng

![ảnh](https://github.com/user-attachments/assets/ab806fe4-4aff-4d50-bffc-05550f8fbb79)
![ảnh](https://github.com/user-attachments/assets/1f17943c-1062-437b-a000-0da0e7a4c2c9)
![ảnh](https://github.com/user-attachments/assets/f7d91828-5963-4e8b-a703-070c57d63d36)




***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

- Diễn giải lỗi: Do chỉ xóa được chuyển phòng khi bệnh nhân chưa khám ở phòng được chuyển và dữ liệu bảng khambenh ở phòng được chuyển cũng được xóa nhưng hiện tại dữ liệu bảng qtdieutri của phòng được chuyển vẫn còn
-> Đề nghị khi xóa chuyển phòng thì xóa luôn quá trình điều trị của bệnh nhân ở phòng được chuyển (chưa có thông tin khám bệnh) 


- Hình ảnh lỗi:

![ảnh](https://github.com/user-attachments/assets/56601115-c99a-49e7-a75d-daa2681be84f)
![ảnh](https://github.com/user-attachments/assets/06ba6b82-f083-437b-afdc-e4eb102c8017)



> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Chưa hoàn thành**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại trường hợp xóa chuyển phòng nhưng vẫn còn diễn biến rỗng ở phòng được chuyển ( diễn biến không có thông tin khám bệnh)

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '  6/9/2024  '.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Prescription.exe v.3.24.0906.0
***
>Lỗi, yêu cầu đã hoàn thành 
- Nội dung: Đã fix lỗi mất bệnh nhân BANT khi xóa chuyển phòng, đã fix lỗi xóa chuyển phòng không xóa quá trình điều trị 
  - Test dữ liệu bệnh nhân chưa phát sinh lỗi liên quan, cấp toa, chỉ định CLS, in bảng kê, xuất XML bình thường

- Hình ảnh: 

![ảnh](https://github.com/user-attachments/assets/7fc28058-0b56-4b2b-a487-f92747335695)
![ảnh](https://github.com/user-attachments/assets/6261b153-2e5d-41f6-93b7-cf4132eb120d)
![ảnh](https://github.com/user-attachments/assets/1c5b33ca-493f-4742-95d2-54196566777e)
![ảnh](https://github.com/user-attachments/assets/8cdbcac5-b0e5-443e-bc03-03984bfb5694)
![ảnh](https://github.com/user-attachments/assets/a8ea3e22-cdea-432d-b549-d8e1640a3c6f)
![ảnh](https://github.com/user-attachments/assets/db877c48-b47a-479e-b582-272cb64e553c)


***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

>- Diễn giải lỗi:


>- Hình ảnh lỗi:



> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Hoàn Thành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
