### ISSUE TITLE
Lỗi - Sai phường xã form nhập viện và địa chỉ bệnh nhân trên Tem bệnh án lấy danh mục địa phương cũ

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#302]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_saidiachi_12082024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/6c3k6MCST)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024065266` - _**MaKB**_: `2408007367` - _**MaBA**_: `013486` _**NgayKCB**_: `12/8/2024` - _**MaPhong**_: `35` - _**MaDV**_: `12` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Thông tin phường xã trên form nhập viện đang lấy danh mục phường xã cũ
- In tem bệnh án các loại đang lấy danh mục địa phương cũ

![ảnh](https://github.com/user-attachments/assets/ea33db4d-b593-4b9d-815e-8f08c2f02d87)
![ảnh](https://github.com/user-attachments/assets/f275f979-90b9-4bd8-9f8e-d9f1e691acd6)
![ảnh](https://github.com/user-attachments/assets/aab592f7-0b08-4875-a8e0-11c522334a11)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-14**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-08-14.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0814.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408141-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408141-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408141-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - Sai phường xã form nhập viện và địa chỉ bệnh nhân trên Tem bệnh án lấy danh mục địa phương cũ

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/302

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '19/08/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***

- Prescription đã fix lỗi Sai phường xã form nhập viện và địa chỉ bệnh nhân trên Tem bệnh án lấy danh mục địa phương cũ

![ảnh](https://github.com/user-attachments/assets/ec2daa3f-9b07-43cc-9ed7-e1dce79ad276)
![ảnh](https://github.com/user-attachments/assets/d6809cae-0c96-4d7f-8e36-d9c678529a92)

> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi: Đề nghị
  - Phần tên Phường xã nên chỉnh lại cho thẩm mỹ hơn, hiện tại xã huyện tỉnh viết liền nhau
  - Phần tên phường xã nên thể hiện địa phương theo đạng tắt " Xã xxx, Huyện xxx, Tỉnh xxx "
- Hình ảnh lỗi:
![ảnh](https://github.com/user-attachments/assets/95ecfc7a-fb46-4238-b6ad-cd3d6561447a)


> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Chưa hoàn thành**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại: Đề nghị chỉnh lại tên phường xã

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0819.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408190-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408190-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408190-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: chỉnh lại định dạng tên phường xã

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/302

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0819.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408191-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408191-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408191-NasDHSolutions.json)

## Nội dung thay đổi

🐛: chỉnh lại định dạng tên phường xã trên form nhập viện

☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/302

![](https://i.imgur.com/ya0pZXN.png)

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '26/08/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***

Prescription.exe v.3.24.0819.2
- Đã fix lại định dạng tên phường xã trên form nhập viện
- Đã fix địa chỉ in tem bệnh án

![ảnh](https://github.com/user-attachments/assets/4425b38a-ea5c-475c-b32c-c561c464ae05)

- Test bệnh nhân mới khám bệnh, cấp thuốc, in bảng kê, xuất  XML bình thường chưa ghi nhận lỗi mới nhập viện

![ảnh](https://github.com/user-attachments/assets/81ac7b53-635d-41c9-8a27-bcf5882394cb)
![ảnh](https://github.com/user-attachments/assets/d9193e8f-7817-46d0-8a76-31ff2073d92d)


> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:

- Hình ảnh lỗi:


> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
