### ISSUE TITLE
Lỗi - Prescription mới 21/8/2024 khi khám bệnh thì báo lỗi

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#309]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/8/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusan_saithangquyettoan_xml4750_07_082024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/db5We96Zo)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024063505` - _**MaKB**_: `2408003072` - _**MaBA**_: `MaBA` _**NgayKCB**_: `22/8/2024` - _**MaPhong**_: `35` - _**MaDV**_: `12` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Prescription ngày 21/08/2024 khi khám bệnh thì báo lỗi

![ảnh](https://github.com/user-attachments/assets/351c8ce5-250b-4aba-a38c-07c7bbfecaee)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-08-22.

**Comment by lequocthong29** [comment]
@chauthanhtra 
Cập nhật cấu trúc : Thêm cột mabshk vào bảng current.psdangky
![image](https://github.com/user-attachments/assets/62bbd850-d317-43ae-a0a4-f2d11a97a622)

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '  22/8/2024  '.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **Hoàn Thành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
