### ISSUE TITLE
Lỗi - Báo cáo Lượt đăng ký ban đầu không xem được thông tin khám

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#31]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dongtay_2209014922`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022008471` - _**MaKB**_: `2209014922` - _**NgayKCB**_: `15/9/2022` - _**MaPhong**_: `H06` - _**MaDV**_: `K10` - _**ThangKT**_: `09` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Báo cáo Lượt đăng ký ban đầu không xem được thông tin khám!
Trường hợp Bệnh nhân đăng ký phòng N04 không khám chuyển qua phòng H06.


```
Bệnh nhân có khám bệnh tại phòng khám
![image](https://user-images.githubusercontent.com/96155021/190582943-0fb4bb41-7bd5-4e44-b110-7be84ce6caca.png)

BC lượt đăng ký không xem được thông tin khám
![image](https://user-images.githubusercontent.com/96155021/190582534-cff6dd7c-d420-4a97-839f-1a052a0282f0.png)

**Comment by nghivanbi** [comment]
Này xem thông tin khám theo phòng thôi nha, đã trả lời bên Register

**Comment by le-an-87** [comment]
cập nhật theo lỗi https://github.com/dh-hos/dhg.hospitalregister/issues/15
