### ISSUE TITLE
Lỗi - CHƯA RÀNG BUỘC MÃ CÔNG VIỆC KHI CHỌN EKIP PT/TT

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#310]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_thanhtri_full`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/yfpljkdQ4)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024009424` - _**MaKB**_: `2408001574` - _**MaBA**_: `MaBA` _**NgayKCB**_: `12/08/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Tại trường mã công việc khi chọn không ràng buộc theo dmcongviecphauthuat.macongviec khi người dùng vô ý nhập lại thì vẫn lưu được >>> Ràng buộc macongviec theo danh mục để tránh nhập tự do vào và sai thông tin trên sổ thủ thuật
![image](https://github.com/user-attachments/assets/2206b644-16d4-473a-9830-d05f5dcba9aa)
![image](https://github.com/user-attachments/assets/0ff9c249-1d64-4a0e-9aa7-8cb2fa3d448a)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-08-26.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0826.3 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408263-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408263-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32408263-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - Lỗi chưa ràng buộc mã công việc khi chọn ekip PT/TT

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/310

![](https://i.imgur.com/grOvDaH.png)

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
✅ Đã fix
![image](https://github.com/user-attachments/assets/006697ca-9841-4eaa-a55e-489054830486)
