### ISSUE TITLE
Lỗi - BANT MÃ CHẨN ĐOÁN PHỤ KHÔNG HIỂN THỊ

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprescription#329]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74206`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Medic Miền Đông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_medic_maicdphu`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/qPF5b4R5W

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024034004` - _**MaKB**_: `2409004562` - _**MaBA**_: `N2024012606` _**NgayKCB**_: `10/09/2024` - _**MaPhong**_: `01` - _**MaDV**_: `CC` - _**ThangKT**_: `09` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

 BANT IN TỔNG KẾT MÃ CHẨN ĐOÁN PHỤ KHÔNG HIỂN THỊ

![image](https://github.com/user-attachments/assets/56ea3eeb-0118-434c-98b9-33b8019d6796)

![image](https://github.com/user-attachments/assets/83f39173-2a6c-4ba8-b0b5-ad87e286b14c)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-18**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @minhduc2it 
- Hướng dẫn người dùng nhập chẩn đoán phụ trong phần **_Kết thúc điều trị_**, vì đây là BANT thanh toán theo đợt, nên những thông tin trên phiếu 01 sẽ lấy thông tin trong chức năng này.
- ![](https://i.imgur.com/HUvW3H6.png)

**Comment by minhduc2it** [comment]
@ongtrieuhau-dh Xem lại chỗ này dùm em
Mục Tổng kết: Chẩn đoán ra viện > Bệnh phụ: có tên chẩn đoán phụ mà ô mã ICD phụ không load mã ICD
![image](https://github.com/user-attachments/assets/bc72e4a4-9f8e-45ac-bef9-6d910a33d626)

**Comment by ongtrieuhau-dh** [comment]
### 📢 @minhduc2it 
---

- Control này hỗ trợ nhập nhiều, nên người dùng có thể xóa.

**Comment by minhduc2it** [comment]
@ongtrieuhau-dh 
Khi cho Kết thúc ĐT thì mã Bệnh phụ có
Khi Kết thúc ĐT xong vào lại bị mất mã Bệnh phụ
![image](https://github.com/user-attachments/assets/846978f5-f6af-4719-8a81-51eee7bec351)

![image](https://github.com/user-attachments/assets/f4d6ab10-adbd-4375-8ec7-f57b7088422c)

Video thao tác: 

https://github.com/user-attachments/assets/1956e723-3fcb-4746-bd84-e3bd015f2387

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**:

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-09-17.

**Comment by minhduc2it** [comment]
@ongtrieuhau-dh 
BANT tài khoản admin bấm **In Tổng kết** sẽ có bảng thông báo Có muốn thiết kế trang in > Đồng í vào thiết kế > Thoát from thiết kế > vào lại **In Tổng kết** thì không hiển thị bảng thông báo Có muốn thiết kế trang in

![image](https://github.com/user-attachments/assets/5f9417b5-4f52-4f4d-9758-a13ca240e372)

Video thao tác: 

https://github.com/user-attachments/assets/d66255d4-6e8b-47a3-99d1-db3f547283f6

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: Kiểm tra chỗ này luôn nhé

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0916.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409162-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409162-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409162-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - Lỗi BANT khi cho Kết thúc ĐT thì mã Bệnh phụ có Khi Kết thúc ĐT xong vào lại bị mất mã Bệnh phụ

![](https://i.imgur.com/kWV40ht.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/329

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lequocthong29** [comment]
Kiểm tra lại DLL OTH.XForms.dll dùm e nha a @ongtrieuhau 
- Khi ấn vào thiết kế trang in và tắt đi thì xuất hiện thông báo lỗi. Nếu ấn bỏ qua thì không xuất hiện thông báo thiết kế trang in nữa.
![](https://i.imgur.com/mLE2BIy.png)
![Prescription vshost_MlQDlmms2k](https://github.com/user-attachments/assets/dbd9251b-5cbf-4b0b-9677-cccf1105520e)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0916.3 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409163-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409163-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409163-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - BANT MÃ CHẨN ĐOÁN PHỤ KHÔNG HIỂN THỊ_**

- 🐛: Hỗ trợ thể hiện trang in sau khi thiết kế

- 🐛: Fix lỗi Chọn in Tổng kết lần 2, không hỏi thiết kế trang in ![](https://i.imgur.com/lsY8Hdy.png) ![](https://i.imgur.com/PHBWTZ4.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/329

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
> * Fix lỗi Chọn in Tổng kết lần 2, không hỏi thiết kế trang in

**CHƯA HOÀN THÀNH**
---
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu @ongtrieuhau-dh kiểm tra lại.
---
Chọn in Tổng kết lần 2 vẫn không hỏi thiết kế trang in
Phải tắt phần mềm mở lại thì  in Tổng kết lần 1 mới hỏi Thiết kế

Link Video test: https://gofile.me/78TQg/GiMWXXLzt

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @minhduc2it  </sub>

- ***Thử xem cấu hình này nhé ![](https://i.imgur.com/RQsjSpu.png)***

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Đã kiểm tra Lỗi - BANT MÃ CHẨN ĐOÁN PHỤ KHÔNG HIỂN THỊ ok
![image](https://github.com/user-attachments/assets/a4d638a8-0af7-4505-96d3-9ed8ab2717ed)

![image](https://github.com/user-attachments/assets/362a07cb-af35-4ae5-b421-f01faee59827)

**Comment by minhduc2it** [comment]
@ongtrieuhau-dh  Xem thêm chỗ này dùm em nha

BANT> Kết thúc ĐT > Hồ sơ 
Tờ Bệnh án ngoại trú:  **Chẩn đoán ra viện: Chẩn đoán phụ không hiển thị mã chẩn đoán**
Kiểm tra bản Precsription 3.24.0826.0 có hiển thị

- **Trên bản Precsription 3.24.0916.3**

![image](https://github.com/user-attachments/assets/35485b1e-faf0-4e49-9022-4cca0a06976a)

- **Bản Precsription 3.24.0826.0**
![image](https://github.com/user-attachments/assets/745568fb-96cb-4e6b-b506-fbf05abd4826)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0917.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409170-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409170-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409170-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - Lỗi BANT khi Kết thúc ĐT vào hồ sơ - Tờ Bệnh án ngoại trú Chẩn đoán ra viện - Chẩn đoán phụ không hiển thị mã chẩn đoán

![](https://i.imgur.com/iDvm7pS.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/329

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Đã kiểm tra ok
![image](https://github.com/user-attachments/assets/9cabad56-0151-4f82-947d-f518982ccc3f)
