### ISSUE TITLE
Lỗi - trừ kho tủ trực (BV cái răng)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#330]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_cairang_saitonkho_11092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_cairang_saitonkho_11092024`](https://gofile.me/78TQg/ZNLKF33EY)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024011541` - _**MaKB**_: `2409003340` - _**MaBA**_: `MaBA` _**NgayKCB**_: `16/09/2024` - _**MaPhong**_: `60` - _**MaDV**_: `01` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**TuTruc**_: `37` - _**MaHH**_: `IS01`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Lỗi trừ kho tủ trực trường hợp cập nhật kho tủ trực khi đang thực hiện ra toa.
(mình họa các bước và hình bên dưới)
```
### Mã hàng IS01 trước khi thực hiện.
![ảnh](https://github.com/user-attachments/assets/4d9ade43-49bc-4744-983a-31a4af4ddcf3)
### Thực hiện ra toa nhưng chưa lưu toa (số lượng = 20)
![ảnh](https://github.com/user-attachments/assets/00f011da-db6d-44da-9b65-b27eab089ab1)
### Thực hiện kiểm tra tủ trực đã thực hiện trừ kho
![ảnh](https://github.com/user-attachments/assets/8d09668e-3a7f-4c15-ad48-0ee8d24fb722)
### Tiến hàng cập nhật lại kho
![ảnh](https://github.com/user-attachments/assets/db16038d-0627-4814-b2fe-6cf4ed8800b3)
![ảnh](https://github.com/user-attachments/assets/4bb8f01e-cc47-4b77-9cdd-4280c5d4e87c)
### Tiến hành lưu toa
![ảnh](https://github.com/user-attachments/assets/7d6e56ff-90d5-471b-b367-9016c577e9e1)
## Kết quả kiểm tra lại tủ trực sẽ bị trừ sai số lượng xuất.
![ảnh](https://github.com/user-attachments/assets/ab1933a4-b6bb-4393-b6b9-b3f593450ca0)

**Comment by nghivanbi** [comment]
✔️ Đã tiếp nhận
⌛Nghiên cứu cách ghi nhận hoặc cảnh báo. Hạn : 23/09/2024

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi: Kiểm tra giùm em vụ này bv hối anh ơi.

🔈 Giải đáp:
***

**Comment by nghivanbi** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @le-an-87 
-  📘 **Nội dung**:
- Đã trao đổi  với bệnh viện hạn chế việc cập nhật tồn kho tủ trực trong thời gian khám.
- Lập yêu cầu để thực hiện chức năng khóa tủ khi phòng khám đang ra toa để không xảy ra trường hợp này.

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi: 

🔈 Giải đáp: Lập yêu cầu là sao anh?
này không phải lỗi sao mà phải lập yêu cầu.
***

**Comment by nghivanbi** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @le-an-87 
-  📘 **Nội dung**: Nây đúng là lỗi nhưng là lỗi qui trình của phần mềm, anh yêu cầu phân tích chỉnh chung cho phần mềm thôi.

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi:

🔈 Giải đáp: không hiểu anh comment của anh.
-> là em phải lập yêu cầu mới đề nghị chỉnh sửa qui trình phần mềm đúng không?
***

**Comment by nghivanbi** [comment]
💡 TRAO ĐỔI💡
---------------------------------------------------------------------
-  👉 **Assign**: @le-an-87 
-  📘 **Nội dung**: Anh lập yêu cầu cho.
