### ISSUE TITLE
Lỗi - chức năng ra toa thuốc không lấy được thuốc còn tồn kho (BV Hồng Dân)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#332]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95005`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Hồng Dân**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_hongdan_17092024_1`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_hongdan_17092024_1`](https://gofile.me/78TQg/bwqEBfby0)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019026396` - _**MaKB**_: `2409006348` - _**MaBA**_: `MaBA` _**NgayKCB**_: `17/09/2024 7:37:47 SA` - _**MaPhong**_: `PK19` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `16` - _**KhoLe**_: `01` - _**MaHH**_: `AC138` - _**ThangKT**_: `09` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Thuốc AC138 và AL176 đều còn tồn kho
-> Prescription chỉ load được thuốc AL176 để ra toa. Thuốc AC138 không load lên để ra toa được.

```
![ảnh](https://github.com/user-attachments/assets/0a417a6d-ed3d-43e3-9ac2-19fd6a454e93)
## AC176
![ảnh](https://github.com/user-attachments/assets/f62f1c44-e935-4d11-9f61-b8b2419a82fa)
## không có AC138
![ảnh](https://github.com/user-attachments/assets/ca30a0c8-81e8-4d0c-b708-a22aeec7532a)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-09-20.

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
Bệnh viện ra toa không được, tranh thủ cho bẹnh nhe @lequocthong29 
***

**Comment by lequocthong29** [comment]
@le-an-87 ok a

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0919.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409190-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409190-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409190-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - chức năng ra toa thuốc không lấy được thuốc còn tồn kho (BV Hồng Dân) #332

![](https://i.imgur.com/A9hcx6i.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/332

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ KIỂM TRA SẢN PHẨM**
***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:

- Hình ảnh lỗi:

> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/f0b544ae-45e1-479e-a4fe-ab82b4e75a67)
![ảnh](https://github.com/user-attachments/assets/9be662a0-180f-4190-a711-d6b6cadf8c1e)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.
