### ISSUE TITLE
Lỗi - không xóa được công khám (BV Đặng Thùy Trâm)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#333]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dtt_xoack_18092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_dtt_xoack_18092024`](https://gofile.me/78TQg/kaoZ5K7yV)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021012104` - _**MaKB**_: `2409004027` - _**MaBA**_: `MaBA` _**NgayKCB**_: `18/09/2024 11:39:02 SA` - _**MaPhong**_: `05` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `CO16`
###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân có công khám CO16 không có chỉ định toa VTYT kèm theo
-> khi xóa phần mềm báo công khám có toa vtyt kèm theo không cho xóa.
```
![ảnh](https://github.com/user-attachments/assets/a8db7e3e-07c2-4849-8cb3-50fa77fb045d)
![ảnh](https://github.com/user-attachments/assets/efd9fe00-ebdd-4339-9105-706eab03d42e)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-09-20.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0919.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409192-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409192-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409192-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - không xóa được công khám (BV Đặng Thùy Trâm)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/333

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ KIỂM TRA SẢN PHẨM**
***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:

- Hình ảnh lỗi:

> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/31e2c1b1-ec6c-41b7-b5a2-9d76f4115608)
![ảnh](https://github.com/user-attachments/assets/784b6986-7bd1-4faa-818c-6c3f4ec0b1f5)
![ảnh](https://github.com/user-attachments/assets/17f0d58a-d324-45f0-b835-773157104f8f)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
