### ISSUE TITLE
Lỗi - Prescription: bệnh nhân có chỉ định toa vật tư kèm theo phần mềm không cho chỉ định thêm cận lâm sàng 

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprescription#334]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquan12_sieuam_loi`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/ovSlw3Wt2)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024069593` - _**MaKB**_: `2409019355` - _**MaBA**_: `MaBA` _**NgayKCB**_: `18/09/2024` - _**MaPhong**_: `09` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `02` - _**MaHH**_: `BO264` - _**SoHD**_: `P14.00002/09` - _**NgayHD**_: `18/09/2024` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `NH09` - _**PhieuYC**_: `PhieuYC`

- Bệnh nhân tại phòng khám Bác sĩ chỉ định cận lâm sàng và Lập Toa vật tư kèm theo thì khi cần chỉ định thêm cận lâm sàng tại phòng khám đó nữa thì phần mềm đang chặn không cho được. Nên vẫn còn đang khó khăn cho đơn vị
Đề nghị cho phép chỉ định thêm cận lâm sàng khi đã có Toa vật tư kèm theo tại phòng khám đó !
![image](https://github.com/user-attachments/assets/df9fa1d6-4c03-4a6d-9690-2f0ff24d2d7a)
![image](https://github.com/user-attachments/assets/84f24f11-0402-421d-af74-30d54c4cc813)
Khi bấm thêm phần mềm báo như hình dưới và không cho chỉ định thêm tại phòng khám đó
![image](https://github.com/user-attachments/assets/d2cf2ec6-f2c3-453e-94ea-ab7f10a9641c)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-09-20.

**Comment by hvtuan1987** [comment]
## 📣 @lequocthong29 
Xác nhận đã ok !
