### ISSUE TITLE
Lỗi - Prescription BANT Theo đợt in Phiếu Tổng kết chi phí báo lỗi

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprescription#335]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87190`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Da Liễu Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbdalieudt_intongket_loi`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/jw8gqNE2j)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024004415` - _**MaKB**_: `2405000714` - _**MaBA**_: `N2024000025` _**NgayKCB**_: `13/09/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2024`

Bệnh nhân có Bệnh án ngoại trú theo đợt kết thúc điều trị và bấm vào nút Tổng Kết CP ->  In Tổng kết
Khi in phiếu 01KCB xong đóng lại và báo lỗi như hình dưới
![image](https://github.com/user-attachments/assets/e501a8ad-dd97-46c1-8a50-c20b708d424e)

Chi tiết lỗi:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Lỗi xảy ra tại [Name:Void OTH.Adapter.HosBHXH.AGiamDinh.Print01Finished(),Assembly:OTH.Adapter.dll,Version: Version=1.24.919.0]. ---> System.InvalidOperationException: No transaction in progress.
   at Npgsql.NpgsqlTransaction.Rollback()
   at OTH.Adapter.HosBHXH.AGiamDinh.SaveXML130()
   at OTH.Adapter.HosBHXH.AGiamDinh.Print01Finished()
   --- End of inner exception stack trace ---
   at OTH.Adapter.HosBHXH.AGiamDinh.Print01Finished()
   at OTH.XForms.HosPrinter.BKChiPhiKCB6556.PrintFinish(Boolean IsUpdateChandoanXml)
   at OTH.XForms.HosPrinter.BKChiPhiKCB6556.PrintPreviewDialogByOption(Form parentForm, Boolean IsUpdateChandoanXml)
   at Prescription.Forms.FrmTKChiPhi.btnInTongKet_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at Janus.Windows.EditControls.UIButton.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Prescription
    Assembly Version: 3.24.919.3
    Win32 Version: 3.24.0919.3
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Prescription/Prescription.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
HosReg.Code
    Assembly Version: 3.24.916.0
    Win32 Version: 3.24.0916.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Prescription/HosReg.Code.DLL
----------------------------------------
Janus.Windows.Common.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Prescription/Janus.Windows.Common.v3.DLL
----------------------------------------
HosPre.BusinessLogic
    Assembly Version: 1.24.919.0
    Win32 Version: 1.24.0919.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Prescription/HosPre.BusinessLogic.DLL
----------------------------------------
Janus.Windows.CalendarCombo.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Prescription/Janus.Windows.CalendarCombo.v3.DLL
----------------------------------------
Janus.Windows.ExplorerBar.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Prescription/Janus.Windows.ExplorerBar.v3.DLL
----------------------------------------
LibraryApp
    Assembly Version: 4.24.810.0
    Win32 Version: 4.24.0810.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Prescription/LibraryApp.DLL
----------------------------------------
HosPre.DataAccess
    Assembly Version: 1.24.919.1
    Win32 Version: 1.24.0919.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Prescription/HosPre.DataAccess.DLL
----------------------------------------

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-25**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @hvtuan1987 
- **_Cập nhật cấu trúc để hỗ trợ chỉnh lỗi này_**: ![](https://i.imgur.com/5ygHIGK.png)

**Comment by hvtuan1987** [comment]
## 📣 @lequocthong29 
Xác nhận cập nhật cấu trúc trên Admin vào in lại đã ok !
