### ISSUE TITLE
Lỗi - PHÁT SINH LỖI KHI CHỈNH DIỄN BIẾN BANT

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#339]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `82242`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN ĐA KHOA TÂM MINH ĐỨC TIỀN GIANG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_tmdtiengiang_loichinhdienbien`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/2eW9MBI0e)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024018992` - _**MaKB**_: `2409004548` - _**MaBA**_: `N2024001665` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `TNT` - _**MaDV**_: `19` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Các bệnh án mới lập có diễn biến lần đầu khi chỉnh diễn biến thì phát sinh lỗi 

https://github.com/user-attachments/assets/8e63078d-2ca3-4c73-b3da-b5b89b512280
![image](https://github.com/user-attachments/assets/127d4fcd-7e2e-44f5-aa65-6eef5bd20a1b)

Kèm theo 1 lỗi cũ nhỏ vẫn còn sót khi cập nhật sinh hiệu chưa khoá nút làm mới, nếu bấm nút làm mới thì nút Khám bệnh sẽ bật lên và vượt qua được ràng buộc nhập sinh hiệu
![image](https://github.com/user-attachments/assets/0a01350b-0c82-4489-92f3-1df2ff5d163c)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-09-30.

**Comment by nqhoa1005** [comment]
Phát sinh thêm trường hợp Thêm diễn biến cho hôm nay để khám bệnh nhân bị lỗi tương tự, check gấp dùm anh @lequocthong29 , lùi bản bị lỗi đếm số lượng ICD

**Comment by nqhoa1005** [comment]
Sản Nhi, Tâm Minh Đức đang lỗi tương tự khi thêm diễn biến mới hôm nay
![image](https://github.com/user-attachments/assets/52b2c767-982a-430d-8c2b-3100711fa7cb)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0926.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409260-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409260-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409260-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - Lỗi phát sinh khi chỉnh, thêm diễn biến BANT

![](https://i.imgur.com/DKKrpyf.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/339

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
✅ Đã fix
> Lỗi do null maicdp khi lấy ra đếm
![image](https://github.com/user-attachments/assets/93bb1e94-484f-402c-8506-4377b507d67c)
