### ISSUE TITLE
Lỗi - Biên bản hội chẩn liên khoa  phần chữ ký bị qua trang 2 mà không kèm nội dung

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#34]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/9/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_caolanh_bbhc_lienkhoa`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022026270` - _**MaKB**_: `2209009512` - _**27/9/2022**_: `NgayKCB` - _**MaPhong**_: `HSCC` - _**MaDV**_: `02` - _**ThangKT**_: `09` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Biên bản hội chẩn liên khoa khi in chữ ký qua trang 2 mà không kèm theo nội dung!
-> phần chữ ký phải kèm theo nội dung.

```
BBHC liên khoa
![image](https://user-images.githubusercontent.com/96155021/192664161-89d40a10-7bd5-4eda-8ef4-54972c7bff8a.png)
![image](https://user-images.githubusercontent.com/96155021/192664223-d79ab83e-7f15-4d65-a97d-bf230d59bb19.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.1027.3](http://www.fsend.vn/download/pAZW4qUoK0eSRMoJESj847SRRCZZBCfh)

**Comment by le-an-87** [comment]
đã fix!
