### ISSUE TITLE
Lỗi - BV Ô Môn: Không xóa được CLS (Prescription báo CLS đã có toa vật tư)

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#340]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK QUẬN Ô MÔN**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_omon_xoacls_baovattukemtheo_26092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/ypGNPFvOQ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020002309` - _**MaKB**_: `2409000217` - _**MaBA**_: `N2024006628` _**NgayKCB**_: `26/9/2024` - _**MaPhong**_: `30` - _**MaDV**_: `29` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `TH119`

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2409000218` - _**MaBA**_: `N2024000001` _**NgayKCB**_: `26/9/2024` - _**MaPhong**_: `30` - _**MaDV**_: `29` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `NH64` 

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000002` - _**MaKB**_: `2409000219` - _**MaBA**_: `` _**NgayKCB**_: `26/9/2024` - _**MaPhong**_: `30` - _**MaDV**_: `29` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `NH64` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân ngoại trú và BANT có chỉ định CLS khi xóa CLS thì phần mềm báo CLS đã có toa vật tư không cho xóa nhưng CLS mới chỉ định chưa có toa vật tư, Nguyên nhân là do các lần tái khám trước hoặc các lần chỉ định CLS trước đã có chỉ định CLS này và đã cấp toa vật tư rồi
-> Đề nghị code fix lại lỗi này

- BANT theo đợt: 
![](https://i.imgur.com/wEEjrCk.png)
![](https://i.imgur.com/lWpHpC5.png)

- BANT theo ngày:
![](https://i.imgur.com/ul631Rw.png)
![](https://i.imgur.com/Z8lIyOX.png)

- Bệnh nhân ngoại trú:
![](https://i.imgur.com/sx4XGhF.png)
![](https://i.imgur.com/NNnn6eo.png)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-30**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-09-30.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0930.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409300-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409300-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32409300-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - BV Ô Môn: Không xóa được CLS (Prescription báo CLS đã có toa vật tư)

- Bổ sung `idchidinh` của CLS vào cột `current.chungtu.idchidinh` khi thêm toa vật tư.

- Khi load toa vật tư hoặc xóa CLS thì dựa vào `idchidinh`

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/340

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '7/10/2024'.
***

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription.exe v.3.24.0930.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Chứng từ vật tư đã bổ xung ID chỉ định của CLS , khi xóa CLS thì dựa và id chỉ định trên chứng từ vật tư

- Hình ảnh: 

![](https://i.imgur.com/tbH86l1.png)
![](https://i.imgur.com/7ingGjM.png)

***
### 🆘 **Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.**

- Diễn giải lỗi:
  - Khi load danh sách toa vật tư dựa vào idchidinh thì các toa vật tư trước đó không xem lại được do không có idchidinh 
  - Khi không thấy hết danh sách toa vật tư thì khó kiểm tra quản lý do phải xem từng CLS nếu muốn kiểm tra thông tin toa cũ

-> Đề xuất mặc định load hết toa vật tư như cũ, ___thêm cột dấu check trên form cấp toa vật tư sau toa để biết các toa vật tư của riêng CLS đó theo mã CLS và idchidinh trên chứng từ___ hoặc tham số cho các đơn vị lựa chọn có load toa vật tư của riêng CLS đó theo mã CLS và idchidinh trên chứng từ không
=> Code xem xét đưa ra phương án phù hợp ( ý kiến riêng  ___thêm cột dấu check trên form cấp toa vật tư sau toa để biết các toa vật tư của riêng CLS đó theo mã CLS  và idchidinh trên chứng từ___ )

- Hình ảnh lỗi:

![](https://i.imgur.com/0ldRIcL.png)
![](https://i.imgur.com/yMdy8wv.png)
![](https://i.imgur.com/IRnucNm.png)

![](https://i.imgur.com/Zm0PZVu.png)

> ***
> Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### ❎ **CHƯA HOÀN THÀNH**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại .

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.1008.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410080-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410080-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410080-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - BANT không xem được toa Vật tư y tế ngày củ

![](https://i.imgur.com/woStleT.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/343

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/340

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '15/10/2024'.
***

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription.exe v.3.24.1010.1
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Phần mềm Prescription đã hỗ trợ xem tất cả các toa VTYT của bệnh nhân

- Hình ảnh: 
![](https://i.imgur.com/Zd3571A.png)
![](https://i.imgur.com/jTgUN1x.png)
![](https://i.imgur.com/U6zPVG5.png)
![](https://i.imgur.com/93aYBUo.png)
![](https://i.imgur.com/WW6pjHr.png)

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
