### ISSUE TITLE
Lỗi - BANT theo ngày khi kết thúc bệnh án thì tạo thêm XML130 có mã bệnh án làm tăng số lượng XML Reports (trùng dữ liệu XML)

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#341]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Trà Cú**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_tracu_rep_trungxml_02102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/iTk9unw1K)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018012260` - _**MaKB**_: `2409006774` - _**MaBA**_: `N2024001765` _**NgayKCB**_: `17/9/2024` - _**MaPhong**_: `10` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân BANT thanh toán theo ngày khi in bảng kê thì phần mềm tạo 1 XML130 như ngoại trú (không có mã bệnh án)->đúng
Khi kết thúc bệnh án thì phần mềm tạo thêm 1 file XML130 NGOAI_TRU_XUAT_VIEN (có mã bệnh án)
-> số hồ sơ XML130  lệch với số hồ sơ XML4210 trên Reports và XML4750 trên Admin

=> Đề nghị fix lại chức năng này và hỗ trợ xóa XML130 bị dư 

![](https://i.imgur.com/Oe8nQ7R.png)
![](https://i.imgur.com/juCjZDE.png)
![](https://i.imgur.com/OS8Oj8X.png)
![](https://i.imgur.com/j1hAK2F.png)
![](https://i.imgur.com/CjVcun2.png)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-10-07**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-10-07.

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
Mấy anh xem hỗ trợ gấp chức năng xóa các xml lỗi để bệnh viện thực hiện gửi dữ liệu và đối chiếu xml với cổng bảo hiểm mấy anh ơi.
***

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.1003.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410032-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410032-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410032-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix Lỗi - BANT theo ngày khi kết thúc bệnh án thì tạo thêm XML130 có mã bệnh án làm tăng số lượng XML Reports (trùng dữ liệu XML)

![](https://i.imgur.com/2CaJhyJ.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/341

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @le-an-87, @nghivanbi  </sub>

> Mấy anh xem hỗ trợ gấp chức năng xóa các xml lỗi để bệnh viện thực hiện gửi dữ liệu và đối chiếu xml với cổng bảo hiểm mấy anh ơi.

- Nhờ @le-an-87 kiểm thử luồng công việc tại đây, vì nhiều chức năng ảnh hưởng tới số lượng hồ sơ lắm. [Các cập nhật liên quan tới số lượng hồ sơ XML](https://github.com/dh-hos/To_Lap_Trinh/issues/628)
- Hiện đã thấy cập nhật phiên bản cao hơn phiên bản chưa kiểm thử xong.
- Không kiểm thử cập nhật lại thì không giải quyết hết trường hợp này.

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
❔ Câu hỏi: 
1. anh cho em hỏi chức năng nào xóa được hồ sơ lỗi này để hướng dẫn cho bv xóa
2. trường hợp báo lỗi không đúng qui định thì đừng tiếp nhận nhé anh.
🔈 Giải đáp:
***

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @le-an-87  </sub>

- Hiện hông có nhé

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @le-an-87 , @nghivanbi  </sub>

- Còn việc nhờ kiểm thử tiếp là để hoàn thiện sản phẩm hơn thôi, nếu hông thực hiện thì cũng hổng sao nhé @le-an-87 , cái này chỉ là nhờ, chứ không phải qui trình đúng hay sai, mà không tiếp nhận nhé

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription.exe v.3.24.1003.4
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Prescription đã fix lỗi : bệnh nhân BANT theo ngày khi kết thúc không tại thêm XML NGOAI_TRU_XUAT_VIEN
  - Đã test bệnh nhân BANT theo ngày, BANT theo đợt, bệnh nhân ngoại trú: chỉ định CLS, cấp toa, in bảng kê chưa phát hiện lỗi mới.

- Hình ảnh: 

![](https://i.imgur.com/SaXcEOI.png)
![](https://i.imgur.com/mpu61oX.png)
![](https://i.imgur.com/oJ9VIRg.png)
![](https://i.imgur.com/K5n3isa.png)
![](https://i.imgur.com/DJp5KSS.png)
![](https://i.imgur.com/mZQf564.png)
![](https://i.imgur.com/UHtidMd.png)

**Comment by chauthanhtra** [comment]
### 🆘 **YÊU CẦU HỖ TRỢ**

- Hiện tại phần mềm Prescription đã fix lỗi tạo XML đối với BANT theo ngày khi kết thúc bênh án.

- Đối với các hỗ sơ bị lỗi trước đó nhờ code đưa ra hướng xử lý cho các đơn vị đã bị lỗi để fix lại, xóa các hồ sơ dư : Chức năng hay Script,... để hỗ trợ các đơn vị thống kê đúng số hồ sơ để gửi báo cáo

**Comment by nghivanbi** [comment]
> ### 🆘 **YÊU CẦU HỖ TRỢ**
> * Hiện tại phần mềm Prescription đã fix lỗi tạo XML đối với BANT theo ngày khi kết thúc bênh án.
> * Đối với các hỗ sơ bị lỗi trước đó nhờ code đưa ra hướng xử lý cho các đơn vị đã bị lỗi để fix lại, xóa các hồ sơ dư : Chức năng hay Script,... để hỗ trợ các đơn vị thống kê đúng số hồ sơ để gửi báo cáo

### 👌 ĐỒNG Ý THỰC HIỆN 👌
---------------------------------------------------------------------
👉 **Phân công thực hiện**: @ongtrieuhau
📘 **Nội dung**: Thực hiện hỗ trợ xử lý hồ sơ bị lỗi trước đó.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1004.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410040-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410040-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410040-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: **💼**: **_Lỗi - BANT theo ngày khi kết thúc bệnh án thì tạo thêm XML130 có mã bệnh án làm tăng số lượng XML Reports (trùng dữ liệu XML)_**

- ✨: ***Bổ sung chức năng xóa hồ sơ thừa so với danh sách hồ sơ 4210 trên chức năng kiểm tra chi phí***

- ![](https://i.imgur.com/diz3Crb.png) ![](https://i.imgur.com/Jvc3xOV.png) ![](https://i.imgur.com/yBv8fyT.png) ![](https://i.imgur.com/dV92tXP.png) ![](https://i.imgur.com/NM5DcTh.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/341

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Reports.exe v.3.24.1004.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410041-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410041-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410041-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: **💼**: **_Lỗi - BANT theo ngày khi kết thúc bệnh án thì tạo thêm XML130 có mã bệnh án làm tăng số lượng XML Reports (trùng dữ liệu XML)_**

- ✨: ***Bổ sung chức năng xóa hồ sơ thừa so với danh sách hồ sơ 4210 trên chức năng kiểm tra chi phí***

- ![](https://i.imgur.com/diz3Crb.png) ![](https://i.imgur.com/Jvc3xOV.png) ![](https://i.imgur.com/yBv8fyT.png) ![](https://i.imgur.com/dV92tXP.png) ![](https://i.imgur.com/NM5DcTh.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/341

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Reports.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm HospitalAdmin.exe v.3.24.1004.0
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Admin đã hỗ trợ xóa hồ sơ 4750 không có trong 4210

- Hình ảnh: 
  - Trước khi chạy kiểm tra chi phí 130
![](https://i.imgur.com/wDwTqWe.png)
![](https://i.imgur.com/4LzwYM5.png)
![](https://i.imgur.com/EngqMgu.png)
![](https://i.imgur.com/ZGv9J6z.png)

  - Sau khi chạy kiểm tra chi phí
![](https://i.imgur.com/tXvpxce.png)
![](https://i.imgur.com/G3jR04C.png)
![](https://i.imgur.com/5ago2ih.png)
![](https://i.imgur.com/95ULViN.png)

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Reports.exe v.3.24.1004.4
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  - Reports đã hỗ trợ chức năng xóa hồ sơ XML 4750 không có trong 4210

- Hình ảnh: 

  - Ảnh trước khi kiểm tra hồ sơ
![](https://i.imgur.com/LlyjM8H.png)
![](https://i.imgur.com/IRYgGdF.png)

  - Ảnh sau khi kiểm tra hồ sơ
![](https://i.imgur.com/B31SwsQ.png)
![](https://i.imgur.com/IriJ2w3.png)

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
