### ISSUE TITLE
Lỗi - CHỈNH NGÀY RA VIỆN KHI KẾT THÚC BANT ĐỢT VỀ THÁNG CŨ GÂY SAI THÔNG TIN XML

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#345]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_thanhtri_full_24092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Oi8YIgvrM)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

VD : Trường hợp người dùng kết thúc hồ sơ tại tháng 10 nhưng cấu hình cấu cứu để chỉnh ngày ra viện về ngày thuộc tháng 09 thì 4750 không tìm thấy hồ sơ để gửi

[Clip test](https://gofile.me/78TQg/ERZs3cPMX)

![image](https://github.com/user-attachments/assets/ac750a51-1310-4b15-b6ab-90503656d0f4)

trường hợp này khi xuất báo cáo thì 4750 không thấy hồ sơ nhưng 130 và 4210 tại Report vẫn có hồ sơ đó 
![image](https://github.com/user-attachments/assets/1d6e2f7f-93e4-4292-85fc-cac76e2607ad)
![image](https://github.com/user-attachments/assets/0dc07968-8367-448b-8d68-94e8b1d4dd1f)

4750 thì không thấy để gửi hồ sơ, xuất thử cả tháng 09 và 10 cũng không tìm thấy
![image](https://github.com/user-attachments/assets/fff37ad2-42f9-4655-8124-f7c3b3ba2f75)

Em cũng đã chạy Kiểm tra chi phí và xuất lại thì vẫn không thấy hồ sơ đó
![image](https://github.com/user-attachments/assets/25341de2-aa34-4cdf-8b95-aa598dd45de1)

Đây cũng là nguyên nhân gây ra lỗi sai thông tin tháng quyết toán trong malk gây ra cùng hồ sơ có 2 malk khác tháng của dữ liệu tháng 7 và 8.

✴️ Đề nghị fix lỗi xuất xml đúng thông tin khi người dùng chỉnh lại ngày ra.

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-10-14**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @nqhoa1005 @lqbinh1987 
- Đã xử lý theo luồng công việc này: [Yêu cầu - ĐIỀU CHỈNH PHÁT SINH XML KHI KẾT THÚC BANT ĐỢT](https://github.com/dh-hos/To_Lap_Trinh/issues/688)

**Comment by nqhoa1005** [comment]
✔️ **ĐÃ TIẾP NHẬN** 
👉 **Vui lòng chờ test lại**
