### ISSUE TITLE
Lỗi - BANT ĐỢT TRẢ VỀ TIẾP TỤC ĐIỀU TRỊ QUA THÁNG MỚI > LỆCH THÁNG QUYẾT TOÁN XML

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#346]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_thanhtri_full_24092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Oi8YIgvrM)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024008036` - _**MaKB**_: `2407001432` - _**MaBA**_: `N2024001911` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `19` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trường hợp BANT theo đợt đã kết thúc điều trị nhưng trả về sau đó điều trị tiếp đến qua tháng mới mới kết thúc lại sẽ lệch báo cáo 4750 và 4210 

BANT ra viện tháng 09 sau đó trả về điều trị và kết thúc lại ở tháng 10 
![image](https://github.com/user-attachments/assets/df0336f5-16a2-4025-bd8d-5ea994a13f8b)

tại thời điểm này xuất 4210 và 130 sẽ ra báo cáo đúng tháng 10, malk cũng là tháng 10
![image](https://github.com/user-attachments/assets/140cb8d3-169b-48f8-a69b-19acf2caff61)
![image](https://github.com/user-attachments/assets/93dcc29f-470d-485a-816d-18bf9e893864)

nhưng xuất 4750 trên admin thì vẫn ra tháng 09, malk tháng 09
![image](https://github.com/user-attachments/assets/ae03058d-5fea-4e5b-b4db-24a71a43531b)

✴️  Đề nghị fix lỗi khi trả về điều trị và kết thúc lại thì kiểm tra tháng ra viện và set đúng điều kiện để 4750 xuất đúng thông tin, tránh việc người dùng gửi bị sai hồ sơ XML

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-10-15.

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @nqhoa1005 
- Kiểm tra trên phiên bản mới nhất (vì có cập nhật tính năng này ở luồng công việc khác, do vừa tạo yêu cầu, vừa tạo lỗi...)
- Những trường hợp XML4750 chưa đúng, thì dùng chức năng ***`Kiểm tra chi phí`*** trên Reports hoặc Admin, để kiểm tra hồ sơ, để cập nhật lại XML4750 mới nhất.

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
👉 Đã kiểm soát tháng quyết toán theo https://github.com/dh-hos/dhg.hospitalprescription/issues/349
