### ISSUE TITLE
Lỗi - THIẾU BỆNH NHÂN KHI ĐĂNG KÝ TÁI KHÁM BANT NGÀY

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#348]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN NHI ĐỒNG CẦN THƠ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbnhidong_thieubantngay`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/7z29H7YkW)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019032639` - _**MaKB**_: `2408006827` - _**MaBA**_: `N2024000027` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `13` - _**MaDV**_: `10` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi áp dụng tham số : bant.nhanbenh = 1
Danh sách tiếp nhận BANT tại Reg không thấy tên BN để đăng ký tái khám
> kiểm tra thấy BN lần đăng ký gần nhất có đăng ký ngoại trú 

Bệnh án vẫn chưa kết thúc
![image](https://github.com/user-attachments/assets/a9a5dc89-6444-4aaa-88c7-b1d4e303ff40)

Danh sách đăng ký tái khám không có tên
![image](https://github.com/user-attachments/assets/c7992a36-5602-4bf5-b44f-f59170881d4b)

Lần đăng ký gần nhất là tiếp nhận ngoại trú bình thường
![image](https://github.com/user-attachments/assets/cad65c64-9959-4b1c-be21-a6e6298d221e)

✴️ Fix lỗi hiển thị thiếu bệnh nhân trong danh sách Đăng ký BANT

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-10-15.

**Comment by lequocthong29** [comment]
@nqhoa1005 Đúng rồi a

**Comment by nqhoa1005** [comment]
tạm thời đóng Git theo dỗi thêm, sẽ lên lại khi rà soát được chính xác nguyên nhân
