### ISSUE TITLE
Lỗi - Thông tư 36/2021

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#35]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_moduc_092022_fees_loadsaichiphi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022016863` - _**MaKB**_: `2209002054` - _**MaBA**_: `MaBA` _**NgayKCB**_: `27/09/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `09` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

    Khi in phiếu không cập nhật được chuỗi psdangky.kqcdoan = “Cấp thuốc theo Giấy Xác nhận điều trị nội trú của cơ sở khám bệnh, chữa bệnh: <ten_co_so_kcb>, ngày cấp: <ngaychungnhan_lao>”
    Khi Printer in rồi có cập nhật psdangky.kqcdoan đúng sau đó Prescription bấm in lại thì bị cập nhật lại sai psdangky.kqcdoan
    
![ảnh](https://user-images.githubusercontent.com/97272332/192668997-1b2d7cb9-6ad7-4670-9e4a-5a7b1f7f0eea.png)

**Comment by nghivanbi** [comment]
@ongtrieuhau cập nhật DLL in phiếu 01 nhé.

**Comment by ongtrieuhau** [comment]
> @ongtrieuhau cập nhật DLL in phiếu 01 nhé.

Cập nhật lên [oLibraries](https://github.com/dh-hos/oLibraries/commits/main) hết rồi nhé

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0930.1](http://www.fsend.vn/download/tBL4Rhj8liVPB7H9CpMC-R__wFAFFH37)
