### ISSUE TITLE
Lỗi - BANT THỂ HIỆN SAI NGÀY HẸN KHI TÁI KHÁM VÀ CHƯA KIỂM SOÁT NGÀY HẸN HỢP LỆ KHI LÊN XML

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#352]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV ĐKTP CẦN THƠ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dktpct_102024092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/4VVaBufOZ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019057744` - _**MaKB**_: `2409030675` - _**MaBA**_: `N2024011760` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BANT khi có chọn ngày hẹn đợt khám trước thì khi chọn lại bệnh nhân để tái khám lúc nào ngày hẹn cũng lớn hơn 1 ngày nhưng khi kết thúc điều trị thì XML lại lấy giá trị từ dữ liệu gây ra lỗi ngày hẹn khám lại phải lớn hơn ngày ra

- Ban đầu : trên form thể hiện ngày 15/10
![image](https://github.com/user-attachments/assets/f7c86623-16f7-4fdd-a825-b9cc8335797d)

- Thực tế trong dữ liệu ghi nhận đang ngày 10/10
![image](https://github.com/user-attachments/assets/bda3e225-ebcd-46f3-b2db-bfb78d161bac)

- khi chọn tái khám và kết thúc điều trị thì giá trị của ngày hẹn vẫn không thay đổi
![image](https://github.com/user-attachments/assets/868c20a8-c651-4c0a-896d-992ff3e1cb9f)

nhưng khi xuất 4750 thì XML đang lấy đúng giá trị đang lưu tại bnnoitru.ngaytaikham
![image](https://github.com/user-attachments/assets/9ec25091-5d8e-46df-b30c-740b700cbf11)

[Clip test](https://gofile.me/78TQg/wG39f8q8v)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-10-21.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.1018.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410181-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410181-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410181-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - BANT THỂ HIỆN SAI NGÀY HẸN KHI TÁI KHÁM

![](https://i.imgur.com/SUYkoCP.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/352

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
👉 Đã update lại giá trị khi ngày hẹn nhỏ hơn ngày thêm diễn biến

Bệnh nhân có ngày hẹn của đợt tái khám trước
![image](https://github.com/user-attachments/assets/50585b3e-cff9-4e52-8223-9bcc90869687)

Đã update lại nếu bnnoitru.ngaytaikham <= ngày thêm diễn biến
![image](https://github.com/user-attachments/assets/e5c2bf95-9430-43e0-a8c2-aba3d851a28e)

Không xuất XML14
![image](https://github.com/user-attachments/assets/3f65620e-b0df-4573-b434-09159216136d)
![image](https://github.com/user-attachments/assets/f31166b8-a0c3-4193-9667-ecb93a0242eb)

👉 Trường hợp có chọn ngày hẹn
![image](https://github.com/user-attachments/assets/12877dd0-96db-4830-845e-21e2cb1e64d2)
![image](https://github.com/user-attachments/assets/520f7b04-5166-4db1-9c55-34367f214e67)

---
✳️ Lần test : 1
