### ISSUE TITLE
Lỗi - Bệnh nhân không có xác nhận kết thúc khám không chỉnh được chẩn đoán sau khi Printer mở khóa chứng từ và 1 số lỗi khác

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#357]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dongtay_matphieunghiom_16102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/ZGMbVRtAY)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024037948` - _**MaKB**_: `2410002253` - _**MaBA**_: `MaBA` _**NgayKCB**_: `16/10/2024` - _**MaPhong**_: `H04` - _**MaDV**_: `K02` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. Khi tham số xacnhanketthuckham = 2 (Không cho chỉnh sửa khi đã kết thúc)
Bệnh nhân khám bệnh xong (___không___ có xác nhận kết thúc khám) -> in bảng kê 6556  , sau đó Printer mở khóa chứng từ bệnh nhân -> Prescription chỉnh chẩn đoán thì phần mềm báo bệnh nhân đã có xác nhận kết thúc khám và trong chức năng mở khóa kết thúc khám có check bệnh nhân đã kết thúc khám

![](https://i.imgur.com/fU2hKNJ.png)
![](https://i.imgur.com/T558iYA.png)
![](https://i.imgur.com/ToichI7.png)
![](https://i.imgur.com/1c3KEx2.png)

2. Khi tham số xacnhanketthuckham = 1 (Cảnh báo cho người dùng biết đã kết thúc hồ sơ bệnh án khi có chỉnh sửa)
Bệnh nhân đã kết thúc khám thì khi chỉnh sửa thì phần mềm cảnh báo bệnh nhân đã có kết quả điều trị và không cho chỉnh sửa -> theo mô tả tham số thì phần mềm chỉ cảnh báo cho người dùng biết đã kết thúc nhưng vẫn cho chỉnh sửa

![](https://i.imgur.com/K2BTxma.png)
![](https://i.imgur.com/3Ru0JTV.png)

3. Bệnh nhân đã in bảng kê rồi mở khóa chứng từ thì trong chức năng mở khóa kết thúc khám có check bệnh nhân đã kết thúc khám cho dù bệnh nhân đó có kết thúc khám hay không

![](https://i.imgur.com/MtIIJUg.png)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-10-21**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-10-21.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.1018.3 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410183-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410183-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410183-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Bệnh nhân không có xác nhận kết thúc khám không chỉnh được chẩn đoán sau khi Printer mở khóa chứng từ và 1 số lỗi khác

+ Khi tham số xacnhanketthuckham = 2 Bệnh nhân khám bệnh xong không có xác nhận kết thúc khám-> in bảng kê 6556 , sau đó Printer mở khóa chứng từ bệnh nhân -> Prescription chỉnh chẩn đoán thì phần mềm báo bệnh nhân đã có xác nhận kết thúc khám và trong chức năng mở khóa kết thúc khám có check bệnh nhân đã kết thúc khám.

![](https://i.imgur.com/NEF8gI7.png)

+ Khi tham số xacnhanketthuckham = 1 (Cảnh báo cho người dùng biết đã kết thúc hồ sơ bệnh án khi có chỉnh sửa).

![](https://i.imgur.com/pb02tvJ.png)

+ Bệnh nhân đã in bảng kê rồi mở khóa chứng từ thì trong chức năng mở khóa kết thúc khám có check bệnh nhân đã kết thúc khám cho dù bệnh nhân đó có kết thúc khám hay không.

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/357

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### ✔️ **ĐÃ TIẾP NHẬN**
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '28/10/2024'.

**Comment by chauthanhtra** [comment]
### ☑️ **KẾT QUẢ TEST**
***
Phần mềm Prescription.exe v.3.24.1021.3
***
### 🆗 **Lỗi, yêu cầu đã hoàn thành .**

- Nội dung: 

  1. Đã fix Khi tham số xacnhanketthuckham = 2 (Không cho chỉnh sửa khi đã kết thúc). Đã cho chỉnh sửa khi mở khóa bảng kê khi bệnh nhân không có xác nhận kết thúc khám

- Hình ảnh: 
![](https://i.imgur.com/0lQNYTP.png)
![](https://i.imgur.com/TAmlHwD.png)


- Nội dung: 

  2. Đã fix Khi tham số xacnhanketthuckham = 1 (Cảnh báo cho người dùng biết đã kết thúc hồ sơ bệnh án khi có chỉnh sửa). Đã cho chỉnh sửa chẩn đoán và có cảnh báo xác nhận kết thúc khám

- Hình ảnh: 

![](https://i.imgur.com/ujlOGaO.png)

- Nội dung: 

  3. Đã fix Bệnh nhân đã in bảng kê rồi mở khóa chứng từ thì trong chức năng mở khóa kết thúc khám đã xác nhận đúng trạng thái kết thúc khám  

- Hình ảnh: 
![](https://i.imgur.com/5GUoJYt.png)
![](https://i.imgur.com/Oww6CvW.png)

**Comment by chauthanhtra** [comment]
### ✅ **HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
