### ISSUE TITLE
Lỗi - BANT NGÀY, BA OPC XUẤT HIỆN NHIỀU DÒNG TẠI DANH SÁCH ĐĂNG KÝ

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#359]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV ĐKTP CẦN THƠ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dktpct_102024092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/4VVaBufOZ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2017094547` - _**MaKB**_: `MaKB` - _**MaBA**_: `N2017003616` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `50` - _**MaDV**_: `30` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi bệnh nhân có BANT thanh toán ngày hoặc BA OPC nếu có 1 đợt đăng ký khám thường thì trên lưới Đăng ký OPC/Đăng ký BANT sẽ có 2 dòng với thông tin cũng khác nhau nhưng có 1 dòng không liên quan đến bệnh án.
![image](https://github.com/user-attachments/assets/791364b5-f997-4070-987e-ec34ffb1bebe)
![image](https://github.com/user-attachments/assets/4efaf366-5e58-4666-8e5a-be42b65174de)

Dòng không có nơi giới thiệu là đợt khám thường không liên quan đến bệnh án
![image](https://github.com/user-attachments/assets/16a69cbf-0897-49ba-90ff-d198ae464ea4)

- Đã kiểm tra BANT ngày và BA OPC đều bị tương tự
✴️ Xử lý và kiểm soát lại để đúng dánh sách Đăng ký để tránh khi chọn nhằm dòng thì đợt khám sẽ lệch thông tin.

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-10-22.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.1022.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410221-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410221-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410221-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - BANT NGÀY, BA OPC XUẤT HIỆN NHIỀU DÒNG TẠI DANH SÁCH ĐĂNG KÝ

![](https://i.imgur.com/xGC2sBD.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/359

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
👉 Đã xử lý không xuất hiện nhiều dòng các bệnh nhân có đăng ký khám thường gần nhất
![image](https://github.com/user-attachments/assets/fc26a8bd-e263-4041-9ee7-d5eccdbe7db0)
---
✳️ Lần test : 1
