### ISSUE TITLE
Yêu cầu - Hỗ trợ Thông tư 36/2021/TT-BYT

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#36]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/9/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_kqcls`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
1. Đề xuất thêm chức năng cho điều chỉnh từ bệnh bình thường sang bệnh Lao và ngược lại.

2. Thêm dấu hiệu nhận biết bệnh nhân Lao giống như bệnh nhân cấp cứu.

3. Trường hợp bệnh nhân có mã bệnh kèm theo thì trường 13 XML sẽ có mã bệnh kèm theo nhưng theo cv thì không có yêu cầu ghép tên bệnh đối với bệnh nhân khám Lao. trong mô tả cũng không có yêu cầu ghép tên chẩn đoán.

```
![image](https://user-images.githubusercontent.com/96155021/192675048-29577da2-a185-42af-92b1-fb17c974dc12.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: v3.22.09.28.2

**Comment by le-an-87** [comment]
![image](https://user-images.githubusercontent.com/96155021/192704206-9bbbe8be-11d3-4a00-adaa-9ddeffc3c984.png)
không tải được nhe anh!
anh cho cái link vào đây nhấp link tải cho tiện anh ơi

**Comment by nghivanbi** [comment]
![image](https://user-images.githubusercontent.com/91751241/192704740-7e36a2ef-5498-4031-94e0-5c547c967031.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0928.3](http://www.fsend.vn/download/yT9PAh4t5-I0XF_p1afhalLbrHP_U9qU)

**Comment by le-an-87** [comment]
Prescription in bảng kê vẫn chưa được nhe anh!
anh cập nhật link là bản V3 mà bấm vào tải thì là bản V2

**Comment by le-an-87** [comment]
đã cập nhật
