### ISSUE TITLE
Lỗi - Mất số liệu tạm xuất khi chỉnh toa

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#362]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_phuoclong_bli_full_18092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `port_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/GGf0SgvBb)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024017519` - _**MaKB**_: `2410000003` - _**MaBA**_: `MaBA` _**NgayKCB**_: `20/10/2024` - _**MaPhong**_: `00` - _**MaDV**_: `02` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi thêm thuốc lần đầu, số lượng có cập nhật cho cột Chờ xuất bảng tồn kho, nhưng sau khi chỉnh thuốc, tăng hoặc giảm số lượng, sau đó lưu lại nhưng phần mềm không cập nhật lại số lượng chờ xuất sau khi khi chỉnh, mà cập nhật lại giá trị 0(**Lưu ý chổ này nếu có chờ xuất của BN khác thì phần mềm cũng cập nhật về 0 luôn**) => các BS khác ra toa ngay thuốc này nữa thì gây ra tình trạng **tổng chờ xuất > tồn kho** => cập nhật phiếu chưa lãnh chưa trả và khi in phiếu 6556 trừ kho bị báo lỗi đối với với **Check pstonkho_check_toncuoi_dh_chk3**
![image](https://github.com/user-attachments/assets/86631b41-c28f-4185-9358-98be42182f4e)

![image](https://github.com/user-attachments/assets/c460c827-4651-44f7-90cf-168e87a69168)

![image](https://github.com/user-attachments/assets/4b18654b-4233-4db8-9f83-7a1f89c1c4ec)

**Comment by ongtrieuhau-dh** [comment]
## <sub><sub>☑️ Đã tiếp nhận</sub></sub>

- ⌛ Thời gian hoàn thành dự kiến: **2024-10-28**

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-10-28.

**Comment by lqbinh1987** [comment]
📢Anh @nghivanbi , anh @ongtrieuhau-dh 
----------
- Đề ngị xử lý sớm cái này vì hiện tại BV phản ánh quá, trả về bản cũ thì bị nhiều lõi khác...

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @lqbinh1987  </sub>

- Luồng yêu cầu này phát sinh sau nên phải chờ.
- Có luồng công việc đang theo phần này [Yêu cầu - Phần tích, mô tả, thực hiện qui trình cho thuốc tủ và cập nhật tồn kho tủ trực](https://github.com/dh-hos/To_Lap_Trinh/issues/662), nếu nằm trong luồng này có thể ưu tiên hơn.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.1022.4 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410224-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410224-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32410224-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Mất số liệu tạm xuất khi chỉnh toa

![](https://i.imgur.com/FF5Bftg.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/362

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
💡KIỂM TRA SẢN PHẨM💡
***
Mô tả lỗi:
Tồn kho mặt hàng còn 34, 2 máy cùng thao tác trên mặt  đó, thao tác thêm lên lưới cùng 1 thời điểm (số lượng 2 máy công lại > tồn cuối) vẫn được, sau đó lưu vẫn được luôn.
![image](https://github.com/user-attachments/assets/8046d4c8-f059-41ad-9953-26e27b157762)
![image](https://github.com/user-attachments/assets/bfeb5f4e-c8c4-4cc8-9f4a-9c4436bcb4de)
 ![image](https://github.com/user-attachments/assets/e968e380-2ae0-411f-9380-89228b9ce1a3)

***
Thông tin bệnh nhân(nếu có)
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dktpct_102024092024data`
- ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/4VVaBufOZ)
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024068456; 2018019056` - _**MaKB**_: `2410009163; 2410009162` - _**MaBA**_: `MaBA` _**NgayKCB**_: `23/10/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

***
❌ Không thể tiếp tục kiểm tra sản phẩm, **tạm dừng kiểm tra.**

**Comment by lequocthong29** [comment]
📣
-----------------
nhờ a @lqbinh1987 cung cấp video test để nắm rõ hơn thao tác gây lỗi 
E đã test trường hợp trên và chưa tìm thấy lỗi 
[Video test](https://gofile.me/78TQg/xKCAzPWNA)

**Comment by nqhoa1005** [comment]
Phối hợp test 2 máy thì đã chặn được trường hợp ra toa lên lưới thì khi lưu toa cũng đã chặn 1 máy rồi anh @nghivanbi , các trường hợp khác đang test thêm

**Comment by lqbinh1987** [comment]
Tạm thời em close git này, đã mở git mới [tại đây](https://github.com/dh-his/Ghi_Nhan_Loi/issues/13).
