### ISSUE TITLE
Lỗi - CÔNG KHÁM CHƯA THU TIỀN KHÔNG CHUYỂN ĐƯỢC VÀO NỘI TRÚ

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprescription#366]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51214`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Nội Tiết**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_ttntqn_102024chuyencknoitru`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/4eb885AWB)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024009662` - _**MaKB**_: `2410001802` - _**MaBA**_: `MaBA` _**NgayKCB**_: `08/10/2024` - _**MaPhong**_: `.06` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Thao tác chuyển chi phí vào nội trú khi nhập viện hiện tại nhiều trường hợp chuyển tất cả chỉ còn lại công khám không có thông báo quản lý nên sót nhiều chi phí.
- Qua kiểm tra thì hiện giờ khi chuyển CLS vào nội trú thì báo thành công nhưng công khám vẫn còn chỉ có cách đăng nhập tài khoản admin vào để chuyển bằng chức năng riêng mới chuyển vào được.

VD : khi dùng chức năng chuyển CLS vào nội trú thì có thông báo nhưng bấm đồng ý thì công khám không chuyển vào được.
![image](https://github.com/user-attachments/assets/30e5db64-435e-47bc-8cc5-7a94c02fc64b)

Công khám không có phiếu thu 
![image](https://github.com/user-attachments/assets/db5f799d-7869-4e00-bb7a-fc682c95f2c4)

khi đăng nhập tài khoản người dùng thì không có chức năng chuyển
![image](https://github.com/user-attachments/assets/90622ea1-f994-4791-9ef5-e81e69e401f8)

chỉ có cách đăng nhập tài khoản admin mới chuyển vào được.
![image](https://github.com/user-attachments/assets/9c94490f-b207-450b-9ebb-ec790d45d82c)

- Nếu công khám chưa chuyển vào được thì tên BN vẫn xuất hiện trên Printer 
👉 nếu in tại printer trường hợp này sẽ không có XML để thanh toán nên bị mất chi phí hoàn toàn công khám này.
![image](https://github.com/user-attachments/assets/e25ff1a7-d1c7-4c50-ba72-4038e79b0c1e)

✴️ Đề nghị xem xét chuyển chi phí bao gồm công khám vào nội trú trong 1 lần chuyển, không phân biệt tài khoản admin mới có quyền chuyển CK vào để đơn vị tránh thất thoát chi phí.

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-10-30.

**Comment by lequocthong29** [comment]
- Trường hợp này là công khám được chuyển ra từ ngoại trú
![](https://i.imgur.com/XWIou7E.png)
- Nguyên nhân không chuyển vào NT được là do chưa mở khóa chứng từ.( dain = 1 )
![](https://i.imgur.com/R39rDVa.png)
Nhờ a @nqhoa1005  kiểm tra lại

**Comment by nqhoa1005** [comment]
❗❗ **TRAO ĐỔI** ❗❗
- ✳️ chổ này là người dùng thử chuyển chi phí ra rồi chuyển vào lại thử để lấy công khám vào nội trú mà không vô
- 👉  chổ này có 2 vấn đề :
- 1. Nếu công khám bị in phiếu nhằm khiến chidinhcls.dain = 1 của công khám thì có thông báo cho người dùng biết để tự mở khoá giải quyết.
- 2. Khi chuyển vào thì tất cả CLS chưa thu sẽ chuyển vào nội trú bao gồm cả công khám.

**Comment by onghaup** [comment]
### 📣📣📣 Prescription.exe v.3.24.1030.0 <sub><sup><sup>[⬇️OneDrive](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32410300-OneDrive.json) [⬇️GoogleStorage](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32410300-GoogleStorage.json) [⬇️NasDHSolutions](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32410300-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Công khám chưa thu tiền không chuyển vào được nội trú

- Cảnh báo công khám đã in

![](https://i.imgur.com/foPWWMo.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/366
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/tolaptrinh/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
❌ **CHƯA ĐẠT YÊU CẦU** ❌ 
- ❗❗ Thông báo chỉ áp dụng khi dùng nút chuyển CK chỉ có tài khoản admin mới hiển thị 
![image](https://github.com/user-attachments/assets/0a3c6b83-04e9-45d8-99fa-17f17257b6c6)
![image](https://github.com/user-attachments/assets/571e1f7a-be97-4826-bb9c-6c48d35826f1)

Người dùng bình thường khi chuyển vào vẫn không có thông báo để biết nguyên nhân không chuyển được công khám
👉 Kiểm tra và thông báo tại nút chuyển chung để người dùng đều nhận được thông báo
![image](https://github.com/user-attachments/assets/c2037c5d-6a03-4fd6-a85b-ab9d359068db)

---
- ✳️ Lần test : 1
- ❗❗ Dừng test các chức năng liên quan.

**Comment by onghaup** [comment]
### 📣📣📣 Prescription.exe v.3.24.1101.3 <sub><sup><sup>[⬇️OneDrive](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411013-OneDrive.json) [⬇️GoogleStorage](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411013-GoogleStorage.json) [⬇️NasDHSolutions](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411013-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Công khám chưa thu tiền không chuyển vào được nội trú

- Cảnh báo công khám đã in

![](https://i.imgur.com/PnTdtuY.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/366
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/tolaptrinh/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by onghaup** [comment]
### 📣📣📣 Prescription.exe v.3.24.1101.5 <sub><sup><sup>[⬇️OneDrive](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411015-OneDrive.json) [⬇️GoogleStorage](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411015-GoogleStorage.json) [⬇️NasDHSolutions](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32411015-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Công khám chưa thu tiền không chuyển vào được nội trú

- Cảnh báo công khám đã in

![](https://i.imgur.com/PnTdtuY.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/366
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/tolaptrinh/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
👉 Đã thông báo tại chức năng chuyển CLS vào nội trú
clip test 
https://github.com/user-attachments/assets/c13d4fc0-f04f-4d9c-95d5-ace610b6096d

@lqbinh1987 
---
✳️ Lần test : 1
