### ISSUE TITLE
Lỗi - Ordinal không in được số thứ tự bệnh nhân

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprescription#370]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/11/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện đa khoa  Quận Thốt Nốt**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbthotnot_kios2`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Ukii0h6Cr)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

Khi trong bảng dmphankhu cột bhyt=0 thì khi quét thẻ BHYT trên Ordinal không in ra được số thứ tự bệnh nhân.
Video như hình dưới:

https://github.com/user-attachments/assets/b14984eb-e927-48f3-bed2-ddec2bf73bc3

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-11-12.

**Comment by onghaup** [comment]
### 📣📣📣 RegisterOrdinal.exe v.1.24.1112.0 <sub><sup><sup>[⬇️OneDrive](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FRegisterOrdinalexe%2F12411120-OneDrive.json) [⬇️GoogleStorage](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FRegisterOrdinalexe%2F12411120-GoogleStorage.json) [⬇️NasDHSolutions](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FRegisterOrdinalexe%2F12411120-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Fix - Lỗi Ordinal Khi trong bảng dmphankhu cấu hình bhyt=0 thì khi quét thẻ BHYT trên Ordinal không in ra được số thứ tự bệnh nhân, thông tin tự động bị xóa mất

![](https://i.imgur.com/hHo7AvF.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/370
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/tolaptrinh/RegisterOrdinal.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by onghaup** [comment]
### 📣📣📣 RegisterOrdinal.exe v.1.24.1112.0 <sub><sup><sup>[⬇️OneDrive](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FRegisterOrdinalexe%2F12411120-OneDrive.json) [⬇️GoogleStorage](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FRegisterOrdinalexe%2F12411120-GoogleStorage.json) [⬇️NasDHSolutions](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FRegisterOrdinalexe%2F12411120-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Fix - Lỗi Ordinal Khi trong bảng dmphankhu cấu hình bhyt=0 thì khi quét thẻ BHYT trên Ordinal không in ra được số thứ tự bệnh nhân, thông tin tự động bị xóa mất

![](https://i.imgur.com/hHo7AvF.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/370
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/tolaptrinh/RegisterOrdinal.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
@lequocthong29 
Vẫn chưa được nghen Thống !
1. Khi quét thẻ BHYTxong chưa in được số thứ tự.
2. Là khi quét thẻ BHYT xong chưa clear được text box như hình dưới

https://github.com/user-attachments/assets/55f4be35-863c-46ea-9357-7c26159fa8e7

**Comment by lequocthong29** [comment]
@hvtuan1987  a có cấu hình bhyt = 1 hỏng a, có cấu hình mới quét xong tự động in stt nha

**Comment by hvtuan1987** [comment]
@lequocthong29 Cấu hình =1 thì quyét CCCD xong không chọn được quầy vì lúc này nút Quầy đó bị ẩn

**Comment by hvtuan1987** [comment]
@lequocthong29 Anh thử =1 cũng hong được luôn nghen Thống !

**Comment by lequocthong29** [comment]
> @lequocthong29 Anh thử =1 cũng hong được luôn nghen Thống !

cho e xin chuỗi quét bị lỗi

**Comment by hvtuan1987** [comment]
@lequocthong29 
Nà á !
9210020211|48c3a02056c4836e205475e1bâ56e|02/10/1987|1|-|92 - 004|01/01/2024|-|25/12/2023|92019210020211|-|4|e20/09/2e68206ec9e1bb81752c205468c3a06e68207068e1bb912043e1bâ76e205468c6a1|$

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-11-13.

**Comment by onghaup** [comment]
### 📣📣📣 RegisterOrdinal.exe v.1.24.1112.1 <sub><sup><sup>[⬇️OneDrive](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FRegisterOrdinalexe%2F12411121-OneDrive.json) [⬇️GoogleStorage](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FRegisterOrdinalexe%2F12411121-GoogleStorage.json) [⬇️NasDHSolutions](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FRegisterOrdinalexe%2F12411121-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Fix - Lỗi Ordinal Khi trong bảng dmphankhu cấu hình bhyt=0 thì khi quét thẻ BHYT trên Ordinal không in ra được số thứ tự bệnh nhân, thông tin tự động bị xóa mất

- 🐛: không khóa phân khu cấu hình bhyt = 1.

![](https://i.imgur.com/Hj8HniN.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/370
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/tolaptrinh/RegisterOrdinal.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by onghaup** [comment]
### 📣📣📣 RegisterOrdinal.exe v.1.24.1112.1 <sub><sup><sup>[⬇️OneDrive](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FRegisterOrdinalexe%2F12411121-OneDrive.json) [⬇️GoogleStorage](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FRegisterOrdinalexe%2F12411121-GoogleStorage.json) [⬇️NasDHSolutions](https://tolaptrinh.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FRegisterOrdinalexe%2F12411121-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Fix - Lỗi Ordinal Khi trong bảng dmphankhu cấu hình bhyt=0 thì khi quét thẻ BHYT trên Ordinal không in ra được số thứ tự bệnh nhân, thông tin tự động bị xóa mất

- 🐛: không khóa phân khu cấu hình bhyt = 1.

![](https://i.imgur.com/Hj8HniN.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/370
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/tolaptrinh/RegisterOrdinal.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
-  ✔️ **Xác nhận** 
Ordinal đã in được số thứ tự khi phân khu có cột bhyt=0
![image](https://github.com/user-attachments/assets/319b6e9d-e934-4a78-8805-04c74d7cc58a)
