### ISSUE TITLE
Yêu cầu - Lập DS hội chẩn mẫu.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#39]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Mắt CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvmat_t2`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu lập danh sách hội chẩn mẫu trước.
Khi nào lập hội chẩn chỉ cần chọn danh sách có sẳn ra và chỉnh sửa lại(nếu cần).
_Chức năng này Treatment đã có, giờ ngoại trú có hội chẩn nhiều nên BV yêu cầu hỗ trợ như nội trú._

![image](https://user-images.githubusercontent.com/99630883/193716715-302ad1a3-0cb0-4cc6-aef8-e7fe16f54558.png)
![image](https://user-images.githubusercontent.com/99630883/193716798-5076a270-ba69-415b-8608-2bcfb6150ee0.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0228.1](http://www.fsend.vn/download/e2pSEepabS6zNtVQvrS0Caj9IALg646J)
