### ISSUE TITLE
Yêu cầu - PK Đông Tây - xóa chẩn đoán củ khi lick bệnh nhân tái khám

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#4]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dongtay_chinhdienbien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bệnh án ngoại trú:
- khi chọn bệnh nhân tái khám xóa hết các chẩn đoán của lần khám trước.
```
khi chọn bệnh nhân tái khám
![image](https://user-images.githubusercontent.com/96155021/177461205-5f15c616-51fa-4cb3-b8f1-59944a060877.png)
Yêu cầu xóa các chẩn đoán củ
![image](https://user-images.githubusercontent.com/96155021/177461387-f3d48b3e-1062-4558-913f-3929e7b47d41.png)

**Comment by le-an-87** [comment]
+ Khi chuyển khoa -> thêm diễn biến thì Prescription không lấy đúng phân loại bệnh cấu hình ở máy đó. Mà giữ lại phân loại bệnh củ

**Comment by nghivanbi** [comment]
Đã trao đổi IT thống nhất xóa chẩn đoán phụ và chấn đoán yhct khi tái khám. Check lại phiên bản cập nhật 20220712 nha

**Comment by le-an-87** [comment]
Prescription khi tái khám đã xóa chẩn đoán phụ và chẩn đoán yhct!
