### ISSUE TITLE
Yêu cầu - Chuyển tạm ứng vào nội trú.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#42]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `60015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BN Hàm Thuận Nam BTN**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_nambinthuan_chuyentuvaonoitru`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

BN đăng ký khám ngoại trú, có **tạm ứng**, sau đó nhập viện.
BV yêu cầu chuyển tạm ứng vào nội trú.
_Chức năng chuyển phiếu tạm ứng vào nội trú lúc trước có, nhưng hiện tại bản mới test không chuyển được._

![image](https://user-images.githubusercontent.com/99630883/194019135-84e088ce-0404-4ced-930e-91ef06d7fbe5.png)

**Comment by nghivanbi** [comment]
Prescription test thử cụ thể một bệnh án gọi hàm với giá trị như sau:
DLLFees.ChuyenCPhiTamUng.ChuyenVao(2022000001,2210001879, 2022000002, admin, S33, 10, 2002)

![image](https://user-images.githubusercontent.com/91751241/198193397-3b63aa1e-9af8-4746-9ebe-30ec1061a63f.png)
![image](https://user-images.githubusercontent.com/91751241/198193441-f9f2c96a-f513-4de5-b2bd-d0f34de2fdc1.png)

Hậu kiểm tra lại DLL nha.

**Comment by ongtrieuhau** [comment]
- Trên form cũng có dữ liệu đã chuyển vào
![image](https://user-images.githubusercontent.com/91751241/198193441-f9f2c96a-f513-4de5-b2bd-d0f34de2fdc1.png)
- Dữ liệu đã ghi nhận tạm ứng trong nội trú rồi mà. 
![image](https://user-images.githubusercontent.com/58720300/198480242-f706f99f-34bb-46f2-9354-748f5c48a13b.png)

Như vậy, kiểm tra chuyện gì ở đây? @nghivanbi @lqbinh1987

**Comment by nghivanbi** [comment]
Chuyển không được tạm ứng á

**Comment by ongtrieuhau** [comment]
Chuyển là chuyển giá trị phiếu tạm ứng, chứ phiếu tạm ứng bệnh nhân vẫn giữ, những thông tin trên đó đâu có thay đổi được, nên phiếu đó vẫn giữ lại, và chuyển số tiền thừa vào trong thôi. Ở đây báo lỗi vấn đề gì. Cụ thể trên phần mềm báo lỗi như thế nào. Còn nếu hổng nắm qui trình thì phải hỏi chứ sao báo lỗi hay yêu cầu làm gì á.
