### ISSUE TITLE
Yêu cầu - BV Lấp Vò: Yêu cầu không cập nhật lại giờ chỉ định công khám theo giờ vào viện khi chuyển công khám vào nội trú và lấy giờ đăng ký làm giờ khám trên phiếu khám bệnh vào viện

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#47]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87005`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Lấp Vò**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_lapvo_nhapvien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

- Hiện tại phần mềm sẽ tự động chuyển công khám vào nội trú theo tham số và cập nhật lại giờ chỉ định của công khám là giờ nhập viện
-> Yêu cầu Không cập nhật lại giờ chỉ định của công khám khi chuyển vào nội trú

- Ngày giờ khám bệnh trên phiếu khám bệnh vào viện đang lấy ngày giờ vào viện
-> Yêu cầu Lấy ngày giờ đăng ký KCB làm ngày giờ khám bệnh trên phiếu khám bệnh vào viện

**Comment by nghivanbi** [comment]
- Cập nhật:
Prescription: [v3.22.1018.1](http://www.fsend.vn/download/3MWTRPmBbdl0lOtpeN8bd_BEZkGf80S1)

**Comment by chauthanhtra** [comment]
tải về Prescription 14/10 anh ơi.
![ảnh](https://user-images.githubusercontent.com/97272332/196352355-8a5e5568-41e7-4df2-b5ec-664d3375d815.png)

**Comment by nghivanbi** [comment]
http://www.fsend.vn/download/DKHjLQNpomdB6PpNe8QY72VTWlNajUcW

**Comment by chauthanhtra** [comment]
link Register anh ơi
![ảnh](https://user-images.githubusercontent.com/97272332/196355828-819dfcbb-8fa3-4c78-a12e-9ed292653910.png)

**Comment by nghivanbi** [comment]
http://www.fsend.vn/download/D5ESkaLfvgTaWRLhMTfqEyZ9Y2Sj3C6M

**Comment by chauthanhtra** [comment]
- Phiếu khám vào viện được rồi anh
- Anh làm luôn chổ này luôn nha
"Hiện tại phần mềm sẽ tự động chuyển công khám vào nội trú theo tham số và cập nhật lại giờ KCB của công khám là giờ nhập viện
-> Yêu cầu Không cập nhật lại giờ chỉ định của công khám khi chuyển vào nội trú"

**Comment by chauthanhtra** [comment]
ok rồi anh
