### ISSUE TITLE
Lỗi - Toa vật tư nhập được nhiều hơn 2 số lẻ

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#5]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **@nghivanbi**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Quãng Ngải**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_quangngai_full_amkho_new`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1N672BCHLMXP3xrDsQmlX9EXCSGvLniDv/view?usp=sharing)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022025079` - _**MaKB**_: `2207000904` - _**MaBA**_: `MaBA` _**NgayKCB**_: `06/07/2022` - _**MaPhong**_: `A1-17` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

![ảnh](https://user-images.githubusercontent.com/97272332/177487443-38e5c2ed-9d87-415b-b3fa-31d3eb4b98a4.png)
![ảnh](https://user-images.githubusercontent.com/97272332/177487907-ed1850c9-1b9b-4b48-966b-e94f3e0664a0.png)
![ảnh](https://user-images.githubusercontent.com/97272332/177489914-892ef71a-efaa-4c20-875e-2a799cd6e0ec.png)

Dữ liệu pshdxn không ghi nhận được số lượng nhưng vẫn tính thành tiền

**Comment by chauthanhtra** [comment]
- mất nút "đóng"
![ảnh](https://user-images.githubusercontent.com/97272332/178636175-137101b7-9d90-4729-9f09-301140f5247d.png)

- mẫu in chưa cập nhật số lượng
![ảnh](https://user-images.githubusercontent.com/97272332/178636301-f43b7d28-b5aa-4da3-b8ac-caa9a928a5a9.png)
![ảnh](https://user-images.githubusercontent.com/97272332/178636320-d6eb27e7-2c01-4bae-b0a8-53b83c5015a8.png)
![ảnh](https://user-images.githubusercontent.com/97272332/178636380-5f8f9547-e939-405c-a9ed-24b10179ae8f.png)
![ảnh](https://user-images.githubusercontent.com/97272332/178636428-6c8df772-7093-4f39-bc38-a0303899429d.png)
![ảnh](https://user-images.githubusercontent.com/97272332/178636680-39c1cc86-356d-4d87-8bbc-dfba390d7f93.png)
![ảnh](https://user-images.githubusercontent.com/97272332/178636861-cd3fa254-ecf9-4adf-9239-5ef93203fcbe.png)

**Comment by chauthanhtra** [comment]
- Các mẫu in bị làm tròn số lượng, nên không thấy được số lượng thập phân
![ảnh](https://user-images.githubusercontent.com/97272332/178640580-da3de0d1-f79f-4036-9e49-e38e7a8575cc.png)

**Comment by nghivanbi** [comment]
Mấy lỗi phát sinh thêm em báo lên đây luôn nha @chauthanhtra

**Comment by chauthanhtra** [comment]
- Phát sinh thêm 1 số lỗi ở các nút form toa vật tư ở phần mềm mới
-- Bấm thêm -> bỏ qua -> thêm lại thì báo lỗi khi đóng thông báo này thì cho nhập toa nhưng không nhập được số lẻ phải tắt form mở lại
![ảnh](https://user-images.githubusercontent.com/97272332/181668670-eff11c54-442b-4e67-8a0f-a7355842e2c4.png)
![ảnh](https://user-images.githubusercontent.com/97272332/181668729-bd6cc556-51d9-4fbc-8409-8fc102d9be25.png)

-- Nút In toa không hoạt động
![ảnh](https://user-images.githubusercontent.com/97272332/181668879-d432dc79-21a4-4c44-bfdf-a38618729ceb.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0805.1](http://www.fsend.vn/download/wA5jMN8Wk2mSsfyOj-XAYoYJQY9KaxeK)

**Comment by chauthanhtra** [comment]
được rồi nha anh
