### ISSUE TITLE
Lỗi - Giờ khám bệnh trên phiếu nhập viện lệch giữa Treatment và Prescription

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#52]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ sản cần thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_phieuvaovien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022087542` - _**MaKB**_: `2210011733` - _**MaBA**_: `014075` _**NgayKCB**_: `24/10/2022` - _**MaPhong**_: `06` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2022` - _**MadvNHAPVIEN**_: `22` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Giờ khám bệnh trên phiếu nhập viện lệch giữa Treatment và Prescription.
-> Bệnh viện đề nghị chỉnh lại cho đồng bộ.

```
Form nhập viện
![image](https://user-images.githubusercontent.com/96155021/197678790-15a33a46-cb2c-4a68-9947-52a4d36cd3f1.png)

Phiếu vào viện Treatment và Prescription
![image](https://user-images.githubusercontent.com/96155021/197678829-b99edb40-1c3f-429a-8756-2a5ceb67ebce.png)

**Comment by vuongdh** [comment]
@nghivanbi coi có xài tham số gì không? hiện tại chỉ có BV Tim Mạch CT là lấy ngày đăng ký làm ngày khám bệnh (vào viện) tất cả bv còn lại là lấy ngày vào viện (làm ngày khám bệnh)

**Comment by nghivanbi** [comment]
Thống nhất hỗ trợ cho bệnh viện mẫu tự thiết kế, để bệnh viện tự chọn.

**Comment by le-an-87** [comment]
01/04/2023!
