### ISSUE TITLE
Yêu cầu - Thay đổi nội dung Label trên form lập phiếu nghỉ ốm. 

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#53]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_thanhtri_giaychungsinh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu thay đổi nội dung label **Lý do nghỉ việc** thành **Chẩn đoán và phương pháp điều trị**, mục đích cho giống với nội dung trên mẫu 01(Giấy chứng nhận nghỉ việc hưởng bảo hiểm xã hội)
Lý do, vì để **Lý do nghỉ việc** như vậy có nhiều BS hiểu nhầm, tự gõ nội dung vào thì lại không đúng với hướng dẫn của BHXH.
![image](https://user-images.githubusercontent.com/99630883/197679300-7abefa0d-2e10-4617-b496-8698ba33d540.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.10.26.1](http://www.fsend.vn/download/sxmYX5GsN643vyJbhP2aXI56l3_cP9TO)
