### ISSUE TITLE
Lỗi - Số ngày điều trị HS bệnh án ngoại trú YHCT bị âm

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#55]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95005`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Hồng Dân BL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_hongdan_hsyhct`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022002563` - _**MaKB**_: `2210011859` - _**MaBA**_: `N2022001362` _**NgayKCB**_: `02/11/2022` - _**YHCT2**_: `MaPhong` - _**MaDV**_: `25` - _**ThangKT**_: `11` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh vào viện ngày 27/10/2022 - ra viện 02/11/2022 nhưng số ngày điều trị trong hs bệnh án YHCT bị âm -24

```
trang in hs
![image](https://user-images.githubusercontent.com/96155021/199384017-9eae4471-0ac8-44cf-a42c-72a2da697110.png)

**Comment by nghivanbi** [comment]
https://github.com/dh-hos/dhg.hospitalprescription/issues/64

**Comment by le-an-87** [comment]
đã fix!
