### ISSUE TITLE
Lỗi - PK Medic SG: lỗi khi xem, in toa thuốc trên Prescription 1/11

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#56]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **2/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77120`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA MEDIC SÀI GÒN**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_medic1_toathuoccu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022002372` - _**MaKB**_: `2211000182` - _**MaBA**_: `MaBA` _**NgayKCB**_: `2/11/2022` - _**MaPhong**_: `P14` - _**MaDV**_: `10` - _**ThangKT**_: `11` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Khi xem hoặc in toa thuốc cũ trên Prescription 1/11/2022 thì phần mềm báo lỗi
![ảnh](https://user-images.githubusercontent.com/97272332/199393751-cb2a0b81-e0c3-4efe-b3e4-9dbda53133bc.png)
- Toa mới vẫn xem in được bình thường
![ảnh](https://user-images.githubusercontent.com/97272332/199393881-9a3cd233-29bb-4439-b910-5353e8499186.png)

**Comment by chauthanhtra** [comment]
- Đăng nhập ngày cũ thì toa thuốc cũ không báo lỗi, toa thuốc mới có mã toa thuốc báo lỗi
- Đăng nhập ngày mới thì toa thuốc mới có mã toa thuốc không lỗi, toa thuốc cũ báo lỗi

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.1103.1](http://www.fsend.vn/download/JHXPjHUyGVXL-3JCLmXGoMKpLs42WTBL)

**Comment by chauthanhtra** [comment]
cái para madonthuoc đó áp dụng theo ngày đăng nhập hả anh
đăng nhập ngày cũ in toa mới thì không thấy mã đơn thuốc

**Comment by nghivanbi** [comment]
lúc lập toa mới sinh madonthuoc, lập trước chưa có.

**Comment by chauthanhtra** [comment]
toa có có mã đơn thuốc rồi anh.
![ảnh](https://user-images.githubusercontent.com/97272332/199647698-615d9743-5413-444c-92b0-58371deae3f3.png)
![ảnh](https://user-images.githubusercontent.com/97272332/199647712-29679af8-dac3-4f6e-a559-43d5c22c5418.png)

**Comment by nghivanbi** [comment]
Xác nhận lỗi này, vì để truy cập nhanh hiện tại chỉ lấy trong tháng. Để xem xét hiệu chỉnh cho phù hợp.

**Comment by chauthanhtra** [comment]
em đóng lỗi này nha
