### ISSUE TITLE
Lỗi - Phiếu chỉ định CLS tổng hợp tự thiết kế trên Prescription mới không có mẫu mặc định

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#59]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **3/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả BV**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_laost_xn`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022000002` - _**MaKB**_: `2211000002` - _**MaBA**_: `MaBA` _**NgayKCB**_: `3/11/2022` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `11` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Không có mẫu in phiếu chỉ định CLS tổng hợp trên Prescription mới phải vào thiết kế lại từ đầu
![ảnh](https://user-images.githubusercontent.com/97272332/199672498-4f0ff183-b4cb-4202-81c2-a524bfa0d33a.png)
![ảnh](https://user-images.githubusercontent.com/97272332/199672578-ae31e564-2225-49e3-89c2-f50ae66040f8.png)

**Comment by nghivanbi** [comment]
Cập nhật: [v3.22.1103.2](http://www.fsend.vn/download/j-cj82tBxZlESIWkAyqU5uJ0mpI1X2EM)

**Comment by chauthanhtra** [comment]
còn chưa in được nha anh
![ảnh](https://user-images.githubusercontent.com/97272332/199682960-89714f58-3b82-4254-9962-d4693959bd6b.png)
![ảnh](https://user-images.githubusercontent.com/97272332/199682990-5b930a06-3f9e-4aec-baca-ddb0de26b28d.png)
