### ISSUE TITLE
Lỗi - không hiển thị được số lượng thuốc xuất tủ trực khi số lượng là số thập phân

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#6]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Quãng Ngãi**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_quangngai_full_amkho_new`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1N672BCHLMXP3xrDsQmlX9EXCSGvLniDv/view?usp=sharing)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022025079` - _**MaKB**_: `2207000904` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `A1-17` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Thống kê Xuất theo đối tượng, bảng kê xuất tủ trực không thể hiện được số lượng thuốc xuất nhưng vẫn có thành tiền do số lượng xuất là số thập phân có 2 số lẻ

![ảnh](https://user-images.githubusercontent.com/97272332/177497715-8ac58e80-dfcc-471f-8bfa-a118908584cc.png)
![ảnh](https://user-images.githubusercontent.com/97272332/177497747-89b6294f-387c-4a6a-a92c-4842c925fba2.png)
![ảnh](https://user-images.githubusercontent.com/97272332/177497773-4e199836-20f4-4895-9457-fa240bcfb06a.png)

**Comment by nghivanbi** [comment]
Báo cáo này được chưa Trà?

**Comment by chauthanhtra** [comment]
- Xem chi tiết theo bệnh nhân thì còn hiển thị 1 số lẻ
![ảnh](https://user-images.githubusercontent.com/97272332/182064917-7fab7104-f195-4890-a154-d80547b1e484.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.0802.1](http://www.fsend.vn/download/BH3KGkQbP0fsuzkeid3SgsfDws3hyCKV)

**Comment by chauthanhtra** [comment]
được rồi anh
