### ISSUE TITLE
Yêu cầu - Cảnh báo tương tác thuốc.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#60]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_tthanhtri_matdienbien2`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu có cảnh báo tướng tác thuốc khi bấm nút lưu của thoa thuốc sư dụng chức năng lấy lại toa.
Vì có trường hợp, Khoa Dược cấu hình tương tác thuốc sau lần ra toa đầu tiên, đến làn 2 lấy lại toa thì pm không cảnh báo theo cấu hình.

Mã KB: 2210001371
Ngày khám: 10/11/2022

![image](https://user-images.githubusercontent.com/99630883/200999341-9892ef6a-c2ab-454c-89e6-95267ec7b716.png)

**Comment by nghivanbi** [comment]
https://github.com/dh-hos/dhg.hospitalprescription/issues/62#issuecomment-1317971094
