### ISSUE TITLE
Yêu cầu - BV Vĩnh Thạnh: Thêm para ngày tháng năm sinh vào toa thuốc theo thông tư 04

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#61]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14-11-2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

- Mẫu toa thuốc theo TT04/2022 yêu cầu ghi ngày tháng năm sinh bệnh nhân lên toa thuốc. hiện tại chưa có para
![ảnh](https://user-images.githubusercontent.com/97272332/201560367-cb44aea3-c142-4fdd-834a-659c0b1c136d.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription  [v3.22.1114.1](http://www.fsend.vn/download/sIr5EkskTRZjrgmcPKx0wgmBko6jzlxK)
