### ISSUE TITLE
Yêu cầu - PK Lê Thành: Chữ ký điện tử toa thu phí, toa BH để trống cho bác sĩ ký tay

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#63]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `75407`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Lê Thành**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_lethanh_full_thongtuyen`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

- PK yêu cầu thêm chữ ký điện tử của bác sĩ lên toa thu phí (kể cả toa mua ngoài của đối tượng BH), để trống chữ ký trên toa BHYT cho bác sĩ tự ký tay
![ảnh](https://user-images.githubusercontent.com/97272332/202352705-d47a980e-c00c-43fd-b928-cd8fbb605949.png)

**Comment by nghivanbi** [comment]
Cập nhật: v3.22.12.14.2
