### ISSUE TITLE
Lỗi - PK Medic SG: BANT YHCT tính sai số ngày điều trị ở hồ sơ bệnh án

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#64]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Medic SG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_medicsg_songaydieutri`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022004857` - _**MaKB**_: `2210003002` - _**MaBA**_: `N2022001495` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `P22` - _**MaDV**_: `10` - _**ThangKT**_: `11` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Số ngày điều trị trên hồ sơ bệnh án YHCT bị âm
- Khi ngày của tháng xuất viện nhỏ hơn ngày của tháng vào viện thì số ngày điều trị bị âm
- Ví dụ: vào viên ngày 21/10/2022 ra viện ngày 01/11/2022 thì số ngày điều trị bị âm
![ảnh](https://user-images.githubusercontent.com/97272332/202641345-2c5c655e-47a7-4385-939e-92a42e7fa500.png)
![ảnh](https://user-images.githubusercontent.com/97272332/202641377-b82b97eb-7ab3-43f3-b97f-08c6ddc769e1.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.1118.1](http://www.fsend.vn/download/j8w873_XG6eAVBIYEWYzSTm3mbTZm94a)
