### ISSUE TITLE
Lỗi - BV Medic SG: Lệch số ngày điều trị BANT YHCT và bảng kê 6556

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#68]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77120`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PKĐK Medic Sài Gòn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_medicsg_songaydieutribant`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022001155` - _**MaKB**_: `2211003346` - _**MaBA**_: `N2022001791` _**NgayKCB**_: `26/11/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `10` - _**ThangKT**_: `11` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Số ngày điều trị BANT YHCT lệch so với bảng kê 6556 -> Số ngày điều trị BANT YHCT tính theo giờ ra viện (nếu giờ ra viện nhỏ hơn giờ vào viện thì bị lệch số ngày)
![ảnh](https://user-images.githubusercontent.com/97272332/204172689-4981a0f7-1621-4ad5-b3e7-975ef516b1fb.png)
![ảnh](https://user-images.githubusercontent.com/97272332/204172704-0ee86d2d-22a5-40b2-9330-a275c4663cce.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.11.28.1](http://www.fsend.vn/download/ksaQi0xj1MUCWckSC5keESZiWJORHqcL)
