### ISSUE TITLE
Lỗi - PK Medic SG: Phần mềm báo sai đơn vị tuổi khi nhập cân nặng khi khám bệnh

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#69]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Medic**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_medicsg_songaydieutri`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022004861` - _**MaKB**_: `2211000004` - _**MaBA**_: `MaBA` _**NgayKCB**_: `30/11/2022` - _**MaPhong**_: `P22` - _**MaDV**_: `10` - _**ThangKT**_: `11` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Prescription báo sai đơn vị tuổi khi khám bệnh
- Nhận bệnh: ngày sinh 1/11/2016 -> phần mềm ghi nhận số tuổi: 72 tháng   (72 tháng 29 ngày)
- Khám bệnh phần mềm bắt nhập cân nặng nhưng khi nhập cân nặng phần mềm báo sai đơn vị tuổi
![ảnh](https://user-images.githubusercontent.com/97272332/204683397-83c2b8c8-cdcb-4e17-9b16-149f9644ab3a.png)
![ảnh](https://user-images.githubusercontent.com/97272332/204683409-6a4a990a-dedb-4b2a-9246-7c1a9873b68f.png)
![ảnh](https://user-images.githubusercontent.com/97272332/204683424-53bd51a6-cef9-4f22-ad3f-e79bb052d56f.png)

**Comment by nghivanbi** [comment]
Cập nhật :
Prescription:[ v3.22.1213.2](http://www.fsend.vn/download/uTmiYRCHfMKRIArxyduIzGPzACkYTtEQ)
