### ISSUE TITLE
Yêu cầu - Thống nhất cách ghi nhận tỷ lệ và thành tiền cls giữa Prescription và Treat

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#70]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dktpct_cls0d`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)
   > _**MaBN**_: `2022088666` - _**MaKB**_: `2212000001` - _**MaBA**_: `000001` _**NgayKCB**_: `05/12/2022` - _**MaPhong**_: `53` - _**MaDV**_: `18` - _**ThangKT**_: `12` - _**NamKT**_: `2022`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DI2724779`
```
Danh mục cls macls: DI2724779 có tỷ lệ: 100 và giá dịch vụ 0đ, được hưởng bhyt

Prescription khi chỉ định bỏ check thanh BHYT sẽ ghi nhận tỷ lệ = 0
bệnh cho nhập viện và chuyển vào nội trú

Treatment khi chỉnh check dịch vụ thì ghi nhận đơn giá = 0, tỷ lệ = 0 và Thành tiền = 0
lúc này khi chỉnh lại bỏ check dịch vụ hoặc chuyển qua bhyt thanh toán vẫn không set lại được thành tiền!

-> đề xuất thống nhất lại cách ghi nhận tỷ lệ khi chỉ định cls giữa 2 module để không ghi nhận sai giá và thành tiền cls 
-> hoặc cách tính thành tiền và đặt tỷ lệ khi điều chỉnh cls.

```
DM CLS
![image](https://user-images.githubusercontent.com/96155021/205535090-5bf8fad2-56a9-4316-87a9-7046a5a2691f.png)
Prescription: khi chỉ định
![image](https://user-images.githubusercontent.com/96155021/205535158-c0577a5c-74d3-45c9-ad79-14f297ee1852.png)
Treatment: khi điều chỉnh cls
![image](https://user-images.githubusercontent.com/96155021/205535278-a69476a2-910e-4bf3-aa2f-32975305395f.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v2.22.1213.3](http://www.fsend.vn/download/U7YMdITcoc7jOcmwRM_ihqTEUFlA4aq2)

**Comment by le-an-87** [comment]
Đã cập nhật! khi chỉ định cls bỏ check thanh bhyt Prescription không set lại tỉ lệ = 0 (PrescriptionSetup20221214)
