### ISSUE TITLE
Lỗi - Lỗi chức năng lấy thông tin thẻ bhyt (F2)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#71]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_cairang_sokhambenh_arv`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Lỗi chức năng lấy thông tin thẻ bhyt

```
Lỗi chức năng lấy thông tin thẻ bhyt
![image](https://user-images.githubusercontent.com/96155021/207211519-dc9baa30-1dd3-4a2c-b944-38e40d19929b.png)
![image](https://user-images.githubusercontent.com/96155021/207211576-21b0e902-113e-4928-b5c0-7813360251d8.png)
![image](https://user-images.githubusercontent.com/96155021/207211587-ec78838c-8d7f-4d0d-bdaf-d403ca2562d2.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.22.1213.1](http://www.fsend.vn/download/kjj-I7s-J6OFvZRvpRPeB6MGnB4sdbqL)

**Comment by le-an-87** [comment]
đã fix!
