### ISSUE TITLE
Yêu cầu - BA ngoại khi kết thúc điều trị thông báo Chọn diễn biến sau cùng để thực hiện

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprescription#72]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Medic Miền Đông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_medicmd_bant`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
BA ngoại, khi Kết thúc điều trị thông báo Chọn diễn biến sau cùng để thực hiện
(chỗ Medic Miền Đông yêu cầu bỏ chức năng này, bản cũ nó không có)
Chỉ cần nhấn vào Kết thúc điều trị chứ không làm thêm thao tác Chỉnh diễn biến
PK Medic Miền Đông: các bs muốn thao tác như trên phiên bản cũ 3.22.0913.4. Không cần làm thêm bước Chỉnh diễn biến mới cho Kết thúc ĐT được.
```
![image](https://user-images.githubusercontent.com/98437757/207766982-73fd53bf-9ff0-474f-8f92-6c5329591d14.png)

**Comment by minhduc2it** [comment]
Báo thêm Lỗi: Khi Chỉnh Diễn biến thì Giơ diễn biến lấy theo giờ hiện tại
Khi đó Các chỉ định CLS trước đó có giờ chỉ định nhỏ hơn giờ Diễn biến 

![image](https://user-images.githubusercontent.com/98437757/207767723-85aa740c-9cda-42bd-a1e8-1201f9429ea0.png)

![image](https://user-images.githubusercontent.com/98437757/207767779-5eaac683-baa2-4f8c-b189-2a1f291ce459.png)

**Comment by nghivanbi** [comment]
Cập nhật: [v3.22.1216.1](http://www.fsend.vn/download/93O7w9HEl70rhgLMrtjBTZX5qGP0sp7O)
- Có tác dụng khi lập bệnh án mới.
