### ISSUE TITLE
Yêu cầu - Thực hiện mô tả cập nhật mã toa thuốc

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalprescription#82]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**

https://github.com/dh-hos/Mo-ta-he-thong/blob/main/Bi%20-%20Mo%20ta%20bo%20sung%20sinh%20ma%20toa%20thuoc%20theo%20quyet%20dinh%2004_20230203v2.pdf

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.0206.1](http://www.fsend.vn/download/2bQUJlv5wgcoT99LJTOwA3BEzQS7-mXF)

**Comment by nghivanbi** [comment]
Cập nhật: giữ lại mã toa thuốc khi chỉnh
Prescription: [v3.23.0207.1](http://www.fsend.vn/download/7jGZOzpfSCoIj62xOgmFKo6BPTenPof6)

**Comment by le-an-87** [comment]
khi tạo quyển mới sai số bắt đầu!
![image](https://user-images.githubusercontent.com/96155021/217174610-5b2823ca-2510-4f0b-8e00-ea624ad30d98.png)
![image](https://user-images.githubusercontent.com/96155021/217174787-30b4993f-8639-4fbf-a0cf-a78854b1fd64.png)

**Comment by nghivanbi** [comment]
Fix, cập nhật:
Prescription: [v3.23.0207.2](http://www.fsend.vn/download/mdgIcYmWfmsGU-XzGZL5oGZhUgPq7Uva)

**Comment by le-an-87** [comment]
đã kiểm tra đúng theo mô tả!
