### ISSUE TITLE
Yêu cầu - BV ĐKTPCT: hỗ trợ script cập nhật đã khám bệnh án ngoại trú không có tên trên SKB

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#83]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **3/2/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV ĐKTP Cần Thơ **
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dktpct_skbnew`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Bệnh nhân BANT có khám bệnh nhưng không lên sổ khám bệnh do cột khambenh.dakham = 0
Cập nhật script cho năm 2022

![ảnh](https://user-images.githubusercontent.com/97272332/216873237-34601173-8681-4f21-bd83-cf040022681c.png)
![ảnh](https://user-images.githubusercontent.com/97272332/216873256-f85e117c-c057-4c9f-b4c4-1cfa9182dbfe.png)
![ảnh](https://user-images.githubusercontent.com/97272332/216873292-da8c253f-737d-42f6-8329-9dd61218b270.png)

**Comment by chauthanhtra** [comment]
anh hỗ trợ BV rồi phải không anh @nghivanbi

**Comment by nghivanbi** [comment]
rồi, này lỗi 2 chỗ anh cập nhật rồi nhờ check lại.
1. dakham = 0;
2. qtdieutri.maxt = Null
