### ISSUE TITLE
Lỗi - Xem Sổ thủ thuật - sổ phẫu thuật báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#86]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_ct_dutru_tutruc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
**MaDV**_: `10` - **MaPhong**_: `01` - _**ThangKT**_: `02` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Xem sổ thủ thuật và sổ phẫu thuật báo lỗi!
```
![image](https://user-images.githubusercontent.com/96155021/217475819-99062b3a-82ef-4574-b4bf-15ee27a9532f.png)

**Comment by vinh-dh** [comment]
Này chờ tao up lại các DLL CLS nhe @nghivanbi

**Comment by vinh-dh** [comment]
Cập nhật lại DLL CLS nhé @nghivanbi! [Fix lỗi sổ TT/PT](https://github.com/dh-hos/oLibraries/commit/2a7fbcd6536b2a3f42a2b56a5849bab4631bfdca)

Có bổ sung thêm 1 số thông số cho các hàm. Build lỗi thì dò bổ sung vô.

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.02.08.1](http://www.fsend.vn/download/QeMzsCT7cHxwD9Y97NpHVz7v1F9yGGKc)

**Comment by le-an-87** [comment]
đã fix!
