### ISSUE TITLE
Lỗi - PK Bình An: Lỗi xem kết quả XN, CĐHA trong chẩn đoán, lịch sử bệnh trên Prescription 

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#87]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20ghi%20nhận-:-blue?style=plastic&logo=github) **9/2/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77114`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Bình An**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_binhan_kqxn_lichsubenh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020020714` - _**MaKB**_: `2302002799` - _**MaBA**_: `MaBA` _**NgayKCB**_: `8/2/2023` - _**MaPhong**_: `09` - _**MaDV**_: `03` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Phần mềm Prescription báo lỗi khi vào lịch sử bệnh xem kết quả Xét nghiệm, Chẩn đoán hình ảnh
- Lỗi khi xem kết quả CĐHA, XN trên lịch sử bệnh
![ảnh](https://user-images.githubusercontent.com/97272332/217696263-cf4a25f5-5eb5-43ca-ab92-dc485a6caec3.png)
- Kết quả trên Diagnose 
![ảnh](https://user-images.githubusercontent.com/97272332/217696349-a6ee0639-c752-43ce-87a3-fdfe42b7ef1c.png)

- Lỗi khi xem kết quả CĐHA, XN trên Form chẩn đoán
![ảnh](https://user-images.githubusercontent.com/97272332/217697957-8a0612c8-b3b7-411c-ac72-714ecbc82c3f.png)
- Kết quả trên Laboratory 
![ảnh](https://user-images.githubusercontent.com/97272332/217698525-ac854aae-a7e8-49ad-9ad6-34085f6cd02c.png)

**Comment by vinh-dh** [comment]
Lỗi này thì nó cũng giống với lỗi này: #86

Vào đó xem cách khắc phục nhe @chauthanhtra

**Comment by chauthanhtra** [comment]
Prescription 8/2/2023. 
- Xem kết quả XN ở lịch sử bệnh không lỗi, xem ở Tiện ích -> tra cứu lịch sử bệnh nhân vẫn lỗi
![ảnh](https://user-images.githubusercontent.com/97272332/217702865-980ab4ec-0d00-4101-abc6-6983eb902acc.png)
- Xem kết quả CĐHA form nào cũng lỗi

**Comment by chauthanhtra** [comment]
> Lỗi này thì nó cũng giống với lỗi này: #86
> 
> Vào đó xem cách khắc phục nhe @chauthanhtra

Vẫn còn mấy chổ chưa cập nhật hết. em đang dùng Prescription 8/2/2023

**Comment by vinh-dh** [comment]
> Prescription 8/2/2023.
> 
> * Xem kết quả XN ở lịch sử bệnh không lỗi, xem ở Tiện ích -> tra cứu lịch sử bệnh nhân vẫn lỗi
>   ![ảnh](https://user-images.githubusercontent.com/97272332/217702865-980ab4ec-0d00-4101-abc6-6983eb902acc.png)
> * Xem kết quả CĐHA form nào cũng lỗi

Lỗi này thì @nghivanbi kiểm tra nhe. Không giống với lỗi ở đầu topic.

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.02.10.1](http://www.fsend.vn/download/OQsa10PkDdbVcom-mE_wn7XUEw-ezeKF)
