### ISSUE TITLE
Lỗi - khi nhận bệnh tự động load lại sinh hiệu củ

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#88]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nhi Đồng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_nhidong_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022148549` - _**MaKB**_: `2209044539` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi đăng ký bệnh nhân Prescription tự load lại sinh hiệu bệnh của lần khám trước
-> dẫn đến sai sinh hiệu so với thực tế.

```
![image](https://user-images.githubusercontent.com/96155021/218421535-670bb27a-a918-4603-9218-1d781673c5ba.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription:[ v3.23.02.14.2](http://www.fsend.vn/download/okubccbNkWF6BlNhA76RqGUyekIYfgs8)

**Comment by le-an-87** [comment]
đã fix!
