### ISSUE TITLE
Lỗi - Không chuyển được cls có thành tiền =0 vào bệnh án ngoại trú được

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#9]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/7/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_chuyenclsbant`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022028343` - _**MaKB**_: `2207004622` - _**MaBA**_: `N2022005197` _**NgayKCB**_: `12/07/2022` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Không chuyển được cls có thành tiền =0 vào bệnh án ngoại trú được!
```
![image](https://user-images.githubusercontent.com/96155021/179171430-8f8560f5-5dfe-40a0-b528-f44135d38629.png)
chọn đồng ý nhưng vẫn không chuyển vào được
![image](https://user-images.githubusercontent.com/96155021/179171635-91a19e79-295d-4805-a069-04d5528e69ef.png)

**Comment by nghivanbi** [comment]
Cập nhật: Pre 20220715

**Comment by le-an-87** [comment]
chuyển được rồi mà dính vụ này anh ơi!
![image](https://user-images.githubusercontent.com/96155021/179180607-15b454bb-9f02-43ae-898b-cc7d6cf7dda3.png)
