### ISSUE TITLE
Yêu cầu - Hỗ trợ tiền ăn.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#92]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51214`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nội Tiết**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_noitiet_qni`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hiện tại chức năng hỗ trợ tiền ăn cho BN điều trị nội trú, lúc nhập viện cột **bnnoitru.tienhotro** dang lấy theo tham số **hotro.tienan**, nhưng phần mềm lại làm tròn, như hình tham số đang cấu hình 99,600, nhưng khi nhập viện thì bnnoitru.tienhotro lại làm tròn lên 100,000.

Đề nghị lấy theo đúng tham số cấu hình, vì quyết định của Tỉnh quy định bao nhiêu thì phải đúng như vậy, không được làm tròn.

![image](https://user-images.githubusercontent.com/99630883/222069766-f46fad01-41cd-423f-b1c2-5f9927a0b6aa.png)
![image](https://user-images.githubusercontent.com/99630883/222069876-ea1da18b-8881-428a-b48b-9cf2565426f0.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.0517.1](http://www.fsend.vn/download/gow16X42vI7U3ms7xrV4XZTmomq0FyPp)
