### ISSUE TITLE
Lỗi - Prescription ra toa không lấy được thuốc có trong tồn kho

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprescription#94]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94058`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Lao ST**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lao_st_chidinhthuoc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023001165` - _**MaKB**_: `2303000179` -  _**NgayKCB**_: `03/03/2023` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `16` - _**KhoLe**_: `KL` - _**MaHH**_: `T151` - `T150` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Đối tượng ngoại trú cấu hình lấy thuốc kho KL
thuốc mã T151 và T150 vẫn còn tồn kho trong kho KL
Prescription khi ra toa thuốc không lấy được các thuốc này
-> do kho lẻ KL thuộc kho 14 nhưng Mã thuốc T151 và T150 thuộc kho 16
* Đề xuất:
 1.  => Cho phép xuất cho bệnh nhân.
 2. => Chặn không cho xuất từ kho chẳn xuống kho lẻ không trực thuộc kho chẳn đó.
```
Cấu hình đối tượng
![image](https://user-images.githubusercontent.com/96155021/223012618-fc8cf203-46ab-4ed7-a00f-7b240cb50a73.png)
Ra toa
![image](https://user-images.githubusercontent.com/96155021/223012673-10f06897-d1d6-409b-acf4-d47aca26c57a.png)
Tồn kho
![image](https://user-images.githubusercontent.com/96155021/223012768-6159b8ad-7fc2-4521-9791-f8e4b53b9368.png)

**Comment by nghivanbi** [comment]
Cái này, trường hợp kho lẻ có nhiều cha, cho xuất nha, anh cập nhật lại cho nó.

**Comment by le-an-87** [comment]
Vậy cập nhật Prescription lại hé anh! em thêm trạng thái gấp nhe BV cần gấp để xuất cho bệnh nhân ngoại trú!

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.0308.2](http://www.fsend.vn/download/uPqsieMzRuW210zAewBUZ5B-8b0XZrqm)

**Comment by le-an-87** [comment]
Còn tồn kho nhưng phần mềm báo không đủ thuốc để cấp!
![image](https://user-images.githubusercontent.com/96155021/223614224-d27e6d05-f747-4628-bb3a-784610900e31.png)
![image](https://user-images.githubusercontent.com/96155021/223614248-dec40d7e-3adf-4542-ab74-9d5becb78009.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription:[ v3.23.0308.3](http://www.fsend.vn/download/pqKLeWmi61LwG8w5dMGYifgEHbhCSeLi)

**Comment by le-an-87** [comment]
Đã fix!
