### ISSUE TITLE
Yêu cầu - Thêm para chỉ số sinh hiệu.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#95]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `89015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch AG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_timmachag_chiso_fio2`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Lúc nhận bệnh có nhập 2 chỉ số như hình: Hb và FiO2
![image](https://user-images.githubusercontent.com/99630883/223015070-91460c7a-17ec-4a1c-b742-44e0e051cd2e.png)

Đề nghị khi thiết kế phiếu nhập viện thêm 2 para đó để hiển thị lên phiếu nhập viện. BV đang sử dụng tham số **nv.customize=1**

**Comment by lqbinh1987** [comment]
Nhờ anh @nghivanbi duyệt thực hiện phần này dùm em.

**Comment by nghivanbi** [comment]
Anh bổ sung 2 para tự kéo vô nhé

**Comment by nghivanbi** [comment]
Cập nhật :
Prescription: [v3.23.0622.1](http://www.fsend.vn/download/ZTdBHJ_mel4A4Fg_2qNhmZZBarjoDTFA)
