### ISSUE TITLE
Yêu cầu - Bắt thời gian phiếu PT/TT.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#97]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhtri_st_2023_02_10`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

- Chổ thời gian kết thúc, khi đưa chuột vô số phút -> nhấn phím mũi tên lên thì tăng lên 6p, hiện tại đang tăng 5p, mà BH thì chỉ tính đến phút và bắt phải lớn hơn 5p, =5p cũng bị BH bắt luôn.

![image](https://user-images.githubusercontent.com/99630883/223020566-f2fb7a43-29f0-4f78-bbc8-890ca45d856d.png)

- Khi lập phiếu PT/TT thì thời gian bắt đầu chỉ lớn hơn thời gian khám ở phòng khám hiện tại, vì hiện tại xảy ra trường hợp đối với BN chuyển phòng, thì thời gian bắt đầu của phòng khám sau có thể điều chỉnh ngay khi lập phiếu PT/TT, vô tình dẫn đến trường hợp thời gian bắt đầu phiếu PT/TT của phòng khám sau nằm trong khoảng thời gian khám của phòng khám trước đó, hoặc thời gian bắt đầu nằm trong thời gian thực hiện PT/TT của phòng khám trước đó.

**Comment by nghivanbi** [comment]
Bắt thêm thời gian phiếu PTTT phải sau phiếu PTTT có trước (nếu có)
