### ISSUE TITLE
Lỗi - Kiểm tra sai số ngày tối đa được phép chỉ định CLS đối tượng MIỄN PHÍ

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprescription#98]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **8/3/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdyct_lechtienthuoc_bant`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000002` - _**MaKB**_: `2303000002` - _**MaBA**_: `MaBA` _**NgayKCB**_: `8/3/2023` - _**MaPhong**_: `12` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DI20` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

(test lỗi)

Đối tượng miễn phí kiểm tra sai số ngày chỉ định CLS 
ví dụ: bệnh nhân miễn phí A chỉ định CLS mã DI20 có cấu hình số ngày chỉ định CLS là 1 thì khi bệnh nhân miễn phí B chỉ định CLS mã DI20 thì phần mềm báo chưa tới hạn chỉ định lại CLS đó
Đề xuất:
1. Không kiểm tra số ngày chỉ định CLS đối tượng Miễn phí
2. kiểm tra số ngày chỉ định CLS đối tượng Miễn phí theo mã bệnh nhân 

CLS mã DI20 có cấu hình số ngày tối đa chỉ định CLS
![ảnh](https://user-images.githubusercontent.com/97272332/223603250-cecd15a9-9be5-44a2-9906-dc72b551924a.png)

Bệnh nhân Nam thuộc đối tượng Miễn phí chỉ định CLS mã DI20 bình thường
![ảnh](https://user-images.githubusercontent.com/97272332/223603337-c5ef615e-9206-47a6-a73e-dfaaf976ab14.png)

Bệnh nhân Nữ thuộc đối tượng Miễn phí chỉ định CLS mã DI20 thì phần mềm báo CLS chưa tới hạn được phép chỉ định
![ảnh](https://user-images.githubusercontent.com/97272332/223603571-c21574a9-2cea-4750-aa3b-2ae56e62e096.png)

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription:[ v3.23.0309.1](http://www.fsend.vn/download/busty_nJ3TXZoUhbzQu_oK-h5xw0-17e)
