### ISSUE TITLE
Yêu cầu - Thời gian ra toa lớn hơn thời gian khám

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#99]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Đề nghị bổ sung thêm thông báo chặn không cho người dùng ra toa nếu thời gian từ lúc khám bệnh(cụ thể là thời gian chỉ định tiền công khám) đến thời gian ra toa < 60 giây.
Vì hiện tại có 1 số BV, giám định BH đang bắt trường hợp thời gian ra toa bằng với thời gian khám bệnh, XML chỉ tính đến đơn vị thời gian là **phút**(do BS khám nhanh quá).
Ví dụ thời gian công khám là 07:01:01, mà thời gian lập toa thuốc là 07:01:59, trong xml thì cả bảng 2 và bảng 3 gửi dữ liệu 07:01 => BH bắt, lý do là thời gian ra toa bằng với thời gian khám.

**Comment by nghivanbi** [comment]
Cập nhật:
Prescription: [v3.23.0315.1](http://www.fsend.vn/download/FIsHyPWgLj2MTo6cz_KaX3GDSD6DVIqh)
